### ISSUE TITLE
Number field is cleared for some invalid inputs in some scenarios

### ISSUE THREAD

**Issue by v6ak** [material-components/material-components-web#2647] opened 2018-04-26 14:17 UTC
### What MDC Web Version are you using?

0.35.0

### What browser(s) is this bug affecting?

Verified mostly in Firefox ESR (Debian) and briefly in fresh Firefox (Fedora):

* Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
* Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

Some other browsers prevent inserting non-numeric characters to the input field, which prevents the issue.

### What OS are you using?

Debian 9 / Fedora 26.

### What are the steps to reproduce the bug?

1. Go to https://codepen.io/anon/pen/WJGdgr
2. Type a number into the textfield, e.g., “1”.
3. Add a non-number character after the number (or anywhere else), without deleting the number. (for example, you will have typed “1j”)
4. Look at textfield content.

### What is the expected behavior?

The textfield content remains as typed (e.g., “1j”), maybe with some indication that it contains an invalid value.

### What is the actual behavior?

The textfield is empty.

### Any other information you believe would be useful?

* When typing a non-number character first, it does not happen.
* See the comments in the codepen.
* Originally, I have had the issue with Scala.JS+UDash, which is a very similar case, but I have tried some more variants: https://scalafiddle.io/sf/To8q48O/5

**Comment by bonniezhou** [comment] 2018-05-08 06:53
Hi @v6ak , thanks for filing this!

It seems that this issue only happens when you try to set `textNode.nodeValue = field.value`. Can you explain the use case where you need to do this? I haven't dug much into why this is happening, but it's specific to Firefox so I suspect this is a feature implemented by the browser in the native input element.

As for error indication, the bottom line of the text field becomes red once you blur the text field to indicate that the input value is invalid.

**Comment by v6ak** [comment] 2018-05-08 07:09
Hello,
I see the minimum reproduction case does not explain the use case. In the original code (which is public, but there is much other code around), I use it as a kind of autocompletition – you type participant number and the name is autocompleted. Searching for participant name was removed from the minimum reproduction case, so it looks more artificial. As far as I see, it depends on the expression (field.value.substr(1) reproduces the issue, while "x" doesn't, not sure why).

On being Firefox-specific: Firefox allows typing non-numeric characters in those fields. Chromium rejects such input immediatelly, so you cannot even perform reproduction step 3. You can press a letter key, but it does not produce any text even on bare <input type="number"> with no scripts/stylesheets.

**Comment by bonniezhou** [comment] 2018-05-21 17:47
Thanks for your feedback. It seems like issue is related to a couple of things:
1. Our text field doesn't support `number` as an input type at the moment, which we've noted in the [README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#basic-usage).
2. When a non number character is entered into the field, the value of the input becomes an empty string (because the input is invalid). Each browser handles this differently with regards to what they render on the screen (whether they prevent inserting non-numeric characters or not) and we don't intend to force consistency across browsers.

**Comment by v6ak** [comment] 2018-05-21 18:22
Hello,

>1. Our text field doesn't support `number` as an input type at the
>moment, which we've noted in the
>[README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#basic-usage).

Thank you for clarification, I've missed it.


>2. When a non number character is entered into the field, the value of
>the input becomes an empty string (because the input is invalid). Each
>browser handles this differently with regards to what they render on
>the screen (whether they prevent inserting non-numeric characters or
>not) and we don't intend to force consistency across browsers.

I don't expect MCW to force such consistency in the first place. I rather want it not to break the number input. This issue is a case where MCW makes user experience in some way worse than with vanilla HTML.

**Comment by kfranqueiro** [comment] 2018-05-21 19:09
Firstly, we agree that we'd ideally like for MDC Text Field to not break `number` and other specialized types of inputs. :) However, this would require finding a way to access the "raw" value entered into the input. Invalid input in `number` fields reports its `value` as an empty string, which is what prevents us from properly detecting when the field is filled but invalid. That's why we currently list this limitation in the README.

I'm going to close this and track #2744 since it more concisely describes the root problem.

**Closed by kfranqueiro** 2018-05-21 19:09 UTC

**Comment by williamernest** [comment] 2018-05-25 23:33
Resolved with #2781

**Comment by williamernest** [comment] 2018-09-16 15:04
@v6ak That fiddle is incorrect and it adding the value of the input to the inside of the input element, resulting in the odd behavior you are seeing. Here's a codepen of a text field working with a number input type. 

It looks like in your pen you are binding the value of the input to render in the middle of the textfield resulting in html that looks like: 
```
<div class="mdc-text-field">
  <input class="mdc-text-field__input" type="number" value="12345">
  12345
  <div class="mdc-line-ripple"></div>
</div>
```
You could try binding the value to a separate div that is not within the text field. 
Example:
https://scalafiddle.io/sf/a1eQEms/0

https://codepen.io/anon/pen/OooOmJ

**Comment by v6ak** [comment] 2018-09-16 18:38
I feel a bit ambivalent:

On one hand, you are right. I am using it in an unintended way.

On the other hand, until I understand why this happens, I am afraid of happening it again under some other circumstances. The behavior is quite strange and beyond what I would expect that could be caused by breaking such a rule.

**Comment by williamernest** [comment] 2018-09-16 19:00
@v6ak You're using an input in a way it wasn't designed to be used, by setting the textContent of the input element using a DOM API (`nodeValue`) instead of using an HTMLElement API (`value`). The input element retains it's data in the `value` attribute, and is not intended to be used with a text node inside of the element. 

The textNode inside the input element is rendering as normal text inside the parent div, which causes the text to be aligned after the input element but within the text-field box. 

This is working as intended. 

Here's some follow up links that may help 
https://www.w3.org/TR/html52/sec-forms.html#the-input-element
https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-BBACDC08

**Comment by v6ak** [comment] 2018-09-16 19:40
You seem to have misread it. In both cases, I am modifying some TextNode after the input element, not the input element itself. This is perfectly legal from W3's point of view. In the Scala version, it should be pretty obvious what I am modifying. In the JS version (i.e. my version at https://codepen.io/anon/pen/WJGdgr ), it might be less clear, but not so hard: formItem.childNodes[0] in a TextNode (just a whitespace), formItem.childNodes[1] is the input element and formItem.childNodes[

On September 16, 2018 9:00:58 PM GMT+02:00, Will Ernest <notifications@github.com> wrote:
>@v6ak You're using an input in a way it wasn't designed to be used, by
>setting the textContent of the input element using a DOM API
>(`nodeValue`) instead of using an HTMLElement API (`value`). The input
>element retains it's data in the `value` attribute, and is not intended
>to be used with a text node inside of the element. 
>
>The textNode inside the input element is rendering as normal text
>inside the parent div, which causes the text to be aligned after the
>input element but within the text-field box. 
>
>This is working as intended. 
>
>Here's some follow up links that may help 
>https://www.w3.org/TR/html52/sec-forms.html#the-input-element
>https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-BBACDC08
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/material-components/material-components-web/issues/2647#issuecomment-421813792

-- 
Sent from my fruity BlackBerry phone. Please excuse my brevity.

**Comment by v6ak** [comment] 2018-09-16 19:51
EDIT: Sorry, I have sent it by accident to early, so I had to add more details.

You seem to have misread it. In both cases, I am modifying some TextNode after the input element, not the input element itself. This is perfectly legal from W3's point of view. In the Scala version, it should be pretty obvious what I am modifying. In the JS version (i.e. my version at https://codepen.io/anon/pen/WJGdgr ), it might be less clear, but not so hard: formItem.childNodes[0] in a TextNode (just a whitespace), formItem.childNodes[1] is the input element and formItem.childNodes[2] is a TextNode after the input field.

I know that using childNodes[2] is not a good idea for best readability, but it was a way to make a minimum reproduction sample without introducing any additional dependency. You can see the same in the Scala version, but more readable (using a binding instead of formItem.childNodes[2]).

**Comment by williamernest** [comment] 2018-09-16 20:01
The parent `mdc-text-field` class is where we apply the "box" style for the filled variant. Any text nodes that are immediate children of this element are unsupported and will cause the text to be rendered before or after the input, but within the box. You can add another element after the text-field to render the value of the text field as an alternative. Again, this is working as intended and we don't plan on supporting the use case you're describing.
