### ISSUE TITLE
[Bug] MDCSlider wont accept any min values that are larger than 100

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4133] opened 2018-12-02 03:55 UTC
## Bugs

There seems to be an issue with the MDCSlider. If you have the `aria-valuemin` set to a value that is larger that 100, even though the `aria-valuemax` is larger than the `aria-valuemin` value, it will throw an error into the console saying that `aria-valuemin` cant be over the sliders maximum value.

### What MDC Web Version are you using?

> 0.41.1

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> MacOS 10.14.1

### What are the steps to reproduce the bug?

> On a slider, have the `aria-valuemin` set to something that is above 100, and have the `aria-valuemax` be set to somethign that is bigger than the `aria-valuemin`
> Visit CodePen [here](https://codepen.io/anon/pen/QJYBwg?editors=1000)

### What is the expected behavior?

> The `aria-valuemin` should base its self off the `aria-valuemax` rather than basing its self off 100

### What is the actual behavior?

> It throws an error into the console saying that the `aria-valuemin` cant be over the sliders maximum value

**Comment by williamernest** [comment] 2018-12-04 23:23
Thanks for filing this issue. This is a duplicate of #2269 and should be resolved when the new slider lands.

**Closed by williamernest** 2018-12-04 23:23 UTC
