### ISSUE TITLE
MDC Drawer 0.28.0 issues with iOS devices

### ISSUE THREAD

**Issue by jordyboytjuh** [material-components/material-components-web#2041] opened 2018-01-23 12:46 UTC
### What MDC Web Version are you using?

> 0.28.0

### What browser(s) is this bug affecting?

> Ipad / Iphone Safari browser

### What OS are you using?

> iOS 11.2.2

### What are the steps to reproduce the bug?

> You can find the issue on the demo page with the temporary drawer. Opening this drawer works as expected, when you close the drawer, it's completely stuttering till it's closed. I don't know if the issue is caused by the MDC update, or by the iOS update. 

### What is the expected behavior?

> Should animate the same way as it opened. 

### What is the actual behavior?

> Closing causes stuttering drawer

**Comment by bonniezhou** [comment] 2018-01-25 18:30
Duplicate of #1700.
Thanks for filing this issue! Feel free to add your +1 to #1700 so we can gauge how many people are experiencing this.

**Closed by bonniezhou** 2018-01-25 18:30 UTC
