### ISSUE TITLE
anchored menu not closing on iOS Safari

### ISSUE THREAD

**Issue by dohomi** [material-components/material-components-web#4441] opened 2019-02-22 13:17 UTC
### What MDC Web Version are you using?

Current catalog of: https://material-components.github.io/material-components-web-catalog/

### What browser(s) is this bug affecting?

latest Safari

### What OS are you using?

latest iOS

### What are the steps to reproduce the bug?

Open https://material-components.github.io/material-components-web-catalog/#/component/menu on iOS and click on anchored menu item

### What is the expected behavior?

click outside after open the menu: should close the menu

### What is the actual behavior?

Menu stays open and its not closing at all, only if any menu item clicked, then its closing.

**Comment by acdvorak** [comment] 2019-02-25 21:02
Thanks for filing this issue! 😀 

Unfortunately this is due to an old [event bubbling bug in iOS](https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html#link2). Mobile Safari doesn't propagate the `click` event unless the target element has an event handler or `tabindex` attribute.

One workaround is to add an empty `'click'` event handler to an element inside the `<body>` (but not the `<body>` itself). E.g.: https://glitch.com/~purple-comet . See #693 for other potential workarounds.

Closing this as a duplicate of #693.

**Closed by acdvorak** 2019-02-25 21:02 UTC
