### ISSUE TITLE
Temporary drawer is not closing smoothly with latest iOS

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#1838] opened 2017-12-28 10:15 UTC
### What MDC-Web Version are you using?

> 0.27.0

### What browser(s) is this bug affecting?

> Mac Safari, Ipad, Iphone

### What OS are you using?

> iOS 11.2.1

### What are the steps to reproduce the bug?

> https://material-components-web.appspot.com/drawer/temporary-drawer.html
> Open above link with iOS device with latest version (11.2.1).
> Click on the hamburger menu icon to open the drawer.
> Tap outside of the drawer to close the drawer.
> you can see closing drawer very slowly.

### What is the expected behavior?

> Drawer should open and close smoothly.

### What is the actual behavior?

> The close animation of the drawer is janky/laggy.

**Comment by thosakwe** [comment] 2017-12-29 17:14
Also occurs on Safari on Mac

**Comment by dkarandana** [comment] 2018-01-02 05:13
I'm experiencing the same issue on my mac with latest safari.

**Comment by acdvorak** [comment] 2018-01-04 23:24
Duplicate of #1700

**Closed by acdvorak** 2018-01-04 23:24 UTC

**Comment by acdvorak** [comment] 2018-01-04 23:25
Thanks for filing this issue and adding your comments!

Please feel free to add your +1 to #1700 so we can gauge how many people are experiencing this 🙂
