### ISSUE TITLE
MDC-Select custom max-height is not handled correctly

### ISSUE THREAD

**Issue by drcampbell** [material-components/material-components-web#2284] opened 2018-02-21 17:10 UTC
### What MDC Web Version are you using?

0.31.0

### What browser(s) is this bug affecting?

All

### What OS are you using?

Mac OS X, Windows

### What are the steps to reproduce the bug?

Create a select input
Fill the select menu with 100 items or something reasonably large
Set the mdc-menu class to a max-height of 400px
Select a list item far down the list
Open the menu
Observe it doesn't open in the correct location

### What is the expected behavior?

The menu opens over the select input.

### What is the actual behavior?

The menu opens at the top of the page

**Comment by drcampbell** [comment] 2018-02-21 17:16
Made a pull request for this:
https://github.com/material-components/material-components-web/pull/2285

**Comment by moog16** [comment] 2018-02-22 06:10
@drcampbell thanks for creating the PR. I created a (Codepen)[https://codepen.io/moog16/pen/RQJoom] to reproduce your issue. I'm just wondering if you could check it out, and see if this is the correct setup?

**Comment by drcampbell** [comment] 2018-02-22 15:31
@moog16 
Hi Moog.  I modified your Codepen to demonstrate the issue clearly by just adding a margin wrapper to the top of the input:
[Codepen](https://codepen.io/dcam/pen/YevJEM)

**Comment by moog16** [comment] 2018-02-22 21:29
@drcampbell I'm seeing this happen. Is this issue you are referring to? I just want to make sure we are looking at the same issue.

<img width="271" alt="screen shot 2018-02-22 at 13 28 36" src="https://user-images.githubusercontent.com/579873/36565104-51db2b22-17d4-11e8-8fce-00849c316366.png">

**Comment by drcampbell** [comment] 2018-02-23 02:00
@moog16 Yep, that's the issue alright!

**Comment by moog16** [comment] 2018-04-02 16:57
This is no longer an issue since we have moved to using only native select in #2462. Closing.

**Closed by moog16** 2018-04-02 16:57 UTC
Labels: in-tracker

**Comment by Slion** [comment] 2022-02-11 11:20
I landed here after searching for --mdc-menu-max-height. It does not look like that variable is working menu height is stuck at 120px somehow as it get's injected into the element. Fortunately I could workaround it using max-height !important.
