### ISSUE TITLE
[TextField] Helper text + Helper error text

### ISSUE THREAD

**Issue by YouraHalloween** [material-components/material-components-web#6607] opened 2020-11-12 11:48 UTC
## Feature Request

Hello!
How to implement HelperText + HleperText error for all TextEdit?
If there is an input error, then HelperText disappears and an error message appears.
I think we need to inherit MDCTextFieldHelperTextFoundation and remake the prototype.setValidity method. Error message take from **`aria-validation-msg-require = "Password cannot be empty" aria-validation-msg-max-len = "..."`**
How do you like that idea?
Sample code: 
```
<label class="mdc-text-field mdc-text-field--filled">
    <span class="mdc-text-field__ripple"></span>
    <span class="mdc-floating-label" id="my-label-id">Password</span>
    <input class="mdc-text-field__input" type="password" aria-labelledby="my-label-id" required minlength="8"
    aria-labelledby="my-label-id"
    aria-controls="username-helper-text1"
    aria-describedby="username-helper-text2">
    <span class="mdc-line-ripple"></span>
</label>
<div class="mdc-text-field-helper-line">
    <div id="username-helper-text1" class="mdc-text-field-helper-text mdc-text-field-helper-text--persistent" aria-hidden="true">
Enter password
    </div>
    <div id="username-helper-text2" class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
Password cannot be empty
    </div>
</div>
```

P/S 
On the Vue, I did just that. And in JavaScript I do not understand how to change it.

**Comment by YouraHalloween** [comment] 2020-12-11 13:04
Hi! Here's the implementation
[Github ticket 6656](https://github.com/material-components/material-components-web/issues/6656)

**Comment by joyzhong** [comment] 2020-12-11 18:43
Closing, this is a dupe of https://github.com/material-components/material-components-web/issues/6656

**Closed by joyzhong** 2020-12-11 18:43 UTC
Labels: feature-request
