### ISSUE TITLE
Error in Toolbar docs class name

### ISSUE THREAD

**Issue by neclepsio** [material-components/material-components-web#378] opened 2017-03-03 14:05 UTC
The docs say: "When using `mdc-toolbar--fixed`, you can add the `mdc-toolbar-fixed-adjust` helper class to the toolbar's adjacent sibling element..."

The name of the class is `mdc-toolbar__fixed-adjust`.

**Comment by Garbee** [comment] 2017-03-03 15:06
Duplicate of #320 perhaps?

**Comment by neclepsio** [comment] 2017-03-03 16:23
Yes. I just searched in open issues.

**Closed** 2017-03-03 17:36 UTC
