### ISSUE TITLE
Image overflowing the cell div

### ISSUE THREAD

**Issue by partulaj** [material-components/material-components-web#406] opened 2017-03-17 22:28 UTC
### What MDC-Web Version are you using?

material-components-web@0.6.0

### What browser(s) is this bug affecting?

>This bug is affecting Firefox 52.
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

### What OS are you using?

>Windows 10 Version 1607

### What are the steps to reproduce the bug?

http://codepen.io/anon/pen/EWojwo

### What is the expected behavior?

>The image should not overflow the cell div 

### What is the actual behavior?

>The image overflow the cell div so it is superposing iwith the other cell div

### Any other information you believe would be useful?

>There is no problem on Chrome 56 and Edge 14. 
It seems to be due to a width: auto;.

**Comment by amsheehan** [comment] 2017-03-21 13:55
Good catch! Your assumption appears to be correct in that the culprit CSS is the `width: auto` rule set on the image. If you are up for it, we _do_ accept pull requests and would love to work with you to get this one resolved. If not, that's fine too and we'll get it resolved for the community.

**Comment by vivekmarakana** [comment] 2017-03-23 05:05
@amsheehan Adding a rule `max-width: 100%` should help it solve for this and other overflowing image issues. If it sounds plausible solution, I can add it and open a PR.

**Comment by amsheehan** [comment] 2017-03-23 05:08
Sounds good to me!

**Comment by partulaj** [comment] 2017-03-23 15:41
Thanks I didn't get the time to search a solution but the `max-width: 100%` solved my problem when I try it

**Comment by traviskaufman** [comment] 2017-03-24 16:53
Hey @vivekmarakana so after [commenting on your PR](https://github.com/material-components/material-components-web/pull/427#discussion_r107948686), I [forked your pen](http://codepen.io/traviskaufman/pen/aJKRjO) and removed the `mdc-layout-grid__cell` class from the image, replacing it with a style rule that sets `width: 100%; height: 100%;` on the image. Is this the behavior that you're looking for? If not, could you please describe the intended behavior that you are looking for? I think we _may_ have misunderstood what you meant when you said "The image overflow the cell div so it is superposing iwith the other cell div" 😄 Thanks!

**Comment by partulaj** [comment] 2017-03-24 19:33
@traviskaufman 
Yes that was what the behavior I was looking for.
Sorry, I think I might have made a bad explanation of the behavior I was looking for, but to sum up I was looking for a behavior similar to Bootstrap `.img-responsive`

**Comment by traviskaufman** [comment] 2017-03-24 19:33
Interesting...so do we even need an issue / PR for this? cc @amsheehan @vivekmarakana

**Comment by partulaj** [comment] 2017-03-24 19:42
@traviskaufman I think one would be good because I redo some test and put the image in a `<div>`with the `mdc-layout-grid__cell` and it seems that if the image is bigger than the cell the image overflow.
So I think your last pen coud be a good idea .

Here the pen of the problem http://codepen.io/anon/pen/peKGGB

**Comment by vivekmarakana** [comment] 2017-03-25 04:41
@traviskaufman Looks good. We can even remove PR. My main concern was what happens when we try to nest grids. I've updated [my pen](http://codepen.io/vivekmarakana/pen/VpxqJa) to show that if we try to add another grid within a grid cell, overflowing is still there.

**Comment by traviskaufman** [comment] 2017-03-28 14:38
Cool, closing :)

**Closed by traviskaufman** 2017-03-28 14:38 UTC
Labels: bug, help wanted
