### ISSUE TITLE
Misaligned title with flexible waterfall on desktop

### ISSUE THREAD

**Issue by cdiener** [material-components/material-components-web#890] opened 2017-07-01 21:07 UTC
### What MDC-Web Version are you using?

mdc-toolbar 0.4.1

### What browser(s) is this bug affecting?

Chrome 58, probably all

### What OS are you using?

Linux

### What are the steps to reproduce the bug?

Go to the following example on codepen: https://codepen.io/anon/pen/JJLJmM , which is your own demo at full width. Use a desktop window with a width > 600px. Scroll down to trigger the flexible behavior until the toolbar is minimized (expansion ratio == 0).

### What is the expected behavior?

Upon scrolling down the Title and menu icon should be aligned in the minimized toolbar.

### What is the actual behavior?

Title and menu icon are misaligned.

### Any other information you believe would be useful?

Current alignment in the flexible waterfall toolbar actually only works on small screens due to fixed height of 56px. Desktop uses 64px which seems to break the alignment.

**Comment by amsheehan** [comment] 2017-07-06 18:39
Looks like this is a possible duplicate of https://github.com/material-components/material-components-web/issues/845

If not, it certainly seems like they're both symptoms of the same problem. Please continue future conversation there. Thanks!

**Closed by amsheehan** 2017-07-06 18:39 UTC

**Comment by cdiener** [comment] 2017-07-06 18:59
Ok.
