### ISSUE TITLE
MDC List with trailing check box hover bug 

### ISSUE THREAD

**Issue by BhavyaSingh2611** [material-components/material-components-web#4657] opened 2019-04-28 11:53 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> 1.1.1

### What browser(s) is this bug affecting?

> Chrome 74

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> Go to https://material-components.github.io/material-components-web-catalog/#/component/list hover over list with trailing checkbox to see black background.

### What is the expected behavior?

> It should give a transparent like black to show hover.

### What is the actual behavior?

> It is showing black background without any transparency

### Any other information you believe would be useful?
> visit https://photos.app.goo.gl/mWKLkSaAHM8DC1Xc7 for the problem video (sorry for the wobbliness of the video.

**Comment by Jelmer7** [comment] 2019-04-28 14:14
Duplicate of #4629

**Comment by moog16** [comment] 2019-04-29 17:46
Thanks for opening issue, but this is a dupe of #4629. Closing...

**Closed by moog16** 2019-04-29 17:46 UTC
