### ISSUE TITLE
Outlined icon shows normal icon with long margin to the right

### ISSUE THREAD

**Issue by yandiro** [material-components/material-components-web#3389] opened 2018-08-21 01:16 UTC
### What browser(s) is this bug affecting?

(Happens on all of them)
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Safari Version 11.1.2 (13605.3.8)
Brave 0.23.79

### What OS are you using?

macOS High Sierra 10.13.6 (17G65)

### What are the steps to reproduce the bug?

Open the .html file on any browser. Makes no difference weather I am using local server or not.

### What is the expected behavior?

Show the Outlined icon

### What is the actual behavior?

Shows the normal icon with a long margin to the right

### Any other information you believe would be useful?

Importing the css:
    `<link href="https://fonts.googleapis.com/icon?family=Material+Icons&style=outlined" rel="stylesheet">`

Showing the actual icon:
```
<button type="submit">
  <i class="material-icons">
    send_outline
  </i>
  Enviar
</button>
```

<img width="1267" alt="screen shot 2018-08-20 at 22 02 23" src="https://user-images.githubusercontent.com/27643901/44374713-1950b680-a4c6-11e8-9e4a-aca297f28b85.png">

**Comment by williamernest** [comment] 2018-08-21 15:55
@yandiro Can you reproduce this using a [codepen](https://codepen.io/williamernest/pen/deyxyp)?

**Comment by yandiro** [comment] 2018-08-21 19:54
Yes, I could.

Please check out the button in the pic bellow:

<img width="1280" alt="screen shot 2018-08-21 at 16 51 58" src="https://user-images.githubusercontent.com/27643901/44425575-9df11280-a562-11e8-8728-3e1e5367fe36.png">

**Comment by williamernest** [comment] 2018-08-21 20:40
@yandiro Thanks. It looks like you're markup is a little off from our normal button. For your example, it should look something like 
```html
<button id="my-button" class="mdc-button mdc-button--outlined" type="submit">
  <i class="mdc-button__icon material-icons">send_outline</i>
  Enviar
</button>
```

You can also instantiate the ripple on the button: 
```js 
MDCRipple.attachTo(document.getElementById('my-button'));
```

Here's an example in a [codepen](https://codepen.io/williamernest/pen/mGywNM).

**Comment by yandiro** [comment] 2018-08-21 21:18
Thanks, @williamernest!

It does not have the margin anymore, but the icon is still not outlined. It's the normal icon.

It is weird because on another computer in the classroom (yeah) it worked fine simply using the code I pasted.

<img width="1279" alt="screen shot 2018-08-21 at 18 11 33" src="https://user-images.githubusercontent.com/27643901/44429386-aef35100-a56d-11e8-953e-55f8a22d6786.png">

The outlined icon should be this:
<img width="1279" alt="screen shot 2018-08-21 at 18 12 10" src="https://user-images.githubusercontent.com/27643901/44429411-bfa3c700-a56d-11e8-9c8c-4b3d1eea37f7.png">

**Comment by TangSteven** [comment] 2018-08-22 03:17
Styled icons (outlined, etc) are unfortunately and disappointingly still not implemented in the Google web font. There's [an issue](https://github.com/google/material-design-icons/issues/773) in the material design icons repository with a variety of non-official solutions. Alternatively, you could download the outlined icon as an SVG and use that instead.

**Comment by yandiro** [comment] 2018-08-22 03:29
Thanks a lot

**Comment by kfranqueiro** [comment] 2018-08-23 19:40
Closing since this is an icons issue which is separate from MDC Web. The icons team has definitely heard feedback that updating the icon font is under high demand; I'll let them know about this latest instance :)

**Closed by kfranqueiro** 2018-08-23 19:40 UTC
