### ISSUE TITLE
Update the README for the switch package

### ISSUE THREAD

**Issue by Ralimist** [material-components/material-components-web#999] opened 2017-07-21 23:10 UTC
The Modifier mdc-switch--disabled specified at the end of the README doesn't do anything. I looked trough the sass file and there is no mention of any class called mdc-switch--disabled.

**Comment by Teoxoy** [comment] 2017-07-21 23:39
The class mdc-switch-label on the label doesn't do anything either

**Comment by amsheehan** [comment] 2017-07-26 16:39
You are correct. Looks like an incomplete implementation to me. The label definitely _should_ do something when a `switch` is disabled. I checked with design and they recommend using `Body1` as the label font, and setting the label on disabled selection components to .38 opacity. 

[The typography spec](https://material.io/guidelines/style/typography.html#typography-styles)

I'm wondering if you'd like to submit a pull request to fix this oversight. Changes would be:

- [ ] Add `@include mdc-typography(body1)` and `opacity: .38` to any `mdc-switch-label` that is a descendent of `mdc-switch--disabled`
- [ ] Add the same to `mdc-checkbox`
- [ ] Add the same to `mdc-radio`

If you have questions about specific implementations for the other components feel free to ask. If you don't have the cycles let us know. Thanks!

**Comment by Teoxoy** [comment] 2017-07-26 23:32
Ok so, regarding the checkbox and the radio, they don't have classes for labels (something like mdc-checkbox-label) and I was wondering if it would be better to remove the mdc-switch-label class for simplicity and consistency rather than adding the 2 extra classes for the labels.
And one more thing: the label doesn't have any margin/padding, is it up to the devs using the library to set that or should a default styling exist ?

**Comment by Teoxoy** [comment] 2017-08-01 10:13
Sooo ?

**Comment by dessant** [comment] 2017-08-03 19:07
The label could be handled by form-field, just like for checkbox and radio.

https://material.io/components/web/catalog/input-controls/form-fields/

**Comment by Teoxoy** [comment] 2017-08-03 19:29
@dessant the sass file for the form-field package doesn't contain any label styling besides rtl/dark-theme,
the issue is that a label styling is mentioned in the README file of the switch package and it's not implemented. And then it was also suggested to style the labels of the checkbox and radio packages (maybe other input packages too)

**Comment by lynnjepsen** [comment] 2017-08-07 19:10
@Teoxoy I kinda like the idea of having the same class for labels on checkbox, radio, and switch...but we need to check with designers to see if these three components are similar enough. I don't want to couple code together and end up overriding all the time. But my guess is that since all three are [Selection Controls](https://material.io/guidelines/components/selection-controls.html), they might be similar enough.

**Comment by lynnjepsen** [comment] 2017-12-19 23:59
I'm going to split this into two issues
1) update documentation about disabled switches, because mdc-switch--disabled is not correct
2) add a demo of mdc-form-field working in concert with mdc-switch (just like we do for mdc-checkbox demo and mdc-radio)
https://github.com/material-components/material-components-web/blob/master/demos/checkbox.html#L91
https://github.com/material-components/material-components-web/blob/master/demos/radio.html#L75

**Comment by lynnjepsen** [comment] 2017-12-20 00:01
And now I'm going to close this issue...see #1805 and #1806 if you want to continue the discussion.

**Closed by lynnjepsen** 2017-12-20 00:01 UTC
Labels: needs-design-guidance
