### ISSUE TITLE
mdc-select won't update label when it has an selected item

### ISSUE THREAD

**Issue by KayvandenHeuvel** [material-components/material-components-web#2209] opened 2018-02-07 10:15 UTC
### What MDC Web Version are you using?

v0.30.0

### What browser(s) is this bug affecting?

Tested in Chrome, Firefox & Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Go to the following pen:
https://codepen.io/anon/pen/oexMQw

We've set an initial selected item, but the label won't update. 

EDIT:
We also tested it with an option to reset the mdc-select. According to the package description we should do the following: 

> The index of the currently selected option. Set to -1 if no option is currently selected. Changing this property will update the select element.

To reproduce this bug we created the following pen:
https://codepen.io/anon/pen/ZrBOYE

### What is the expected behavior?

We expected the label would float above the selected text

### What is the actual behavior?

It doesn't float

### Any other information you believe would be useful?
/

**Comment by kfranqueiro** [comment] 2018-02-09 18:06
I believe this is a duplicate of #1810, which was recently fixed with #2125 and will be in the next release.

**Closed by kfranqueiro** 2018-02-09 18:06 UTC
