### ISSUE TITLE
RFC: Drawers to open with slide gesture

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#882] opened 2017-06-30 12:58 UTC
## Feature Requests
Not sure if this is already in discussion but `temporary-drawer` has implementation to close it with a swipe gesture, however it cannot be opened with the same. 
I tried searching the spec for anything related to gestures with drawers but couldn't find it here
https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-content

All the native material apps appears to have this functionality(say GMail for example), also boilerplate app from `polymer-cli` has the capability to open the `temporary-drawer` using a swipe from the left corner. And the same is implemented at multiple PWAs check https://flipkart.com, https://wego.com on your phone to experience the same.

Implementing the same in `mdc-web` will improve the UX for a ton of sites that use `mdc-web`.

**Comment by amsheehan** [comment] 2017-06-30 15:48
I hear what you’re saying, but we have chosen not to implement this feature and most other horizontal swiping features (scrollable tabs for instance).

This is because swiping from the edge in mobile safari triggers back navigation, and MDC Web is aiming to stay out of the way of browser features like that. 

If you would like to extend the capabilities of the drawer on an implementation level, you are more than welcome to do so, but we will not be adding this behavior to MDC Web.

**Comment by prateekbh** [comment] 2017-06-30 16:01
Sure I definitely understand the concern here, but can we not make this more like an opt-in?
May be surround this with better messaging or not do it on safari at all(i know UA parsing sucks, but may be something else)?
We're wide eyed leaving a gap open for what can be a delightful user experience and is a very base expectation from mobile application UX.

**Comment by piotr-cz** [comment] 2017-07-09 02:51
This an is how I implemented such feature in reactjs.
Doesn't look as good as closing the drawer when it's position mimics touch position

```js
  constructor() {
    this.touchStartLeftSide = false
  }

  componentDidMount() {
    window.document.addEventListener('touchstart', this.handleTouchStart, false)
    window.document.addEventListener('touchend', this.handleTouchEnd, false)
    window.document.addEventListener('touchmove', this.handleTouchMove, false)
  }

  handleTouchStart(event) {
    this.touchStartLeftSide = (event.changedTouches[0].screenX === 0)
  }

  handleTouchEnd(event) {
    this.touchStartLeftSide = false
  }

  handleTouchMove(event) {
    // Trigger drawer open when swiping over 25% of drawer width
    if (this.touchStartLeftSide && event.changedTouches[0].screenX > 280 * 0.25) {
      this.props.onDrawerOpen()
    }
  }
```

**Comment by touficbatache** [comment] 2017-07-11 17:39
@amsheehan I think this is a pretty good feature https://twitter.com/materialdesign/status/884828964023263232

**Comment by prateekbh** [comment] 2017-07-11 17:44
![pretty please](https://user-images.githubusercontent.com/5960497/28081921-88a2c6b2-668e-11e7-8b20-ce581bb15fcb.gif)

Yeah, we can give really great UX for the browsers that support this. Open to discussion to figure out a better approach though. And super happy to start a PR if you allow me to do that

**Comment by touficbatache** [comment] 2017-07-11 17:49
The problem is that some browsers have "swipe from left" do something _natively_ and MDC Drawer would break that. Safari does that apparently so it could be disabled there. I'll leave that to @amsheehan to decide if he want to re-open this issue and discuss about it...

**Comment by prateekbh** [comment] 2017-07-11 17:53
I agree, hence I said we can discuss some approach to fix this may be...

**Comment by amsheehan** [comment] 2017-07-11 18:00
@prateekbh making it hard to say no with the gifs 😅

I'll bring it up with the team. I'm still leaning toward not implementing something like this, but maybe having a demo of the functionality for people who wish to do so on their own.

**Comment by prateekbh** [comment] 2017-07-11 18:32
😆 😆 😆 😆 

Just trying my best to get more awesomeness in. I am all in for a cleaner approach that shouldn't break anyone, but I am also advocating that this is a huge UX gain.

Also, just a thought from the top of my head, can we implement this as a modifier with clear bold callout that this wont work on ios?

**Comment by Garbee** [comment] 2017-07-11 18:41
IMO a swipe gesture that is implemented for all browsers save one creates an *inconsistency* with the offering. That's certainly not something we'd want. Further other browsers in the future may include gestures as well, so then do we disable as that happens or let things conflict?

It's best that if developers want this, they implement on their own within their apps. That way they are taking the responsibility of making sure it is known where it is usable and where it isn't. Also, the library then isn't left maintaining that when it may not get used by many developers.

Simply because something *can* be done doesn't mean it *should* be done.  There are a lot of little bits that *can* be done but they aren't feasible long-term to include and maintain internally.

Notice how on the tweet it said *on Android* as in Android apps. Not anything built to work on Android including web apps or desktop apps. It's a hard thing to balance providing native-like experiences from the web. While it is important, some things no matter how you tell people will cause confusion and resentment. It's best that be avoided and put the onus on developers building their apps to create explicitly inconsistent experiences. At least then they understand why instead of saying it is a problem with the library.

**Comment by prateekbh** [comment] 2017-07-12 02:48
>Further other browsers in the future may include gestures as well, so then do we disable as that happens or let things conflict?

Mostly thats the reason I suggested it as an _opt-in_ with the help of modifiers. Not sure but since there is no spec around it, I don't see this(swipe to go back) becoming a widely used pattern.

>It's best that if developers want this, they implement on their own within their apps. That way they are taking the responsibility of making sure it is known where it is usable and where it isn't.

Makes sense, but much like everything in the repo I am guessing the aim of the repo is to make dev's lives easier and provide standard ways of doing things.

>Simply because something can be done doesn't mean it should be done. There are a lot of little bits that can be done but they aren't feasible long-term to include and maintain internally.

+1

>Notice how on the tweet it said on Android as in Android apps.

As of today implementing this on android browsers will also be a huge gain, not just the native apps.


P.S. Sorry if I sound pushy, just putting my thoughts here and trying to see if we can make this better somehow

**Comment by piotr-cz** [comment] 2017-07-12 08:27
Important question is whether such implementation:

a) would break native browser behavior
b) browser would not fire touch move events and just native behavior
c) browser would trigger it's native behavior and touch move events at the same time

I can't check on Safari, somebody would have to try with code from [my previous comment](https://github.com/material-components/material-components-web/issues/882#issuecomment-313894124).

If a) or c) is true, this feature should probably not be implemented because AFAIK there is no way to prevent breaking UX

if b) is true, then IMO we should look at this feature from the point of progressive enhancement (this is a web package after all)

I'm using this package in progressive web app so maybe another option is to allow swipe-left event listeners only in standalone mode as logic says that most browser UI is disabled there.

**Comment by prateekbh** [comment] 2017-07-12 08:49
c) is true,  similar functionality already exist on https://webpack.js.org

**Comment by piotr-cz** [comment] 2017-07-12 09:07
I don't think there is a way to check if browser triggers native behavior for swipe-left gesture.
We could blacklist Safari, but as @Garbee said other browsers or browser extensions may implement same gestures

Last left option is to sniff for standalone or WebView mode

**Comment by Garbee** [comment] 2017-07-12 12:45
> I am guessing the aim of the repo is to make dev's lives easier and provide standard ways of doing things.

The goal of the project is to provide Material Design components with reference implementations for the web. It won't cover every pattern or use case defined. It is a very targeted goal to help ease developers needs. Developers shouldn't be absolved of doing work because they use the library.

**Comment by lynnjepsen** [comment] 2017-07-13 18:44
> The problem is that some browsers have "swipe from left" do something natively and MDC Drawer would break that

This is why we will not bake "swipe from left" logic into the MDC Drawer component.

> The goal of the project is to provide Material Design components with reference implementations for the web

@prateekbh you're more than welcome to submit a PR that creates a reference implementation of "swipe from left" in our **demo** code, but please do not implement this **within** MDC Drawer.

**Closed by lynnjepsen** 2017-07-13 18:44 UTC
Labels: Discussion
