### ISSUE TITLE
[TopAppBarNavigationIcon] Icon is not unselected in Chrome

### ISSUE THREAD

**Issue by maracuja-juice** [material-components/material-components-web#4731] opened 2019-05-17 16:37 UTC
## Bug report
The navigation icon is not unselected when clicking twice on it.
This only happens in Chrome. Couldn't reproduce in Firefox and Safari.

### Steps to reproduce
1. Go to https://codepen.io/maracuja-juice/pen/byRwPW
2. Click on the menu button
3. Click on the menu button again

### Actual behavior
The button is in a clicked state.

### Expected behavior
The button isn't in a clicked state.

### Screenshots
![image](https://user-images.githubusercontent.com/16801528/57942627-435acc00-78d2-11e9-8092-282f47dc84d2.jpeg)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | latest as of right now
| Browser          | Chrome 74.0.3729.157
| Operating System | macOS Mojave

### Possible solution
This probably happens because the `mdc-ripple-upgraded--background-focused` class is not correctly removed.

**Comment by williamernest** [comment] 2019-05-17 16:39
The icon retains focus when the element is clicked to close the menu. Since the icon is focused, the focused class remains on the element. This is working as intended.

**Comment by maracuja-juice** [comment] 2019-05-17 16:40
1: Can you explain why this behaviour is only in Chrome though?
2: Why is there not the same behaviour when using a different tag if this is intended?
3: How can I make it to behave like I want?

**Comment by williamernest** [comment] 2019-05-17 16:42
If the button is not retaining focus (and the subsequent class) in other browsers I would call that a bug. What other tag have you attempted to use for the navigate menu icon ?

**Comment by maracuja-juice** [comment] 2019-05-17 16:45
I updated the comment. 
I don't exactly understand why it does not retain focus on the first click but on the second click it does.

**Comment by williamernest** [comment] 2019-05-17 16:46
You shouldn't use an `a` tag to open a menu, since anchor tags are used for navigation. The first time you clicked the button, the menu gains focus. When clicking the icon a second time the menu is closed, causing the button to regain focus.

**Comment by maracuja-juice** [comment] 2019-05-17 16:48
Yes of course not, I'm aware of that.
So if this intended by MWC (reasoning not 100% clear to me yet but okay, that's fine for me): What is the correct way for me to fix this then? I don't want the button to regain focus because the menu is closed. It doesn't make sense in my opinion for the user to have the button in focus again when he closes the menu. (This is the same for Drawers for example aswell, which is what I'm actually working with)

**Comment by williamernest** [comment] 2019-05-17 17:01
You could listen to the menu closed event and set the focus on the body (which is what safari does). A timeout could also work. 

The native behavior of a button (on some browsers such as Chrome and Firefox) is to retain focus when clicked. We don't explicitly set focus on any element when the menu is closed. That's the behavior that occurs when you click a button and we defer to whatever the browser default behavior is.

**Comment by maracuja-juice** [comment] 2019-05-17 17:02
Okay, I will try that out. Maybe a hint in the docs somewhere would be good?
Otherwise I think we can close this.

**Comment by moog16** [comment] 2019-05-20 18:15
This is a native behavior that doesn't need to be documented. Thanks for opening. Closing :)

**Closed by moog16** 2019-05-20 18:15 UTC
Labels: bug
