### ISSUE TITLE
Exports broken for chips, drawer and textfield

### ISSUE THREAD

**Issue by thdk** [material-components/material-components-web#4135] opened 2018-12-02 09:16 UTC
Using the 0.41.0 version of the following packages:

- @material/chips
- @material/drawer
- @material/textfield
- ...

Gives the following errors when bundling: 
Error: 'MDCChipSet' is not exported by node_modules\@material\chips\dist\mdc.chips.js
Error: 'MDCDrawer' is not exported by node_modules\@material\drawer\dist\mdc.drawer.js
Error: 'MDCTextField' is not exported by node_modules\@material\textfield\dist\mdc.textfield.js

Downgrading to "0.40.1" is a temporary workaround.

### What MDC Web Version are you using?
0.41.0

### What is the expected behavior?
packages should export: MDCChipSet, MDCDrawer, MDCTextField

### What is the actual behavior?
Build fails because of the missing exports

### Any other information you believe would be useful?
There is already an issue for MDCSelect #4129 which I believe was facing the same problems as the packages listed above.

**Comment by kfranqueiro** [comment] 2018-12-03 15:47
#4129 was caused by missing exports in `mdc-select/index.js`. However, all of the exports mentioned in this issue are present, and I'm unable to reproduce this issue.

I tested this JS, using the webpack config from our [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-3-webpack-with-es2015):

```js
import {MDCChip, MDCChipSet} from '@material/chips';
import {MDCDrawer} from '@material/drawer';
import {MDCTextField} from '@material/textfield';

console.log(MDCChip);
console.log(MDCChipSet);
console.log(MDCDrawer);
console.log(MDCTextField);
```

MDC Web packages listed in output of `npm ls --depth 0`:

```
├── @material/chips@0.41.0
├── @material/drawer@0.41.1
├── @material/textfield@0.41.0
```

Can you provide a gist or repository that reproduces this issue?

**Comment by williamernest** [comment] 2018-12-07 00:51
You can resolve this issue by either adding `/index` to each of your import statements (recommended) or changing your imports to `* as MDCCheckbox`. 

We could resolve this by adding `"module": "index.js"` to our package.json file so that rollup correctly resolves to the ES6 file, but IIRC we had a reason to not add that when we last updated our `"main"`.

**Comment by thdk** [comment] 2018-12-07 07:54
Thanks, that allowed me to upgrade indeed.

I used your first recommendation and added /index to each of my imports.

Is it likely that it will stay like this? Or do you think i can remove this suffix from my imports with later versions?

**Comment by kfranqueiro** [comment] 2018-12-07 15:30
If your goal is to consume our modules in ES2015+ format, you should specifically reference `index.js`. We have a note about this in our [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-4-include-javascript-for-a-component).

RE Will's comment, the reason for not specifying `module` was because even according to [rollup's own docs](https://github.com/rollup/rollup/wiki/pkg.module), `module` is intended to point to something that is purely an ES2015 module with no other transforms necessary, which isn't completely true of our code (we also use babel's `transform-object-assign` plugin becuase IE11 doesn't support `Object.assign`).

**Comment by williamernest** [comment] 2018-12-10 21:57
Closing this issue since the exports are working as intended.

**Closed by williamernest** 2018-12-10 21:57 UTC
