### ISSUE TITLE
[MDCTextField] Outlined Text Field doesn't reset the label position when form is reset using button

### ISSUE THREAD

**Issue by Hrishikesh-K** [material-components/material-components-web#6491] opened 2020-09-19 13:29 UTC
## Bug report
MDCTextField (Outlined) doesn't reset the label position back to the center of the text field when a form is reset using a button. In normal cases, the label is first positioned in the (vertical) center of the text field. When a user clicks on the text field, the label animates to the top left of the field and when the user clicks out of the field while leaving it empty, the label resets to the original position. All that's working fine. However, if a form is reset using `<button type = "reset">`, the data of the form is removed, but, the labels stay in the top-left position until the user clicks in it first and then clicks outside again.

### Steps to reproduce
1. Go to: https://hrishikeshk.netlify.app/contact
1. Fill the form with random information and click on 'Reset'.
1. Notice that the labels don't reset to their position.

### Actual behavior
The labels stay in the top-left corner of the text field just like when they're filled with text (or being typed into).

### Expected behavior
The labels should reset to original position.

### Screenshots
Filled state (all good):

![image](https://user-images.githubusercontent.com/11403551/93668317-49098880-faa9-11ea-8af4-fe39a4e34d54.png)

After clicking 'Reset':

![image](https://user-images.githubusercontent.com/11403551/93668370-75bda000-faa9-11ea-8afa-18568a4a2133.png)

It should reset to this:

![image](https://user-images.githubusercontent.com/11403551/93668389-9554c880-faa9-11ea-8580-0e00f8e58d99.png)

### Your Environment:
|Software        |Version(s)                         |
|----------------|-----------------------------------|
|MDC Web         |7.0.0                              |
|Browser         |Chrome Windows 64-bit 85.0.4183.102|
|Operating System|Windows 10 64-bit 19041.508        |

**Comment by abhiomkar** [comment] 2020-09-21 17:56
Thanks @Hrishikesh-K for reporting this issue!

Since form reset action does not trigger native events (including `change` & `input`) on `<input>` element text field's floating label does not respond. Text field does not know if the form is been reset. This is intended behaviour.

You'll have to reset the floating label positions manually (using text field's `.floatLabel()` API) on form reset action.

I'm closing this since working as intended. Feel free to re-open if you see an issue with the MDC component.

Please let me know if you've any questions!

**Closed by abhiomkar** 2020-09-21 17:56 UTC
Labels: bug
