### ISSUE TITLE
Dragging the value on a slider changes values on other sliders

### ISSUE THREAD

**Issue by PolygeneLubricants** [material-components/material-components-web#1428] opened 2017-10-16 11:36 UTC
This issue has been discovered in Chrome, Version 61.0.3163.100 (Official Build) (64-bit).
When dragging the sliders on a page with multiple sliders in mobile or responsive mode (Chrome), all other previously touched sliders change value as well.
Steps to reproduce:
1. Open Chrome with debugger mode, toggle Device Toolbar and set to Responsive, width 600px
2. Access https://material-components-web.appspot.com/slider.html
3. Drag slider 1 to 70.
4. Drag slider 1 to 10.
5. Drag slider 2 to 70.

Slider 1 has now changed value to 33.

**Comment by kfranqueiro** [comment] 2017-10-16 18:46
I believe this is a duplicate of #1192. It's not specific to dragging other sliders; it's specific to dragging a slider, then dragging anywhere else on the page with touch input.

**Closed by kfranqueiro** 2017-10-16 18:46 UTC
