### ISSUE TITLE
Anchor MDCMenu from any corner of surface

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4252] opened 2019-01-16 11:51 UTC
I think that the menu should not open over a button if a button has activated it.
Currently when a menu is opened, it opens over the button that is used to trigger it.

![example](https://user-images.githubusercontent.com/26075792/51247147-1d3f2100-19f1-11e9-98ac-f2731cd40d58.gif)

I think that it should appear under the button like this:
![classroom](https://user-images.githubusercontent.com/26075792/51247102-fe408f00-19f0-11e9-8d35-75bea87aa90e.gif)

Plus the current menu doesn't seem to stick to the rules of the layout grid and just overlays outside of the grid.
<img width="344" alt="screen shot 2019-01-17 at 12 42 23 am" src="https://user-images.githubusercontent.com/26075792/51247183-39db5900-19f1-11e9-9ca1-6d0681313851.png">

I guess the grid should act like the edge of the screen and make the menu open inwards if it is on the edge of a grid.

**Comment by acdvorak** [comment] 2019-01-17 20:28
We try to keep our components as independent from each other as possible, so the Menu intentionally does not consider Grid boundaries when positioning; that's working as intended. If you want to implement such functionality, you can position it manually with `setAbsolutePosition()`.

I don't think we currently support anchoring the _right_ side of the menu surface to a specific point.  @williamernest or @kfranqueiro can correct me if I'm wrong.

Menu anchors appear to be relative to the menu surface's top-_left_ corner, and I don't see any way to override that. AFAIK, the closest you can get is:

```js
menu.setAnchorCorner(mdc.menuSurface.Corner.BOTTOM_START);
```

https://codepen.io/acdvorak/pen/EGzGLN?editors=1010

If the button is on the far right of the screen, it will look _almost_ right, but not quite:

![image](https://user-images.githubusercontent.com/409245/51346738-3a0c4080-1a53-11e9-937b-abeb73f58bb8.png)

However, if the button is in the middle of the screen, you can clearly see that it's left-aligned:

![image](https://user-images.githubusercontent.com/409245/51346722-32e53280-1a53-11e9-9fc0-f45532450051.png)

Unless I'm missing something, this might be a good feature request for Menu Surface: Supporting anchor points on both the surface _and_ the target (button).

**Comment by williamernest** [comment] 2019-01-17 20:39
We initially had this scoped in but ended up not implementing it at the time since it wasn't a specifically requested feature and we wanted to narrow our scope for the deliverable.

**Comment by CyborgSemon** [comment] 2019-01-17 20:49
Should i make a new issue requesting the left side, right side feature? Or can the feature request tag just be added to this one with a title change?

**Comment by acdvorak** [comment] 2019-01-17 21:34
Thanks for the history, Will!

We can repurpose this issue as a FR. Thanks @CyborgSemon!

**Comment by CyborgSemon** [comment] 2019-01-17 21:38
No problem :)

**Comment by abhiomkar** [comment] 2019-06-09 19:49
Closing this as duplicate of #4775 (menu alignment)

Please feel free to re-open if it is not related.

**Closed by abhiomkar** 2019-06-09 19:49 UTC
Labels: backlog, feature-request
