### ISSUE TITLE
Tabs: Does not match spec: (1) Letter-spacing (2) Icon-and-text version's spacing/sizing

### ISSUE THREAD

**Issue by jasonkylefrank** [material-components/material-components-web#2855] opened 2018-05-31 23:56 UTC
### What MDC Web Version are you using?

I believe its **v0.35.2**
The CodePen template is pulling the "latest", from [here](https://unpkg.com/material-components-web@latest/dist/material-components-web.js), and that says 0.35.2 in the URL.   

<small>
Side question from a newbie: The CodePen is setup to pull the "latest", but I see that the repo has newer stuff than v0.35.2, in particular the master branch has newer commits and tag v0.36.0-0 also has newer commits.  Why doesn't "latest" use one of those?
</small>

### What browser(s) is this bug affecting?

Version 66.0.3359.181 (Official Build) (64-bit).

navigator.userAgent:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"

### What OS are you using?

macOS High Sierra.  Version 10.13.4.

### What are the steps to reproduce the bug?

**Letter-spacing problem:**
1. Load [this CodePen](https://codepen.io/jasonkylefrank/pen/xzGYyB), which was started from your template.
2. Observe the letter-spacing (does not match the current guidelines)
3. Copy one of the example images from the guidelines and paste into a design tool such as Sketch.  Then spec-out the text to observe the differing letter-spacing (called "character-spacing" in Sketch).
Note that the difference is significant enough that I noticed it visually right away without needing to actually perform these steps.

Screenshots and suggested fix to follow (or I can do a PR).

**Icon-and-text version's spacing/sizing problem**:
1. Load [this CodePen](https://codepen.io/jasonkylefrank/pen/xzGYyB), which was started from your template.
2. Observe the 83px height of the tabs.  Also observe the icon's incorrect positioning relative to the top of the tabs and the text.  These do not match the latest guidelines.

Screenshots and suggested fix to follow (or I can do a PR).

### What is the expected behavior?

**Letter-spacing problem:**  It should match the guidelines.

**Icon-and-text version's spacing/sizing problem**:  It should match the guidelines.

### What is the actual behavior?
**Letter-spacing problem:**  The tabs are using a letter-spacing that the latest *button* guidance shows, but not what the latest *tab* guidance shows.

**Icon-and-text version's spacing/sizing problem**:   The tabs use an incorrect height of 83px and position the icon incorrectly, according to what the latest guidelines show.

### Any other information you believe would be useful?
I'll post several screenshots which should illustrate the issues, but let me try to cut-to-chase before I burden you with those.  Here are possible fixes for these 2 issues (I can do a PR if that's helpful):

**Letter-spacing problem:**  According to my tests in Sketch, the latest guidelines are using a letter-spacing of about 0.8px. 

**Icon-and-text version's spacing/sizing problem**:   See my CodePen for a possible fix: Remove the line-height from the `.mdc-tab` anchor element.  That seems to get it almost perfect.

#### Background:
I first noticed the issues when I was viewing the icon-and-text tabs in the RMWC [demo page](https://jamesmfriedman.github.io/rmwc/tabs).  Hover one of the icon-and-text tabs and you'll see the icon-positioning problem.  While I realize that library is not the exact same as MDC by itself, I think it mostly just wraps the MDC components, so it got me digging.  

Next I'll show 2 ways that I dug into the problem: (1) Hacking in the MDC Tab demo page, and (2) The linked CodePen.  I'll now show details from both ways.

First, I used the [MDC tabs demo page](https://material-components.github.io/material-components-web-catalog/#/component/tabs).  But since that page currently does not show an example of the icon-and-text version, I just copied the HTML from the [docs page](https://material.io/develop/web/components/tabs/) into the demo page.  I realize this doesn't give the JS a chance to properly initialize the component (thus no "current underline", etc.), but my CodePen corroborates the issue, so hang with me.

![image](https://user-images.githubusercontent.com/7502365/40813468-0e65d75c-6509-11e8-8b99-32105555c036.png)

Just visually observing the MDC implementation revealed the 2 issues.  But here is the MDC next to the guidelines:

![image](https://user-images.githubusercontent.com/7502365/40813558-7dd70bc4-6509-11e8-8275-491ffdd3ec32.png)

Next, I inspected element to find that the MDC letter-spacing is at 1.25px.  Incidentally, that seems to be what the new MDC button is using for its letter-spacing, and that actually does about match the button guidelines.  But the *tab* guidelines do not use 1.25px for their letter-spacing.

![image](https://user-images.githubusercontent.com/7502365/40813606-c2b5f124-6509-11e8-960a-8dd915c53bb9.png)

Here is a Sketch file that I used to spec-out an image that the guidelines use for the tabs.  It shows that the guidelines use a letter-spacing of about 0.8px:

![image](https://user-images.githubusercontent.com/7502365/40813658-ff2a9f92-6509-11e8-9f49-68ae31438980.png)

**Next I'll show my investigation into the icon-and-text version's spacing/sizing problem.**

Here are some screenshots showing that the guidelines show that there should be 12px of space above the icon's 24px box.  But the MDC component only has 4px of space above it:

![image](https://user-images.githubusercontent.com/7502365/40813682-28a139bc-650a-11e8-9d37-4ec8422de88a.png)

![image](https://user-images.githubusercontent.com/7502365/40813740-6bc8697c-650a-11e8-827c-0b6d354569e0.png)

**I will now transition to showing my [CodePen](https://codepen.io/jasonkylefrank/pen/xzGYyB) to further corroborate the sizing/spacing issue, as well as a possible fix.**

Note that my CodePen give instructions about the fix, but I'll include them here as well.  

First, notice that when the tabs load, they have a height of 83px:

![image](https://user-images.githubusercontent.com/7502365/40813810-b864cafa-650a-11e8-8078-001753265eca.png)

Next, notice that the `.mdc-tab` element has a `line-height` set:

![image](https://user-images.githubusercontent.com/7502365/40813836-e26c6e8e-650a-11e8-8d46-c0352b035431.png)

Next, if we remove that `line-height`, notice how the size of the tabs goes to a proper 72px:

![image](https://user-images.githubusercontent.com/7502365/40813863-07c19f4c-650b-11e8-932c-d6e8eaed6e89.png)

![image](https://user-images.githubusercontent.com/7502365/40813880-1ded365a-650b-11e8-9b54-3d7a2bd1df9e.png)

And here's a close-up of a Sketch file where I spec'd-out this result.  This shows that with the `line-height` removed, the icon has about 13px of space above it (which is almost the correct 12px of space):

![image](https://user-images.githubusercontent.com/7502365/40813926-4808fa78-650b-11e8-937e-9b8b25eb8898.png)

**Comment by patrickrodee** [comment] 2018-06-04 19:35
Hey Jason, thanks for submitting this issue.

Could you provide which version of the Material Sketch file you're using?

Thanks!

**Comment by kfranqueiro** [comment] 2018-06-04 20:33
Thanks for providing so much detail in this issue!

As a further update, we checked with our designer, who confirmed that some of the information currently reflected in the guidelines is out of date. The design team will work on updating those details.

At the same time, we're currently in the middle of working on new packages to take the place of the current `mdc-tabs`. These new packages include updated styles to reflect the new design guidelines. This work has been occurring on the `feat/tabs/tabs` branch, and should be picking up again soon.

I'm going to close this since work is already underway in both engineering and design to resolve these discrepancies.

**Closed by kfranqueiro** 2018-06-04 20:33 UTC
