### ISSUE TITLE
Using fixed last row with Top App Bar

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#3945] opened 2018-10-19 18:22 UTC
## Feature Requests
Hey,
I'm currently using MDC-Web in my project and came across a small problem. I need to use the [old Toolbar's fixed last row](https://material-components-web.appspot.com/toolbar/waterfall-toolbar-fix-last-row.html) for a feature but I can only find the Top App Bar, which doesn't seem to feature the fixed last row. I'd like to use the new Top App Bar because it's in the new MD Guidelines and it seems like the old Toolbar is deprecated, right? If not, I'm sure it will be soon.
Are there any plans on adding this feature to the Top App Bar component?
Thanks

**Comment by acdvorak** [comment] 2018-10-22 19:21
Nice to see you again @touficbatache 😀 

The "flexible" behavior of the (now deprecated) toolbar component was actually never in the Material Guidelines, which is why it was cut from scope when we created the new Top App Bar component.

However, if this is something you need, please comment on #3041 so we can track potential use cases!

_(Closing this issue as a duplicate of #3041.)_

**Closed by acdvorak** 2018-10-22 19:21 UTC
