### ISSUE TITLE
Elevation not applied to CSS only raised button on mobile safari

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#737] opened 2017-05-26 23:44 UTC
### What MDC-Web Version are you using?

> 0.11.1

### What browser are you using?

> Mobile Safari

### What version of OS are you using?

> iOS 10.2.1

### What are the steps to reproduce the bug?

> 1. Open [button](http://material-components-web.appspot.com/button.html) in catelog on mobile safari
> 2. Scroll to css only button
> 3. Click on `RAISED WITH PRIMARY`, `RAISED WITH ACCENT`, `DIV`

### What is the expected behavior?

> A temporary elevation should be applied to the button

### What is the actual behavior?

> And it is not. Just the focus ring.

**Comment by traviskaufman** [comment] 2017-05-30 15:40
Duplicate of #110

**Closed by traviskaufman** 2017-05-30 15:40 UTC
