### ISSUE TITLE
[Webpack] Invalid CSS after "@include mixins"

### ISSUE THREAD

**Issue by DimaChaichan** [material-components/material-components-web#5502] opened 2020-01-22 16:53 UTC
## Bug report
Hello, 
I try to pack mdc with Webpack and Typscript.

In Version 4.0.0
I get this error: 
```
ERROR in [at-loader] ./node_modules/@material/auto-init/index.d.ts:38:16 
    TS2528: A module cannot have multiple default exports.
```

This is fixed by Version: "^5.0.0-canary.faa9af310.0"
But now I have the error:
```
ERROR in ./src/frontend/sass/main.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
        on line 24 of node_modules/@material/button/mdc-button.scss
```

### Steps to reproduce
1 Create a Example Project like this. 
https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md
2. update mdc: npm i material-components-web@5.0.0-canary.faa9af310.0
3. run npm: npm start

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.0.0-canary.faa9af310.0
| Browser          | chrome
| Operating System | Debian 10

### Possible solution
The only way to fix both problems, go to version 2.3.1.

**Comment by asyncLiz** [comment] 2020-01-22 17:24
This looks like a duplicate of #5158. A fix has been made, but I don't believe it's released yet.

**Comment by asyncLiz** [comment] 2020-01-22 17:25
Edit: Ah never mind, I see your actual problem is with sass!

**Comment by cintaccs** [comment] 2020-01-22 23:46
I have the same problem (with the canary releases over npm and using webpack to generate the updated css) - can't find any examples of how to include the changed / new mixins?

**Comment by DimaChaichan** [comment] 2020-01-23 10:04
I tested now the NPM releases. 
The Problem is in release: 5.0.0-canary.faa9af310.0
Release 5.0.0-canary.a4db5fbad.0 works. 
Looks like this commit make the problem: https://github.com/material-components/material-components-web/commit/faa9af310d1a18ec2c183830c84eb14d0492feab

**Comment by bonniezhou** [comment] 2020-01-24 21:18
Hi, MDC Web is not officially supported on Canary. We recommend using the `@latest` release.

**Closed by bonniezhou** 2020-01-24 21:18 UTC
Labels: bug

**Comment by cintaccs** [comment] 2020-01-24 21:56
... from my part it was not a support request - as I don't expect you to "support". However the feedback that is delivered here could potentially help improve the library and help the community too... @latest is currently 3 months behind (and projects using the mdc libraries are often not able to wait for 3 month for updates and improvements). Using canary at least give some interim fixes as well as avoid having major breaking changes hit you. As @canary releases are available on npm I think it is not unreasonable that some (including myself) have used "the latest" build before asking further questions or requesting new features. But in any case thanks for the feedback.

**Comment by DimaChaichan** [comment] 2020-01-27 10:30
> Hi, MDC Web is not officially supported on Canary. We recommend using the `@latest` release.

Hi bonniezhou,
I try to use the @lastest version.
But I have this problem: 
```
ERROR in [at-loader] ./node_modules/@material/auto-init/index.d.ts:38:16 
    TS2528: A module cannot have multiple default exports.
```
This is fixed in a Canary version. In the Moment I must use the mini.css file. And this make a lot of problems and I can't use the "power" of SCSS. 
I not really understand why the canary visions are on NPM, if this Versions are not ready to use. 
I will wait for the new Version, thanks for your feedback.

**Comment by asyncLiz** [comment] 2020-01-27 17:20
What version of sass are you using? That canary version is using [sass modules](https://sass-lang.com/blog/the-module-system-is-launched), which may be why sass is failing to build.

If you're using an older version, a fix may be to update sass.

**Comment by DimaChaichan** [comment] 2020-01-27 17:41
> What version of sass are you using? That canary version is using [sass modules](https://sass-lang.com/blog/the-module-system-is-launched), which may be why sass is failing to build.
> 
> If you're using an older version, a fix may be to update sass.

Hi AsyncLiz, 
thanks for your message.

I use the Version sass@1.25.1-test.1. 
This is the last version on NPM.

**Comment by abraham** [comment] 2020-02-14 02:02
I was getting

> ERROR in ./src/frontend/sass/main.scss
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
>         on line 24 of node_modules/@material/button/mdc-button.scss

and fixed it by removing `node-sass` and installing `sass@1.25.0`.

**Comment by jamiddd** [comment] 2020-02-14 21:01
> I was getting
> 
> > ERROR in ./src/frontend/sass/main.scss
> > Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> > SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
> > on line 24 of node_modules/@material/button/mdc-button.scss
> 
> and fixed it by removing `node-sass` and installing `sass@1.25.0`.

It worked .. Thanks

**Comment by m-alzam** [comment] 2020-02-15 16:46
Hi @abraham 
> and fixed it by removing `node-sass` and installing `sass@1.25.0`.

I get this error

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Two forwarded modules both define a variable named $mdc-feature-mdc-feature-all-features.
  ╷
2 │ @forward "@material/feature-targeting/variables" as mdc-feature-*;
  │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @forward
3 │ @forward "@material/feature-targeting/mixins" as mdc-feature-*;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @forward
  ╵
  node_modules/@material/card/mdc-card.import.scss 3:1  @import
```

**Comment by KolCrooks** [comment] 2020-02-16 19:00
@m-alzam same

**Comment by sitterrus** [comment] 2020-02-18 14:43
> @m-alzam same



> Hi @abraham
> 
> > and fixed it by removing `node-sass` and installing `sass@1.25.0`.
> 
> I get this error
> 
> ```
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Two forwarded modules both define a variable named $mdc-feature-mdc-feature-all-features.
>   ╷
> 2 │ @forward "@material/feature-targeting/variables" as mdc-feature-*;
>   │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @forward
> 3 │ @forward "@material/feature-targeting/mixins" as mdc-feature-*;
>   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @forward
>   ╵
>   node_modules/@material/card/mdc-card.import.scss 3:1  @import
> ```

here is temporary solution: https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020

**Comment by jkaan** [comment] 2020-02-18 21:14
I indeed have the same error and when I add the workaround it complains that it cannot find the stylesheet.

**Comment by abhiomkar** [comment] 2020-02-19 01:38
I created [full working example](https://github.com/abhiomkar/mdc-web-getting-started) with some of the popular bundlers: Webpack, Rollup & Snowpack.

**Comment by sitterrus** [comment] 2020-02-19 10:50
> I indeed have the same error and when I add the workaround it complains that it cannot find the stylesheet.

if you see the following
![image](https://user-images.githubusercontent.com/40627292/74827498-d9ae9900-530d-11ea-966e-9cf0f9f87b9d.png)
it means that the package is not installed

**Comment by wazest** [comment] 2020-02-25 10:45
> I was getting
> 
> > ERROR in ./src/frontend/sass/main.scss
> > Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> > SassError: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
> > on line 24 of node_modules/@material/button/mdc-button.scss
> 
> and fixed it by removing `node-sass` and installing `sass@1.25.0`.

Hi @abraham 

I get the same Error ... 

ERROR in Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@forward "@material/animation/variables" as mdc-animation-*;
^
      @forward is coming soon, but it's not supported in this version of Dart Sass.
  ╷
1 │ @forward "@material/animation/variables" as mdc-animation-*;



Any solution?

**Comment by asyncLiz** [comment] 2020-02-25 17:23
CSS modules require `sass@^1.23.0`. Make sure you're on that version or later to use them.

If you're using `sass-loader` it will automatically use `sass`, but you'll need to make sure any traces of `node-sass` have been fully removed from the project.

If you're continuing to have problems, create a reproduction repository with your package.json and package-lock.json.

**Comment by monkeythedev** [comment] 2020-08-30 08:52
> > @m-alzam same
> 
> > Hi @abraham
> > > and fixed it by removing `node-sass` and installing `sass@1.25.0`.
> > 
> > 
> > I get this error
> > ```
> > Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> > SassError: Two forwarded modules both define a variable named $mdc-feature-mdc-feature-all-features.
> >   ╷
> > 2 │ @forward "@material/feature-targeting/variables" as mdc-feature-*;
> >   │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @forward
> > 3 │ @forward "@material/feature-targeting/mixins" as mdc-feature-*;
> >   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @forward
> >   ╵
> >   node_modules/@material/card/mdc-card.import.scss 3:1  @import
> > ```
> 
> here is temporary solution: [webpack-contrib/sass-loader#804 (comment)](https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020)

Works with sass ^1.26.10 and MDC 7.0.0

**Comment by chendoio** [comment] 2022-10-05 00:40
> Estuve obteniendo
> 
> > ERROR en ./src/frontend/sass/main.scss Error al compilar el 
> > módulo (de ./node_modules/sass-loader/dist/cjs.js): 
> > SassError: CSS no válido después de "@includemixins": se esperaba 1 selector o regla at, era ".core-styles;" 
> > en la línea 24 de node_modules/@material/button/mdc-button.scss
> 
> y lo arregló quitando `node-sass`e instalando `sass@1.25.0`.


it worked for me just updating sass, thanks
