### ISSUE TITLE
Fab button with class mdc-fab--exited breaks ripple effect

### ISSUE THREAD

**Issue by MarkOGDev** [material-components/material-components-web#2494] opened 2018-03-31 14:11 UTC
Fab button with class mdc-fab--exited breaks ripple effect
 

### What MDC Web Version are you using?

@material/fab v0.33.0
@material/ripple v0.33.0

### What browser(s) is this bug affecting?

FireFox v59.0.1

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

**See Code Pen:**
https://codepen.io/anon/pen/KoRpEP

**More Info:**
Add a Fab Button with class **mdc-fab--exited**
Add the ripple effect to the Fab Button.
Use JavaScript to remove the class **mdc-fab--exited** and show the Fab Button.
Click the Fab Button and the ripple effect does not work correctly.

The style added by Ripple looks like this.
--mdc-ripple-fg-size:0.360003662109375px; --mdc-ripple-fg-scale:30.134517814439533; --mdc-ripple-fg-translate-start:15.370001220703125px, 22.81999816894531px; --mdc-ripple-fg-translate-end:0.120001220703125px, 0.120001220703125px;

But it should look more like this:
--mdc-ripple-fg-size:33.6px; --mdc-ripple-fg-scale:2.654641651574206; --mdc-ripple-fg-translate-start:11.2px, 13.2px; --mdc-ripple-fg-translate-end:11.2px, 11.2px;

You can see the ripple effect sizing is wrong. 
 
### What is the expected behavior?

A nice ripple effect.

### What is the actual behavior?

The ripple effect is too small and looks bad.

**Comment by acdvorak** [comment] 2018-04-02 20:41
Thanks for filing this issue!

It looks like the ripple is trying to measure the component's size while it's still animating from `scale(0)`.
(Possibly a duplicate of #2207)

As a workaround, try calling `.layout()` on the `MDCRipple` _after_ the `transitionend` event:

https://codepen.io/acdvorak/pen/eMKeez?editors=1010#0

```js
var fab = document.querySelector('#fab');
var ripple = mdc.ripple.MDCRipple.attachTo(fab);

fab.addEventListener('transitionend', () => ripple.layout());
fab.classList.remove('mdc-fab--exited');
```

Does that work for you?

**Comment by MarkOGDev** [comment] 2018-04-03 08:33
Hello acdvorak,

Yes, that works fine.
Thanks for your help.

**Comment by acdvorak** [comment] 2018-04-05 18:02
Glad to hear it! 😁

**Closed** 2018-04-05 18:02 UTC
