### ISSUE TITLE
[mdc-textfield] Outlined input box label color incorrect on hover

### ISSUE THREAD

**Issue by mashirozx** [material-components/material-components-web#7241] opened 2021-07-16 15:26 UTC
## Bug report

![image](https://user-images.githubusercontent.com/16148054/125968761-def54bfc-9522-402f-8cca-53b1d81b9b8f.png)

### Steps to reproduce
```scss
@use "@material/theme/index" with (
  $primary: #2271b1,
  $secondary: #72aee6,
  $on-primary: #ffffff,
  $on-secondary: #ffffff,
);
@use "@material/textfield/mdc-text-field";
```

### Actual behavior

It uses the default color.

### Expected behavior

The label should be in `$primary: #2271b1`.

### Screenshots

![image](https://user-images.githubusercontent.com/16148054/125971205-423c4ea5-6c7e-4153-baf2-3d195cb2d1dd.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |"@material/textfield": "^12.0.0-canary.9f68a932e.0","@material/theme": "^12.0.0-canary.9f68a932e.0",|
| Browser          |Chrome 91|
| Operating System |macOS 11.4|

### Additional context

"yarn": ">= 1.22.10",
"node": ">= 14.17.1",

"vite": "^2.4.2",
"sass": "^1.35.1",
"sass-loader": "^12.1.0",

**Comment by joyzhong** [comment] 2021-07-16 19:09
Can you please provide a Codepen/Glitch demo?

**Comment by DouglasRiddle** [comment] 2021-08-09 18:20
I have this same issue when using the CDN. I have created a codepen example at the below url. I also included the various places I have found where I have to override the default purple color.

[codepen: MDC Web Hard-coded Purples](https://codepen.io/DouglasRiddle/pen/YzVdqRr)

**Comment by asyncLiz** [comment] 2021-08-10 23:24
Thanks for the update! This is actually a duplicate of https://github.com/material-components/material-components-web/issues/2718, so I'm going to close it to clean up our issues.

Text field, along with many other components, is getting a theming refresh for improved customization support, so this issue will be resolved when that happens.

**Closed by asyncLiz** 2021-08-10 23:24 UTC
Labels: bug, needs-response

**Comment by mashirozx** [comment] 2021-08-10 23:49
Hello， I've read #2718, but in the contrary, I set the color with @material/theme in scss. I also tried the css variable, it is OK. 
![image](https://user-images.githubusercontent.com/16148054/128949059-993a53a4-68b8-489f-b23e-597c66cf543e.png)
 As you can see above, the default var value isn't correct, I think it should also be the default purple.
Can this issues be reopened?

**Comment by asyncLiz** [comment] 2021-08-13 21:38
#2718 is "mdc-floating-label does not use theme colour". I believe this describes the issue you are describing. The floating label is not using the theme color that was configured (`$primary: #2271b1`)
