### ISSUE TITLE
how to add density to components

### ISSUE THREAD

**Issue by cojua8** [material-components/material-components-web#5814] opened 2020-04-14 13:39 UTC
Hi, 

I'm new to web development, and I'm trying to change density of the components that my UI uses. So far, I have managed to change button density, but I'm stuck in tab bar, text field and some others. I have tried everything, but nothing works.

Any help is welcome

**Comment by asyncLiz** [comment] 2020-04-15 18:31
Hi, can you add a reproduction or some code of what you have tried? Have you tried using the [density mixin for textfield](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mixins-for-filled-text-field-only)?

```scss
@use "@material/textfield";

.my-text-field {
  @include textfield.density(-4);
}
```

**Comment by cojua8** [comment] 2020-04-16 23:30
Hi,

Unfortunately, I have moved to CDN (and for what I understand, I can't use mixins).

But to answer your question, I did try using that exact lines and it didn't work

**Comment by asyncLiz** [comment] 2020-04-17 01:30
Unfortunately no, you won't be able to use Sass through CDN. There is no other way to apply density or other style customizations except through Sass.

I'd recommend reading through the [Installing Locally](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#installing-locally) section of our Getting Started guide to walk through how to get set up for local development with Sass.

I'll go ahead and close this issue since the problem is using a CDN where density customization isn't supported. Feel free to report back if you run into any more issues.

**Closed by asyncLiz** 2020-04-17 01:30 UTC
Labels: needs-response
