### ISSUE TITLE
discrete mdc-slider doesn't have a visual focus indication

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#1427] opened 2017-10-16 11:27 UTC
### What MDC-Web Version are you using?

0.22.2

### What browser(s) is this bug affecting?

Tested on chrome

### What OS are you using?

Doesn't matter

### What are the steps to reproduce the bug?

1. Browse to https://material-components-web.appspot.com/slider.html
2. Use the tab key to change the focus to the different inputs on the page

### What is the expected behavior?

All sliders should have a visual indication when they receive focus. (See the guidelines https://material.io/guidelines/components/sliders.html ).

### What is the actual behavior?

The discrete sliders do not have a visual indication when they receive focus. This doesn't conform with the guidelines on https://material.io/guidelines/components/sliders.html

This is caused by the styling overrides for .mdc-slider--discrete.mdc-slider--focus .mdc-slider__focus-ring in the .scss files. Please note that for a discrete slider with markers, the marker should be shown on focus (according to the guidelines linked above), for that there doesn't seem to be any styling at all.

**Comment by kfranqueiro** [comment] 2017-10-16 18:52
Thanks for pointing this out; definitely a bug.

**Comment by lynnjepsen** [comment] 2018-01-23 21:28
Duplicate of #1588

**Closed by lynnjepsen** 2018-01-23 21:28 UTC
Labels: bug, in-tracker
