### ISSUE TITLE
[MDCSelect] Some dropdown options are inaccessible if a parent element has overflow:hidden

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#5693] opened 2020-03-09 15:57 UTC
### Steps to reproduce
1. Go to [this pen](https://codepen.io/Darhakexge/pen/yLNpVNX)
2. Open the select menu
3. Some items of the select menu are inaccessible

### Actual behavior

If a MDCSelect parent element has an `overflow:hidden` style, some dropdown options may be inaccessible

### Expected behavior
The dropdown options should be visible over any element

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |5.1.0
| Browser          |All
| Operating System |Windows 10

### Additional context
This bug was introduced in #5113 since `hoistMenuToBody` was removed from MDCMenu

**Comment by asyncLiz** [comment] 2020-03-09 17:42
Duplicate of #5590

**Closed by asyncLiz** 2020-03-09 17:42 UTC
Labels: bug
