### ISSUE TITLE
MDCDrawer: CRASH/REGRESSION: FocusTrap: Element must have at least one focusable child

### ISSUE THREAD

**Issue by regnaio** [material-components/material-components-web#6843] opened 2021-02-07 04:51 UTC
**Describe the bug**
REGRESSION: No issues with v8.0.0. Somewhere between v8.0.0 to v10.0.0, this crash was introduced

(I'm using npm)

When opening a MDCDrawer, this crash occurs

I'm just using the **modal navigation drawer** example from https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

Observe that when the drawer is opened, v8.0.0 surrounds the `mdc-drawer__content` with `mdc-dom-focus-sentinel` with `tabindex="0"`, as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
    <div class="mdc-drawer__content">...</div>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
</aside>
```

v10.0.0 forgets to do this surround, as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div class="mdc-drawer__content">...</div>
</aside>
```

Due to no wrapping with `tabindex="0"`, this causes `focusableEls.length === 0`, which causes the crash (source code below)

```
if (focusableEls.length === 0) {
    throw new Error('FocusTrap: Element must have at least one focusable child.');
}
```

Can we please bring back the behavior that wraps and does not crash?

**Comment by patrickrodee** [comment] 2021-03-19 19:00
Closing as a duplicate of #6829 which has a more up-to-date comment stream.

**Closed by patrickrodee** 2021-03-19 19:00 UTC
