### ISSUE TITLE
MDC Select floating label overflows to top

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#1835] opened 2017-12-24 16:57 UTC
### What MDC-Web Version are you using?

0.0.27

### What browser(s) is this bug affecting?

Chrome (also others I guess)

### What OS are you using?

Mac

### What are the steps to reproduce the bug?

1. Create a select box with very small options e.g. `Opt1, Opt2, Opt3`

2. Put the surface label bigger than options length e.g. `Select an option`

3. When selection an option in browser, notice that floating label is broken

### What is the expected behavior?

If the floating label is quite big to display, may be add ellipses to it.

### What is the actual behavior?

The text overflows out of the select viewport
<img width="145" alt="screen shot 2017-12-24 at 8 52 31 am" src="https://user-images.githubusercontent.com/5960497/34328017-717bc16a-e888-11e7-8473-629419824e5a.png">

**Comment by acdvorak** [comment] 2018-01-04 23:19
Thanks for taking the time to report this issue!

That sure looks like a bug. Added it to our internal issue tracker.

**Comment by acdvorak** [comment] 2018-01-05 00:08
Duplicate of #1864

**Comment by kf106** [comment] 2018-01-17 00:24
I think I have the same issue, with slightly different behaviour after the select list is used, possibly because I'm using MDC for web with the full js and css packages downloaded and stored locally (wget on Jan 15, 2018 - it would be nice if they had a version number in the headers).

I initially had a mdc-select__label that was longer than the longest list item, and parts of it disappeared off the top of the list pane. Then I shortened the label to be shorter than the longest list item. Now, when I see the list for the first time the text is too large and overwrites the aria-selected item.

After selecting an item of the list the label floats up and everything looks normal.

HTML snippet:

        <div>
		    <div class="mdc-select" role="listbox" data-mdc-auto-init="MDCSelect" id="js-select-box">
              <div class="mdc-select__surface" tabindex="0">
                <div class="mdc-select__label">RDBMS</div>
                <div class="mdc-select__selected-text"></div>
                <div class="mdc-select__bottom-line"></div>
              </div>
              <div class="mdc-simple-menu mdc-select__menu">
                <ul class="mdc-list mdc-simple-menu__items">
                       <li class="mdc-list-item" role="option" tabindex="0" aria-selected id="S">
                       SQL Server
                       </li>
                   
                       <li class="mdc-list-item" role="option" tabindex="0" id="M">
                       MySQL RDBMS
                       </li>
                   
                </ul>
		      </div>
            </div>
        </div>

What it looks like at first:
![listbox-001](https://user-images.githubusercontent.com/25053735/35019005-20862298-fb2d-11e7-9efc-f2ef400e53d6.png)

Then you go to select something:
![listbox-002](https://user-images.githubusercontent.com/25053735/35019009-2a28d886-fb2d-11e7-936d-7425c3d0213d.png)

After selecting it looks right:
![listbox-003](https://user-images.githubusercontent.com/25053735/35019012-3356b73e-fb2d-11e7-91e0-ecfee7805a92.png)

**Comment by kf106** [comment] 2018-01-17 12:53
I have since discovered https://github.com/material-components/material-components-web/issues/1810 which addresses half of the problem here.

**Comment by kfranqueiro** [comment] 2018-02-05 21:53
Codepen from #2166: https://codepen.io/anon/pen/qxbmWm

**Closed** 2018-10-26 20:53 UTC
Labels: bug, icebox
