### ISSUE TITLE
[MDCMenu] Menus overlapping MARGIN_TO_EDGE are cropped 

### ISSUE THREAD

**Issue by dgoogles** [material-components/material-components-web#5603] opened 2020-02-13 18:38 UTC
## Bug report
MDCMenu that is positioned near the bottom edge of the screen will get cropped to a thin line rather than being repositioned above the anchor. getOriginCorner_ doesn't use MARGIN_TO_EDGE, but getMenuSurfaceMaxHeight_ does, causing the inconsistency and cropping.

### Steps to reproduce
1. Create a menu that opens near the bottom of the screen where it would overlap MARGIN_TO_EDGE
2. Notice how the menu is cropped instead of being repositioned above the anchor

### Actual behavior
The menu gets cropped because of its max-height property

### Expected behavior
The menu should be aligned BOTTOM instead of TOP.

### Screenshots
<img width="453" alt="Screen Shot 2020-02-13 at 1 35 58 PM" src="https://user-images.githubusercontent.com/56900427/74466714-cdd25b00-4e65-11ea-8be7-3135a092c6c5.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.0.0-canary.a1a0deb3e.0
| Browser          | Chrome
| Operating System | OSX

### Additional context
This was surfaced while using the web-components version of the MDCMenu but the error appears to be here.

### Possible solution
getOriginCorner_ should take into account the MARGIN_TO_EDGE here: https://github.com/material-components/material-components-web/blob/8c11ea2a3bd7962c6d895c5bd6b849f95b52d10c/packages/mdc-menu-surface/foundation.ts#L325 and reposition the menu above.

**Comment by dgoogles** [comment] 2020-02-13 19:25
Just saw this is a duplicate of https://github.com/material-components/material-components-web/issues/5373 However there hasn't been much update on that. Is this being worked on or does it need a PR?

**Comment by asyncLiz** [comment] 2020-02-14 23:13
Going to close since it's a duplicate of #5373. @harpojaeger was working on a fix in https://github.com/harpojaeger/material-components-web/tree/bug/menu-surface/scrollbar, you can follow the issue for updates!

**Closed by asyncLiz** 2020-02-14 23:13 UTC
Labels: bug
