### ISSUE TITLE
[MDCSelect] Overflow select menu in MDCDialog when browser is resized

### ISSUE THREAD

**Issue by axxie** [material-components/material-components-web#7438] opened 2021-11-03 10:23 UTC
## Bug report

When the fixed menu surface is used in MDCSelect on a MDCDialog and the browser window is resized, the position of the menu surface is not synchronized with the position of the select.

The reason is that the fixed menu surface is positioned against window borders, but the dialog is centered. As the result, the menu surface and the dialog move differently during resize.

Demo project: https://glitch.com/edit/#!/material-select-overflow

The issue relates to #5590 and #6735

### Steps to reproduce
1. Create MDCDialog with MDCSelect
2. Add some items to the menu of the MDCSelect
3. Set menu surface to “fixed” by adding “mdc-menu-surface--fixed" class
4. Run the created project, open dialog and click on the MDCSelect to open the menu
5. Try to resize the browser window

### Actual behavior
The menu surface moves separately from the MDCSelect

### Expected behavior
The menu surface should move together with MDCSelect

### Screenshots

![image](https://user-images.githubusercontent.com/5149179/140043158-c53b4ee3-541b-44ba-9405-553c63505623.png)

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |13.0.0|
| Firefox          |94.0|
|Chrome| 95.0.4638.69|
| Operating System |Windows 10, 21H1, OS Build 1904.1288|

### Additional context
The [glitch project](https://glitch.com/edit/#!/material-select-overflow) shows 3 buttons.

![image](https://user-images.githubusercontent.com/5149179/140043503-bb4fa295-a07f-4292-92ae-f72b8c0920ca.png)

The first one opens dialog with select without fixed menu surface. This leads to scroll appearing inside the dialog.
The second button opens dialog with fixed select that demonstrates the issue with window resize. Hoisting the menu surface to the body leads to the same issue with window resize.

### Possible solution
The third button opens dialog with fixed select with the following workaround: the menu is closed if the window is resized. The close itself is not very clean: the user can still see the menu surface moving before it completely disappears.

Besides the bug report, I would like to ask if there is some other workaround for the issue.

**Comment by abhiomkar** [comment] 2021-11-17 20:52
Thanks for reporting the issue!

Your workaround seems fine to me. i.e., closing the menu when window resize is detected. Component itself will not listen for window resize itself but it is consumer's or application's responsibility to listen for window resize event and close the menu accordingly. 

I'm closing this bug as working as intended. Feel free to re-open or add a comment if you've any questions!

**Closed by abhiomkar** 2021-11-17 20:52 UTC
Labels: bug
