### ISSUE TITLE
Tabs Showing Ripple Only Once

### ISSUE THREAD

**Issue by dchenk** [material-components/material-components-web#947] opened 2017-07-14 21:30 UTC
When the tabs are displayed, I can click on any of them and the indicator bar moves to the new tab correctly; however, the ripple appears on the clicked tab once, and if I move to another tab the ripple appears only if that tab wasn't already click and wasn't the initial tab. In the demo, the tabs were showing ripples every time they were clicked.

**MDC-Web Version:**
- **material/base: "^0.2.2"**
- material/button: "^0.3.9"
- material/checkbox: "^0.4.0"
- material/drawer: "^0.5.2"
- material/list: "^0.2.12"
- material/menu: "^0.4.1"
- material/ripple: "^0.8.0"
- material/select: "^0.3.10"
- **material/tabs: "^0.2.3"**
- material/textfield: "^0.3.1"
- material/toolbar: "^0.4.1"

**Browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)

**OS:** MacOS Sierra (10.12.5)

I am using Webpack on NPM to build my Vue.js project.

I'm running this line in the `mounted()` function of Vue:
`const tabBarScroller = new MDCTabBarScroller(document.getElementById("my-tabs"))`

The HTML looks like this:
```
<div id="my-tabs" class="mdc-tab-bar-scroller">
	<div class="mdc-tab-bar-scroller__indicator mdc-tab-bar-scroller__indicator--back"><div class="mdc-tab-bar-scroller__indicator__inner material-icons" aria-label="scroll back">navigate_before</div></div>
	<div class="mdc-tab-bar-scroller__scroll-frame">
		<nav id="my-scrollable-tab-bar" class="mdc-tab-bar mdc-tab-bar-scroller__scroll-frame__tabs">
			<router-link to="/account" class="mdc-tab">MAIN ACCOUNT OPTIONS</router-link>
			<router-link to="/account/payment" class="mdc-tab">PAYMENT</router-link>
			<span class="mdc-tab-bar__indicator"></span>
		</nav>
	</div>
	<div class="mdc-tab-bar-scroller__indicator mdc-tab-bar-scroller__indicator--forward"><div class="mdc-tab-bar-scroller__indicator__inner material-icons" aria-label="scroll forward">navigate_next</div></div>
</div>
```

It seems like this problem started occurring after I upgraded all the material components I'm using a few days ago (July 11). Perhaps this is happening because of the new upgrade? (BTW, the ripple effect is working great on buttons.)

**Comment by amsheehan** [comment] 2017-07-18 19:01
Does this happen with any other component that `mdc-ripple` is attached to?

**Comment by dchenk** [comment] 2017-07-19 00:10
Nope, just the tabs.

**Comment by lynnjepsen** [comment] 2017-07-21 22:49
Hmm, this is tricky. I reviewed you're attached HTML structure, and it looks correct to me. We haven't done any large changes to ripple or tabs, so I don't have a good sign of an issue that might be causing you're problem. And I cannot reproduce this error on our demos (as you mentioned), so it most likely is a version problem, or a Vue problem.

Maybe you can help us out @dchenk. How would you feel about submitting a Pull Request to add tabs to our [framework examples directory](https://github.com/material-components/material-components-web/tree/master/framework-examples/vue)? It might help us reproduce you're issue, and then we can figure out the right fix.

**Comment by yeelan0319** [comment] 2017-07-25 19:52
@dchenk We are still not quite able to reproduce the issue on our end. Could you send a codepen or as Lynn suggested an PR to our framework examples?

**Comment by dchenk** [comment] 2017-08-04 01:02
Hello. Thank you for your efforts already. Could this be happening because I'm attaching the tabs component to the element by `document.getElementById` instead of `document.querySelector`?

**Comment by grzegorztomasiak** [comment] 2017-10-20 20:39
I have the same problem. It turned out that when 'history mode' is enabled in VueRouter it does not properly work together with ripple due to url change (no hashbang). Note that  'indicator bar' works properly. However I don't know yet how to fix that. If anyone know on this planet, please share!

**Comment by kfranqueiro** [comment] 2018-08-01 15:07
We've since revamped tabs into separate `mdc-tab-bar`, `mdc-tab-scroller`, `mdc-tab`, and `mdc-tab-indicator` packages in 0.38. Between that and our inability to repro this issue, I'm going to close it.

**Closed by kfranqueiro** 2018-08-01 15:07 UTC
