### ISSUE TITLE
[SWITCH] scss warning

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7302] opened 2021-08-08 08:09 UTC
## Bug report
Warning shows up during SCSS compilation
```
WARNING: $level must be between 0 and 24; received ''
    ..\..\node_modules\@material\elevation\_elevation-theme.scss 225:5   -shadow()
    ..\..\node_modules\@material\elevation\_elevation-theme.scss 457:20  resolver()
    ..\..\node_modules\@material\tokens\_resolvers.scss 5:11             -material-elevation()
    ..\..\node_modules\@material\elevation\_elevation-theme.scss 417:21  with-resolver()
    ..\..\node_modules\@material\switch\_switch-theme.scss 376:5         -set-handle-elevation()
    ..\..\node_modules\@material\switch\_switch-theme.scss 358:5         @content
    ..\..\node_modules\@material\theme\_state.scss 231:5                 @content
    ..\..\node_modules\@material\theme\_state.scss 253:5                 @content
    ..\..\node_modules\@material\theme\_state.scss 747:7                 -selector()
    ..\..\node_modules\@material\theme\_state.scss 252:3                 enabled()
    ..\..\node_modules\@material\theme\_state.scss 230:3                 default()
    ..\..\node_modules\@material\switch\_switch-theme.scss 357:3         -handle-elevation()
    ..\..\node_modules\@material\switch\_switch-theme.scss 191:3         theme-styles()
    ..\..\node_modules\@material\switch\styles.scss 38:5                 @content
    ..\..\node_modules\@material\dom\_dom.scss 93:7                      forced-colors-mode()
    ..\..\node_modules\@material\switch\styles.scss 36:1                 @use
    ..\..\node_modules\@aurelia-mdc-web\all\mdc-all.scss 30:1            @forward
    ..\..\node_modules\@aurelia-mdc-web\all\_index.scss 1:1              @use
    src\views\root\root.scss 9:1                                         root stylesheet
```
### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          |
| Operating System |

### Additional context
As far as I understand, `handle-elevation` is missing in the `$forced-colors-theme` which causes this warning via 
```scss
@include dom.forced-colors-mode {
  .mdc-switch {
    @include switch-theme.theme-styles(switch-theme.$forced-colors-theme);
  }
}
```

**Comment by asyncLiz** [comment] 2021-08-10 23:10
Duplicate of https://github.com/material-components/material-components-web/issues/7240

**Closed by asyncLiz** 2021-08-10 23:10 UTC
Labels: bug
