### ISSUE TITLE
mdc-select change event is emitted when component preinitialized with a value

### ISSUE THREAD

**Issue by ftaiolivista** [material-components/material-components-web#5866] opened 2020-04-28 15:29 UTC
mdc-select emit MDCSelect:change when initialized on DOM structure with pre-selected option.

I think is a bug. The change event should be emitted only in successive changes.

**Comment by abhiomkar** [comment] 2020-04-28 15:36
Select component calls `setSelectedIndex()` during initialization to set initial selected state which causes it to trigger event.

IMO, Any programmatic changes (i.e., `setSelectedIndex()` API) should not trigger events. Similar to how native components do not trigger change events when programmatically settings its value. Example, `input.value = 'foo'` does not trigger event)

/cc @allan-chen

**Comment by allan-chen** [comment] 2020-04-28 21:31
Duplicate of #5783. Fix is in flight.

**Closed by allan-chen** 2020-04-28 21:31 UTC
Labels: backlog, bug
