### ISSUE TITLE
Issue with indeterminate state change for css checkbox on IE

### ISSUE THREAD

**Issue by taedh86** [material-components/material-components-web#2262] opened 2018-02-16 10:11 UTC
Changing state of an indeterminate checkbox by clicking it on other browsers then IE change it state to checked. In internet explorer 11 it is changed to unchecked without triggering on change event. This behaviour can be seen in examples section for checkbox: https://material-components-web.appspot.com/checkbox.html - CSS only - Indeterminate checkbox.

**Comment by kfranqueiro** [comment] 2018-02-16 14:59
This sounds like a duplicate of #1503 (see in particular https://github.com/material-components/material-components-web/issues/1503#issuecomment-342367168).

For CSS-only in particular, there's not much we can do without scripting, since this is simply how the browser behaves.

**Closed by kfranqueiro** 2018-02-16 14:59 UTC
