### ISSUE TITLE
MDC-snackbar with action opening a blank window calls cleanup function more than once

### ISSUE THREAD

**Issue by pgbross** [material-components/material-components-web#2545] opened 2018-04-10 15:59 UTC
### What MDC Web Version are you using?

> 0.34.1

### What browser(s) is this bug affecting?

> Chrome Version 66.0.3359.81 (Official Build) beta (64-bit)

### What OS are you using?

> Fedora 28 workstation 4.16.0-300.fc28.x86_64

### What are the steps to reproduce the bug?

> 1. Run a page with a snackbar and a button to show it.
> 2. Set snack data to have action hanndler that opens a window target _blank
> 3. Show snackbar, follow action, wait for new window to render
> 4. Go back to original tab, wait for timeouts behind the scene to complete
> 5. Show snackbar, observe action button is missing, and is never dismissed.
>
> See [codepen](https://codepen.io/anon/pen/dmaarK) for example.

### What is the expected behavior?

> When the snackbar cleans itself up it should it may need to be aware the window.transitionend isn't captured or otherwise guard against it not happening at the right time.

### What is the actual behavior?

> The foundation cleanup_() method appears to be called multiple times without a transitionend actually occuring.

### Any other information you believe would be useful?
If you use the codepen above and experiment with the timing of when you press the "show" button relative to when you return from the newly opened tab, you will see other effects such as the next snackbar being dismissed well before its expected timeout.

**Comment by acdvorak** [comment] 2018-04-16 17:59
Possibly a dupe of #1398

**Closed** 2018-04-16 18:44 UTC
