### ISSUE TITLE
textfield label doesn't float while invalid text is present (e.g. in number fields)

### ISSUE THREAD

**Issue by namannehra** [material-components/material-components-web#2744] opened 2018-05-15 14:05 UTC
### Conditions for the bug
- The `type` attribute of the `input` element should be set to `number`
- The text entered should of the form number-number. Example: 12-345

### Steps to reproduce the bug
1. Open https://codepen.io/namannehra/pen/aGaNZv
2. Enter "1-1" in the textfield
3. Unfocus the textfield
4. Look at the label

### Expected behavior
The label should be floating after losing focus

### Actual behavior?
The label is **not** floating after losing focus

### Browsers affected
Chrome/66.0.3359.139
Edge/17.17134
Firefox/59.0

**Comment by williamernest** [comment] 2018-05-15 15:03
@namannehra Thanks for filling this issue. Our textfield doesn't support `number` as an input type just yet. Each browser behaves a little differently, but when a non number character is entered into the field, the `value` of the input becomes an empty string (because the input is invalid). We use the `value` of the input to determine if the user entered anything so we can return the label to it's resting position. 

https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

**Comment by namannehra** [comment] 2018-05-18 16:28
Is there a plan to support other input types? Is yes then which types should be supported and when should the label be floating for each supported type? If this is finalised then I would like to work on implementing them. I suggest the following types to be supported:

`password`, `search`, `text`
The current behavior is fine for these types. Float the label when value is not empty.

`color`, `date`, `datetime-local`, `file`, `month`, `time`, `week`
Most browsers show some UI for these types even when the value is empty. So for these types the label should always be floating.

`email`, `number`, `tel`, `url`
For these types the `input.value` might return an empty string if an invalid value is present. In such cases the label should float. One solution might be:
1. change `type` to `text`
2. get value using `input.value`
3. change `type` back to original type
4. float label if value is not empty

**Comment by kfranqueiro** [comment] 2018-05-21 19:16
We'd certainly be interested in finding a reliable solution to this problem. I'm going to track this issue, but we're definitely open to suggestions / PRs.

I just [briefly prototyped](https://codepen.io/kfranqueiro/pen/qYvONW) your `type`-change idea, but unfortunately it immediately nukes any invalid value upon changing the type (in Chrome, at least).

**Comment by merlinnot** [comment] 2018-05-21 19:42
Isn't `input.validity.badInput` enough? If it's true, float the label.

**Comment by williamernest** [comment] 2018-05-21 19:45
@merlinnot `input.vaidity.vadInput` returns true if a field is required and the user left it empty (after entering it). In this case, we want the label to return to the original position because the field is still empty.

**Comment by namannehra** [comment] 2018-05-21 19:49
@williamernest So can we remove require, check `input.validity.badInput` and re-add it?

**Comment by merlinnot** [comment] 2018-05-21 20:10
@williamernest  Hm, I can't reproduce it. Can you take a look at [this](https://stackblitz.com/edit/js-ugtcen?file=index.js)?

**Comment by namannehra** [comment] 2018-05-21 20:31
@williamernest You are right. `input.vaidity.vadInput` returns true if a field is required and the user left it empty but `input.validity.badInput` **does not** return true in this case. So it can used to check if label should float.

@merlinnot Your code works because of the same reason. It checks against `input.validity.badInput`. The check you are performing for `input.validity.valid` is not needed.

This is an example using `input.validity.badInput`: https://codepen.io/namannehra/pen/jxJWZN

**Comment by merlinnot** [comment] 2018-05-21 20:37
Y I know, I've updated it a few minutes after I posted :) But it works fine, right? Or is there an edge case/browser I'm missing?

**Comment by namannehra** [comment] 2018-05-21 20:39
It's working fine for me

**Comment by williamernest** [comment] 2018-05-25 23:33
Resolved with #2781

**Closed by williamernest** 2018-05-25 23:33 UTC
Labels: bug, in-tracker
