### ISSUE TITLE
Menu on small-height screen is partially hidden

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#541] opened 2017-04-21 09:30 UTC
### What MDC-Web Version are you using?

0.9.1

### What browser(s) is this bug affecting?

Chrome 57, Firefox 52, most likely all others

### What OS are you using?

Windows

### What are the steps to reproduce the bug?

1. http://material-components-web.appspot.com/simple-menu.html
2. Reduce viewport's height so that the `Toggle` button is almost in the left lower corner.
3. Click `Toggle`.
4. Menu will open from bottom to top.

### What is the expected behavior?

All options of the menu must be visible.

### What is the actual behavior?

Only a few options are available to choose from, the upper bound of the menu is beyond the top of the viewport.

### Any other information you believe would be useful?

When the menu opens from top to bottom, a scrollbar will appear if necessary, so all options are always accessible. But when the menu opens from bottom to top, its upper part gets hidden on small screens.

**Comment by traviskaufman** [comment] 2017-04-24 15:31
Thanks for reporting @anton-kachurin! We actually took this into account in `mdc-select` by adding `overflow-y: scroll` (https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/mdc-select.scss#L92). I wonder if it's just a matter of refactoring that out into `MDCSimpleMenu`?

**Comment by anton-kachurin** [comment] 2017-04-24 20:37
A scroll bar looks somewhat foreign in menus, in my opinion. Might it better just not to open the menu from bottom to top when there is not enough space above the anchor, and open it from top to bottom in that case? Seems like a simple fix `if (extendsBeyondTopBounds && bottomOverflow <= 0) {` here (https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L334)

**Comment by traviskaufman** [comment] 2017-05-18 15:30
The issue with that approach is that sometimes there are so many menu items that even if you were to expand it to be the full height of the page it may still overflow. In that case, scrolling is needed.

**Comment by RobJacobs** [comment] 2017-07-25 20:00
@traviskaufman @anton-kachurin I solved this by adding

    height: calc(100vh - 32px)

To the mdc-simple-menu.scss mdc-simple-menu__items class.  I think the issue is an element with overflow needs to have a height to calc from.

**Comment by williamernest** [comment] 2018-08-28 21:56
Closing this issue since it seems to have been resolved by calculating the height of the window and setting the max-height of the menu based on the size of the window.

**Closed by williamernest** 2018-08-28 21:56 UTC
Labels: bug, in-tracker
