### ISSUE TITLE
[Button] button bg turns white on hover

### ISSUE THREAD

**Issue by BhavyaSingh2611** [material-components/material-components-web#4849] opened 2019-06-20 06:58 UTC
## Bug report
button placed in a card turns white on hover

### Video

[Youtube](https://youtu.be/--4aOf2mmvk)

### Actual behavior
button placed in mdc card turn white on hover

### Expected behavior
button shouldn't turn white on hover

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  2.3.1
| Browser          |  Chrome 75
| Operating System |  Windows 10

### Additional context
the source code `<html> <head> <meta charset="utf-8"> <title>Sign in – Bolt ID accounts</title> <meta name="viewport" content="width=device-width, initial-scale=1"> <script src="../dist/bundle.js"></script> <script src="../node_modules/material-components-web/dist/material-components-web.min.js"></script> <style>html, body{margin: 0; height: 100%; width: 100%;}.main{width: 448px; height: 500px; margin-top: calc(50vh - 250px);}@media all and (max-width:601px){.main{width: 100%; height: 100%; margin-top: 0}}.progress{border-top-left-radius: 4px; border-top-right-radius: 4px;}.content{padding: 24px; background-color: #f5f5;}.username{width: 80%;}</style> </head> <body> <button class="mdc-button mdc-button--raised"> <span class="mdc-button__label">Next</span> <i class="material-icons mdc-button__icon" id="next_icon">chevron_right</i> </button> <center> <div class="mdc-card mdc-card--outlined main"> <div role="progressbar" class="mdc-linear-progress mdc-linear-progress--indeterminate progress"> <div class="mdc-linear-progress__buffering-dots"></div><div class="mdc-linear-progress__buffer"></div><div class="mdc-linear-progress__bar mdc-linear-progress__primary-bar"> <span class="mdc-linear-progress__bar-inner"></span> </div><div class="mdc-linear-progress__bar mdc-linear-progress__secondary-bar"> <span class="mdc-linear-progress__bar-inner"></span> </div></div><div class="content"> <div class="mdc-text-field mdc-text-field--outlined username"> <input type="text" id="username" class="mdc-text-field__input"> <div class="mdc-notched-outline"> <div class="mdc-notched-outline__leading"></div><div class="mdc-notched-outline__notch"> <label for="username" class="mdc-floating-label">Username</label> </div><div class="mdc-notched-outline__trailing"></div></div></div><button class="mdc-button mdc-button--raised"> <span class="mdc-button__label">Next</span> <i class="material-icons mdc-button__icon" id="next_icon">chevron_right</i> </button> </div>Helo World!!! </div></center> <script>var buttons=document.querySelectorAll('.mdc-button, .mdc-fab'); for (var i=0, button; button=buttons[i]; i++){mdc.ripple.MDCRipple.attachTo(button);}var textfields=document.querySelectorAll('.mdc-text-field'); for (var i=0, textfield; textfield=textfields[i]; i++){mdc.textField.MDCTextField.attachTo(textfield);}var ibuttons=document.querySelectorAll('.mdc-icon-button'); for (var i=0, button; button=ibuttons[i]; i++){var a=mdc.ripple.MDCRipple.attachTo(button); a.unbounded=true;}</script> </body> </body></html>`

the bundle js is nothing but mdc web css bundle in js

**Comment by abhiomkar** [comment] 2019-06-21 17:29
Closing this as duplicate of #4780

**Closed by abhiomkar** 2019-06-21 17:29 UTC
Labels: bug
