### ISSUE TITLE
Drawers (All) rtl closed state is broken

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#1989] opened 2018-01-18 19:48 UTC
### What MDC Web Version are you using?

latest

### What browser(s) is this bug affecting?

Chrome 

### What OS are you using?

MacOSx

### What are the steps to reproduce the bug?

1. Head to https://material-components-web.appspot.com/drawer/temporary-drawer.html (or any of the drawers)
1. add `dir='rtl'` to <body> tag

### What is the expected behavior?

to not see the drawer

### What is the actual behavior?

drawer is in middle of page

<img width="838" alt="screen shot 2018-01-18 at 11 47 34" src="https://user-images.githubusercontent.com/579873/35118036-6c64a540-fc45-11e7-80c9-caf1677f5cec.png">

**Comment by acdvorak** [comment] 2018-01-19 23:53
Duplicate of #1930 😁

**Closed** 2018-01-20 00:04 UTC
Labels: in-tracker
