### ISSUE TITLE
temporary drawer does not work properly in mobile 

### ISSUE THREAD

**Issue by Nerogee** [material-components/material-components-web#2439] opened 2018-03-20 11:56 UTC
The drawer component does not work well in my iphoneX with both safari and latest chrome browser. 

The issue is when I expect the opened menu to hide, it starts to move away in a very slow speed and in a not smooth manner. Issue can be verified by going to the official demo page [drawer demo](https://material-components-web.appspot.com/drawer/temporary-drawer.html) with my phone.

 Is there any solution for it ?

**Comment by williamernest** [comment] 2018-03-20 14:20
Thanks for filing this issue. Is this the same problem as #1700 ?

**Comment by Nerogee** [comment] 2018-03-20 14:25
yes, it is. thanks .

**Comment by williamernest** [comment] 2018-03-20 14:26
Closed as a duplicate of #1700

**Closed by williamernest** 2018-03-20 14:26 UTC
