### ISSUE TITLE
Implement Expand/Colapse for mdc-list

### ISSUE THREAD

**Issue by KaRkY** [material-components/material-components-web#483] opened 2017-04-06 12:34 UTC
It would be nice to have Expand/Collapse on mdc-list as documented here.

https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by Garbee** [comment] 2017-04-06 14:59
Related to #46 

Same JS logic for both, just slightly different style on top to fit into lists.

**Comment by yeelan0319** [comment] 2017-04-06 15:40
Duplicate of #46 , we will close this one.

**Closed by yeelan0319** 2017-04-06 15:40 UTC

**Comment by CarlosV89** [comment] 2018-10-04 20:18
This doesn't really count as the "same" anymore since expansion panels are not part of the MDC Spec, but Expandable/Collapsible lists are.

https://material.io/design/components/lists.html#types

Sorry for reviving but should this remain closed?

**Comment by kfranqueiro** [comment] 2018-10-04 20:33
This is somewhat of a timely question, since I believe we'll be discussing scope/prioritization of List features across platforms sometime soon. We'll likely end up entering new issues to reflect the outcome of that discussion after it happens.

**Comment by Garbee** [comment] 2019-01-15 00:49
From the referenced issue this is a dupe of...

> This is no longer within scope of the MD spec, so we're no longer planning to add this to the core MDC Web repository.

**Comment by tamalsaha** [comment] 2019-01-15 01:12
But the material.io website still shows a `Expand and collapse` option for List. Is that going to be support in the MDc components?

![mdc-list](https://user-images.githubusercontent.com/94814/51151402-9c7cfb00-181f-11e9-8d48-887913bce472.png)

**Comment by calebccff** [comment] 2019-08-13 08:39
Is there any news on this? I'd really like this feature for a website.

**Comment by suhailkc** [comment] 2019-10-29 05:24
Any plan to implement Expand/Collapse?
It's necessary !!

**Comment by LionstoothSoftware** [comment] 2019-11-11 22:43
Does anyone have a good workaround? I'm about to just implement my own thing without using the MDC list.

**Comment by KingFalse** [comment] 2020-08-06 06:37
Need it!

**Comment by clevercodenl** [comment] 2020-08-31 10:54
Also need it

**Comment by jfbrennan** [comment] 2020-09-20 18:22
If not directly available is there a code sample for achieving the same? I can only find screenshots:
<img width="824" alt="Screen Shot 2020-09-20 at 11 18 49 AM" src="https://user-images.githubusercontent.com/1817868/93718777-1dcb7b80-fb33-11ea-8e12-a70f5889da1d.png">

I'm comparing Material Web's markup to [M-](http://m-docs.org/accordion) and want to make sure I'm putting out an accurate comparison. Right now I have to put "Unsupported" for Material, but the https://material.io/components/lists#types has that example in the screenshot above. Confusing...

**Comment by c-dinkel** [comment] 2020-10-27 14:49
This is not a duplicate of #46 any longer, since the spec does not contain the Expansion Panel any more.

This is now an issue again, since expanding and collapsing lists are still part of the spec.
