### ISSUE TITLE
Select Menu - iOS tap away to close menu

### ISSUE THREAD

**Issue by mellogarrett** [material-components/material-components-web#1605] opened 2017-11-16 13:34 UTC
### What MDC-Web Version are you using?
@material/select: 0.23.0
> Please be specific, e.g. _major.minor.patch_

### What browser(s) is this bug affecting?
Mobile Safari

### What OS are you using?
iOS 11

### What are the steps to reproduce the bug?
1. Tap on select menu to open
2. Tap out of select area
3. Notice that it does not close the menu as expected

### What is the expected behavior?
Tapping out of the select area should close the select menu

### What is the actual behavior?
You are locked in once opening the select menu and the only way to close it is to select an option

**Comment by kfranqueiro** [comment] 2017-11-16 22:59
Interesting that this only seems to happen in iOS Safari, but yup this looks like a bug, repro'd on a 10.3 simulator as well. Thanks for reporting.

**Comment by kfranqueiro** [comment] 2017-11-27 21:58
Actually, this sounds like it might be a duplicate of #693?

**Comment by GenericUK** [comment] 2017-11-30 07:15
No change in 0.26.0.
This is only happening on temporary drawer https://material-components-web.appspot.com/drawer/temporary-drawer.html

It works as expected here https://material.io/guidelines/patterns/navigation-drawer.html 

Is material.io site using MDC?

**Comment by markmcdowell** [comment] 2017-12-05 18:21
Interestingly with 0.26.0 on both chrome and safari in iOS the temporary drawer does shut for me but takes ages and is really jittery.

**Comment by rober42539** [comment] 2017-12-21 16:39
Looks like Firefox on iOS may have same issues too.

**Comment by rober42539** [comment] 2017-12-21 18:14
[Video Showing Issue on iOS Safari, with dramatic audio](https://youtu.be/tLNpllMggKI)

**Comment by mellogarrett** [comment] 2017-12-21 20:38
Found out this is because iOS doesn't emit a `click` event if the element you are tapping on isn't considered "clickable".

Workaround is setting all elements as "clickable"
```
@supports (-webkit-overflow-scrolling: touch) {
  /* CSS specific to iOS devices */
  * {
    cursor: pointer;
  }
}
```

**Comment by kfranqueiro** [comment] 2018-08-01 15:01
Closing this as duplicate of #693 RE menu behavior, and as obsolete since MDC Select uses a native input now.

**Closed by kfranqueiro** 2018-08-01 15:01 UTC
Labels: bug, in-tracker
