### ISSUE TITLE
MDC Menu should not preventDefault for space keys within inputs

### ISSUE THREAD

**Issue by thatcherkins** [material-components/material-components-web#2763] opened 2018-05-18 20:21 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC Web Version are you using?

0.35.1

### What browser(s) is this bug affecting?

Firefox 52.7.3

### What OS are you using?

Windows 7

### What are the steps to reproduce the bug?

1.  Displaying an MDCMenu on a button click.  The MDCMenu has an integrated text input.

2.  Type 'MDC Test' into text input.

### What is the expected behavior?

1.  I expect 'MDC Test' to be visible in the text input

### What is the actual behavior?

1.  'MDCTest' is displayed.  All spaces are being eaten by the menu

### Any other information you believe would be useful?

I tracked down in the MDCMenu code a check for a space to stop any unwanted scrolling.  I'm not
sure why no one else is seeing this.  I am using React so the event model is different and might be
causing some strange event bubbling but it doesn't seem like it should be.
**Spaces are actually eaten everywhere in Firefox, even the debug console.

**Comment by williamernest** [comment] 2018-05-18 20:51
@thatcherkins Thanks for filling this issue. This is a known issue at the moment and will be addressed in the coming weeks with a redesigned menu component. The issue was the space key was bubbling up and causing the page to scroll. We were preventing that from happening by calling `event.preventDefault()`. This has the additional problem of preventing people from using the text input inside the menu. 

This issue will be resolved with the redesigned menu (#2758). Also, a react workaround that may help is in #2422.

**Comment by kfranqueiro** [comment] 2018-05-21 19:29
This is a duplicate of e.g. #2471 and #2422, and at the time we didn't expect to support inputs inside of menus.

Since we now have ongoing work to redesign menu with a more general-purpose scope, we'll go ahead and track this one to make sure we cover it in the redesign.

**Comment by thatcherkins** [comment] 2018-05-21 20:35
Awesome, thanks man

**Closed** 2018-08-13 22:49 UTC
Labels: in-tracker
