### ISSUE TITLE
Ripple does not dissipate if radio is activated by clicking label instead of input

### ISSUE THREAD

**Issue by ilikebits** [material-components/material-components-web#222] opened 2017-01-27 04:12 UTC
### What MDC-Web Version are you using?

Demo at https://material-components-web.appspot.com/radio.html

### What browser(s) is this bug affecting?

Chrome 55.0.2883.87

### What OS are you using?

Ubuntu 14.04 LTS

### What are the steps to reproduce the bug?

1. go to https://material-components-web.appspot.com/radio.html
2. click the text "radio 1" or "radio 2" under "JavaScript"

### What is the expected behavior?

The ripple dissipates, like unbounded ripples in https://material-components-web.appspot.com/ripple.html

### What is the actual behavior?

The ripple animation hangs.

**Comment by traviskaufman** [comment] 2017-01-30 16:28
Duplicate of #9

**Closed by traviskaufman** 2017-01-30 16:28 UTC
