### ISSUE TITLE
Framework wrappers should be in charge of listening to their framework events

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#3039] opened 2018-07-06 19:23 UTC
Most of our components have adapter methods which register (or deregister) to events. This is implemented in our vanilla components by listening to DOM events. But framework event systems are not 1 to 1 with DOM events. These frameworks end up adding listening logic to their component's constructor. 

For example, here is the MDC React Line Ripple listening to transition end event:
https://github.com/material-components/material-components-web-react/blob/master/packages/line-ripple/index.js#L85

So we should remove the register and deregister methods from our Adapters, and instead provide guidance on which events the wrapping component should wire up to which handleFoo methods on the Foundation

**Comment by kfranqueiro** [comment] 2018-07-09 21:22
Isn't this a duplicate of #2813?

**Comment by acdvorak** [comment] 2018-11-09 01:15
Duplicate of #2813

**Closed by acdvorak** 2018-11-09 01:15 UTC
Labels: icebox
