### ISSUE TITLE
Changing ripples size using compiled CSS & JS

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1066] opened 2017-08-03 08:41 UTC
Hey,
I was creating a web app when I came across a small problem: the ripple size is too big and cannot be changed.

I was searching in the READMEs for a way to to change its size but this could only be done using the foundation (which I'm not using). If there was a way to do it, it would really help me.

Thanks

**Comment by Garbee** [comment] 2017-08-03 12:45
> the ripple size is too big and cannot be changed.

In what case is it too large? Could you provide a [codepen](https://codepen.io) that shows the issue in action?

**Comment by touficbatache** [comment] 2017-08-03 12:56
https://codepen.io/anon/pen/YxGLQE @Garbee

**Comment by Garbee** [comment] 2017-08-03 13:04
Duplicate of your next issue ( #1067 ) it appears to me. The ripple sizes can't, and afaik shouldn't, be developer-modifiable. This is a bug in the toolbar that needs addressing.

**Comment by yeelan0319** [comment] 2017-08-03 18:47
@Garbee is right that we are not intended to make ripple size customizable. We will address the problem in toolbar in #1067 instead.

**Closed by yeelan0319** 2017-08-03 18:47 UTC
