### ISSUE TITLE
Temporary Drawer retracting animation broken on iOS 11.2

### ISSUE THREAD

**Issue by mjwwit** [material-components/material-components-web#1700] opened 2017-12-06 07:16 UTC
### What MDC-Web Version are you using?

`0.26.0`

### What browser(s) is this bug affecting?

Mobile Safari

### What OS are you using?

iOS 11.2

### What are the steps to reproduce the bug?

1. (On an iOS 11.2 device) go to the drawer demo page (https://material-components-web.appspot.com/drawer/temporary-drawer.html)
2. Open the temporary drawer
3. Close it.

### What is the expected behavior?

The drawer closes with a smooth animation.

### What is the actual behavior?

The drawer jerks back and forth and takes forever to completely close.

### Any other information you believe would be useful?

Has been tested on iPhone 8, iPhone 6S, iPod Touch 6th gen, iPad Air 2. The bug seems to only occur since the iOS 11.2 update.

**Comment by acdvorak** [comment] 2017-12-07 19:27
I was able to repro on iOS 11.2 Safari. Yikes!

![Screen recording of iOS 11.2 Safari](https://user-images.githubusercontent.com/409245/33734496-685dca14-db41-11e7-8ee5-24c68fda9d4c.gif)

**Comment by menelike** [comment] 2017-12-07 19:48
Does anyone have a clue how to temporarily fix this issue?

**Comment by mjwwit** [comment] 2017-12-07 19:50
@menelike, I disabled the close animation as a temporary workaround. Far from optimal, but better than the jerky drawer.

**Comment by menelike** [comment] 2017-12-07 20:17
@mjwwit Thanks a lot! 

I can confirm that removing `mdc-temporary-drawer--animating` from the classnames worked.

**Comment by kfranqueiro** [comment] 2017-12-15 14:57
Some additional helpful information was provided by @luspav on #1790.

**Comment by daniel-mf** [comment] 2017-12-18 16:51
@menelike I need a quick workaround, could you explain how to remove `mdc-temporary-drawer--animating`?
Thanks!

**Comment by canaanites** [comment] 2017-12-18 22:49
+1 I have the same issue.
I don't use the class `mdc-temporary-drawer--animating` I just use `mdc-temporary-drawer`

Any solution or work around for this issue?

**Comment by canaanites** [comment] 2018-01-02 16:01
+1

**Comment by MarcoTroost** [comment] 2018-01-03 09:27
Very recognizable.
I'm experiencing the same issue on my site ([https://www.droominfo.nl]).

**Comment by canaanites** [comment] 2018-01-04 03:42
@MarcoTroost Thank you! I confirm the above solution has fixed the issue.

I have added the above CSS in my HTML file right under the material components tag:
`<link rel="stylesheet"
          href="/node_modules/material-components-web/dist/material-components-web.css">`



> iPhone 6s
> iOS 11.2.1

**Comment by ruwaroshan** [comment] 2018-01-09 07:49
I have implemented the fix from @MarcoTroost and checked it as bellow and it is working fine. Thank you!

iPhone 6s 11.2.1
iPad 11.2.1
Mac Safari 11.0.2

**Comment by koba-ninkigumi** [comment] 2018-01-10 07:50
@MarcoTroost 0.28.0 seems to be unable to use that solution.

**Comment by jamesmfriedman** [comment] 2018-01-13 13:27
Confirming still an issue on 12.2

**Comment by BekStar7** [comment] 2018-01-18 09:36
Try add this snippet to your own scss:

``` 
.mdc-drawer--temporary  { 
  .mdc-drawer__drawer {
    transform: translateX(calc(-100vw - 20px));
    -webkit-transform: translateX(calc(-100vw - 20px));
  }
}
```
If you want drawer came out on the right, then you use it in html:
``` 
<aside class="mdc-drawer mdc-drawer--temporary" dir="rtl">
  <nav class="mdc-drawer__drawer" dir="ltr">
    ...
  </nav>
</aside>
```
and scss:
```
.mdc-drawer--temporary  { 
  .mdc-drawer__drawer {
    transform: translateX(calc(100vw + 20px));
    -webkit-transform: translateX(calc(100vw + 20px));
  }
}
```
P.S. `vw` doesn't support older browsers

**Comment by jordyboytjuh** [comment] 2018-01-26 10:32
+1

**Comment by edi2lopez** [comment] 2018-01-26 23:04
+1

**Comment by jamesmfriedman** [comment] 2018-01-28 14:14
Hello everyone, happy to report the issue is resolved on ios 11.2.5. Unfortunately anyone who doesn't upgrade will still have the issue so now it's a quesrion of:

Do we leave it as is and have people fix it in their own code bases as needed (probably)

Do we find a solution that works for both since people will likely be on ios11 for the next year. I don't have a way of testing but I want to know the exact versions this effects. To my knowledge it's only been 11.2.

**Comment by acdvorak** [comment] 2018-01-29 23:43
@BekStar7 Thanks for [the suggestion](https://github.com/material-components/material-components-web/issues/1700#issuecomment-358590431)!

Be aware that `100vw` != `100%` 🙂 

* `100%` = width of the `__drawer` element
* `100vw` = width of the viewport

Using `100vw` will cause the drawer enter/exit animations to be _much_ faster (especially on desktop).

**Comment by acdvorak** [comment] 2018-01-29 23:45
Thanks for the update @jamesmfriedman! Glad to hear this bug has been fixed by Apple.

I'm inclined to leave MDC Web as-is, and let folks fix this in their own code base if necessary. I'm not wild about leaving some users with a broken experience, but it's probably not worth spending time to fix a bug that increasingly few people will see.

However, if someone from the community is able to fix this with a one- or two-line PR, we would be more than happy to review it!

BTW - does anyone know if this issue also affects _desktop_ Safari? (And if so, which versions?) I'm not able to repro it in Safari 11.0.2 on macOS 10.13.2 (High Sierra).

**Comment by abhiomkar** [comment] 2019-10-18 16:07
This is fixed in new Drawer version.

**Closed by abhiomkar** 2019-10-18 16:07 UTC
Labels: backlog, bug
