### ISSUE TITLE
[mdc-elevation] DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by mashirozx** [material-components/material-components-web#7199] opened 2021-06-23 08:58 UTC
## Bug report

Dev server warning: 

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(math.max($backLum, $foreLum), math.min($backLum, $foreLum))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
49 │   @return math.max($backLum, $foreLum) / math.min($backLum, $foreLum);
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@material/theme/_theme-color.scss 49:11   contrast()
    node_modules/@material/theme/_theme-color.scss 60:19   tone()
    node_modules/@material/theme/_theme-color.scss 73:14   contrast-tone()
    node_modules/@material/theme/_theme-color.scss 115:17  @use
    node_modules/@material/theme/_theme.scss 35:1          @use
    node_modules/@material/elevation/_elevation.scss 29:1  @use
    node_modules/@material/elevation/styles.scss 23:1      @import
    src/styles/index.scss 2:9                              @import
    src/App.vue 2:9                                        root stylesheet
```

### Steps to reproduce
1. In a Vite CLI vue project
2. `@import '@material/elevation/styles';`
3. Dev server throw this warning

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | "@material/elevation": "^11.0.0",|
| Browser          |
| Operating System |

### Additional context

"sass": "^1.35.1",
"sass-loader": "^12.1.0",
"vite": "^2.3.8",

node: v14.17.1

**Comment by mashirozx** [comment] 2021-06-23 09:04
This might be relative https://github.com/sass/sass/issues/3065

**Comment by mashirozx** [comment] 2021-06-27 02:21
Not sure if it is fixed in #7158 ?

**Comment by johnpryan** [comment] 2021-06-29 16:49
I think this is a duplicate of #7143

**Comment by joyzhong** [comment] 2021-07-14 20:20
Closing as a duplicate of #7143.

**Closed** 2021-07-14 20:20 UTC
Labels: bug
