### ISSUE TITLE
 Ripple stay onMouseOut

### ISSUE THREAD

**Issue by shawnthye** [material-components/material-components-web#1581] opened 2017-11-13 00:36 UTC
### What MDC-Web Version are you using?

> @material/ripple@0.24.0

### What are the steps to reproduce the bug?
Click and hold and move the mouse pointer away from ripple.

### Comment
Hi Guys,
I am using `MDCRippleFoundation`

Is there a way to add a extra event(e.g `mouseout`) to deactivate the ripple effect???

**Comment by anton-kachurin** [comment] 2017-11-13 02:26
This is a very old bug #196

**Comment by shawnthye** [comment] 2017-11-13 03:11
Hi @anton-kachurin is there a temporary work around for this?

**Comment by anton-kachurin** [comment] 2017-11-13 03:23
The source code for the component changed a lot since the last time I've looked at that issue but the central idea is still the same, I think. You can set event listeners for `mousedown`, `mouseup`, and `mouseleave` events for an element.

If `mouseleave` happens after `mouseup` then it's a normal click and no actions should be taken.
If `mouseleave` happens after `mousedown` then the user decided not to click be element and the class that renders the ripple as "activated" must be removed.

**Comment by amsheehan** [comment] 2017-11-13 21:11
This is indeed a duplicate of a very old (in the 100's!) bug. We're on it, thank you for everyone's patience.

**Closed by amsheehan** 2017-11-13 21:11 UTC

**Comment by shawnthye** [comment] 2017-11-16 00:05
@anton-kachurin ,base on #1124 @mpiroc suggested, below workaround are good to go!!!
```
        registerInteractionHandler: (evtType, handler) => {
            const target = evtType === 'mouseup' || evtType === 'pointerup' ? window : this.surface;
            target.addEventListener(evtType, handler, util.applyPassive());
        },
        deregisterInteractionHandler: (evtType, handler) => {
            const target = evtType === 'mouseup' || evtType === 'pointerup' ? window : this.surface;
            target.removeEventListener(evtType, handler, util.applyPassive());
        },
```
