### ISSUE TITLE
[mdc-select] Select menu is cutoff by parent containers overflow hidden

### ISSUE THREAD

**Issue by desean1625** [material-components/material-components-web#5837] opened 2020-04-17 23:12 UTC
## Bug report
When upgrading from 3.x to ^4 mdc-select menu is appended to the container. This causes issues when a parent is set to overflow hidden because the menu cannot be hoisted to the body. mdc-select__native-control did not have this issue.

### Actual behavior
menu is cutoff by overflow

### Expected behavior
ability to see the menu

### Possible solution
Add option to allow hoisting to body, or return back to the native control.

**Comment by allan-chen** [comment] 2020-04-23 01:56
Duplicate of #5590

**Closed by allan-chen** 2020-04-23 01:56 UTC
Labels: bug
