### ISSUE TITLE
MDCSimpleMenu has no support for menu item icons

### ISSUE THREAD

**Issue by kmmbvnr** [material-components/material-components-web#1845] opened 2018-01-02 11:08 UTC
### What MDC-Web Version are you using?

lastest (codepen)

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

Go to codepen, click on the icon of the menu item
https://codepen.io/kmmbvnr/pen/eyReGv

### What is the expected behavior?

Menu closed, 'MDCSimpleMenu:selected' event fired

### What is the actual behavior?

The menu stays open, no event fired.

### Any other information you believe would be useful?

The issue that the foundation class assumes that menu item could contain only text - https://github.com/material-components/material-components-web/blob/a9e48682bf28f7ccfde9fdf79a97a2ecef8affbc/packages/mdc-menu/simple/foundation.js#L387L389

**Comment by aaronhudon** [comment] 2018-01-04 19:34
You sure?
What's wrong with just using the list items per-their spec.

E.g. https://codepen.io/aaronhudon/pen/Lezxby

**Comment by acdvorak** [comment] 2018-01-05 00:01
Thanks for taking the time to report this!

Luckily, there's already an open PR to fix it: #1756

What we really need, however, is a more general-purpose solution that uses common, shared code to solve this sort of problem in every component [_once and for all_](https://i.imgur.com/1Ehdy5x.jpg).

**Comment by acdvorak** [comment] 2018-01-05 00:03
Duplicate of #1747

**Comment by acdvorak** [comment] 2018-01-05 00:12
Oops! Just kidding, #1747 is a separate issue.

**Comment by moog16** [comment] 2018-06-29 23:05
SimpleMenu is no longer a component. Also not an issue anymore with the new menu. Updated with the new menu: https://codepen.io/anon/pen/VdqgaP?editors=1010

**Comment by williamernest** [comment] 2018-07-02 20:00
Reopened for tracking until the new menu feature branch is merged into master (0.38.0 or 0.39.0)

**Closed** 2018-08-13 22:49 UTC
Labels: bug, in-tracker
