### ISSUE TITLE
mdc-textfield bare component not building, error within mdc-notched-outline function

### ISSUE THREAD

**Issue by IvaWonderbush** [material-components/material-components-web#4038] opened 2018-11-02 12:46 UTC
### What MDC Web Version are you using?
Uh, this should suffice:
```
"@material/textfield": {
      "version": "0.41.0",
      "resolved": "https://registry.npmjs.org/@material/textfield/-/textfield-0.41.0.tgz",
      "integrity": "sha512-kJ52W2gxOS2xfpreVhvHQ1u3UkiDl58duw9HkhEkK5Oi1bSDOtbnlWy0pGTOiAma5ZQgetPNgoa+T0zMBptfnw==",
      "requires": {
        "@material/animation": "^0.41.0",
        "@material/base": "^0.41.0",
        "@material/floating-label": "^0.41.0",
        "@material/line-ripple": "^0.41.0",
        "@material/notched-outline": "^0.41.0",
        "@material/ripple": "^0.41.0",
        "@material/rtl": "^0.40.1",
        "@material/shape": "^0.41.0",
        "@material/theme": "^0.41.0",
        "@material/typography": "^0.41.0"
      },
      "dependencies": {
        "@material/shape": {
          "version": "0.41.0",
          "resolved": "https://registry.npmjs.org/@material/shape/-/shape-0.41.0.tgz",
          "integrity": "sha512-k1K3CjOVxclfb/0r28cOa2oJpP7QMA2fP0SOS3Vh8ale5Q2jkaHTL60KX8VkHvV6rMqShpXW+60gPjoz5XRbDQ=="
        }
      }
    },
```

### What OS are you using?

Windows 10 Home

### What are the steps to reproduce the bug?

- Setup Webpack 4
- `npm install @material/textfield`
- `@import "~@material/textfield/mdc-text-field";`
- `npm run dev`

### What is the expected behavior?

It should build.

### What is the actual behavior?

```
ERROR in ./resources/builder/assets/sass/main.scss (./node_modules/css-loader!./node_
modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--5-4!./resources
/builder/assets/sass/main.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    undefined
                           ^
          "12px-mdc-shape-prop-value(small)-1.2" is not a number for `max'
          in node_modules\@material\notched-outline\_functions.scss (line 33, column 25)
```

### Any other information you believe would be useful?

Most other components work fine. In case you are wondering, here is my Webpack config:

```
const path = require('path');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    entry: './resources/builder/assets/index.js',
    output: {
        filename: 'main.js',
        path: path.resolve(__dirname, './public/assets'),
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    'cache-loader',
                    'babel-loader',
                    'eslint-loader',
                ],
            },
            {
                test: /\.(sa|sc|c)ss$/,
                use: [{
                    loader: 'style-loader',
                }, {
                    loader: MiniCssExtractPlugin.loader,
                }, {
                    loader: 'css-loader',
                }, {
                    loader: 'postcss-loader',
                }, {
                    loader: 'sass-loader',
                    options: {
                        includePaths: ['./node_modules'],
                    },
                }],
            },
            {
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: '$',
                }],
            },
        ],
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
        }),
        new MiniCssExtractPlugin({
            filename: '[name].css',
            chunkFilename: '[id].css',
        }),
    ],
};

```

**Comment by jvv8** [comment] 2018-11-02 16:02
I have the same error message, but for me I was able to build the mdc-textfield and notched outlines worked fine.  Then I tried to import @material/select/mdc-select, resulting with the same error message:
` Module build failed: 
  $leadingStrokeLength: max(0, $mdc-notched-outline-min-leading-stroke-edge-position - $cornerSize - 1.2);
                       ^
"12px-mdc-shape-prop-value(medium)-1.2" is not a number for 'max'
      in node_modules/@material/notched-outline/_functions.scss (line 33, column 25)
`

**Comment by kfranqueiro** [comment] 2018-11-02 17:16
Huh. I couldn't reproduce this directly by installing textfield and select, then running `node-sass` over a file that imports them.

The way the error reads makes it seem like it's not recognizing the `mdc-shape-prop-value` mixin, but that's in `@material/shape/functions` which both text field's and select's `mixins` files import.

* Can you confirm that `mdc-shape` also ended up installed?
* Can you run `npm ls | grep material` to see what it outputs?
* Could one of you provide a minimal repo / gist with a package.json + webpack config that reproduces this?

**Comment by IvaWonderbush** [comment] 2018-11-05 15:30
By creating a minimal setup I found that another material package(s) is/are crippling things. I'm looking into the order of imports and the packages specifically. Will let you know once I found out what's going wrong.

**Comment by MonikaCholewa** [comment] 2018-11-05 15:31
I have also the same error message, and i found the mistake. There is incorrect name of function in line 129 in node_modules\@material\select\_mixins.scss file. I have mdc-shape-prop-value($resolved-radius); but it should be mdc-shape-prop-value_($resolved-radius);

**Comment by IvaWonderbush** [comment] 2018-11-05 15:42
```
"dependencies": {
    "@material/textfield": "^0.41.0",
    "@material/shape": "^0.40.1"
  }
```
@material/shape is what is bugging things, specifically (thanks to @MonikaCholewa) it is the `mdc-shape-prop-value_` naming. The funny thing is, the function has an underscore at __functions.scss:109_ and removing it fixes the issue.

**Comment by kfranqueiro** [comment] 2018-11-05 15:59
It looks like there's a version mismatch to blame, then. The function in question was renamed in `@material/shape` 0.41.0, but your dependencies still show 0.40.1. If you install the latest version of shape to match, you should be fine.

Alternatively, if you run `npm ls` I'm guessing you'll notice nested installations of `@material/shape@0.41.0` under select and textfield. If you use the custom importer detailed in our [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#appendix-configuring-a-sass-importer-for-nested-node_modules) instead of just `includePaths`, that will probably work even with the mismatched versions.

**Comment by IvaWonderbush** [comment] 2018-11-06 12:16
Ah, looks like I had more mismatched versions. Fixed them all, nothing to worry. Will pay better attention in the future. Thanks a bunch!

**Comment by kfranqueiro** [comment] 2018-11-08 21:35
Glad to hear that worked. I'll close this since it's resolved now.

**Closed by kfranqueiro** 2018-11-08 21:35 UTC

**Comment by jvv8** [comment] 2018-11-09 02:47
Indeed, worked for me too.  Although just days apart, there were a mismatched versions causing the issue.  Solved with npm uninstall @material/'package' then npm install @material/'package' --save
All is well.
