### ISSUE TITLE
[mdc-select] Can't jump to option by typing a letter / letters

### ISSUE THREAD

**Issue by brycekirk** [material-components/material-components-web#5817] opened 2020-04-15 18:03 UTC
Given that there's a strong focus on usability, there should be the option to type a letter or a few letters to jump to an option, as default select elements work

**Comment by asyncLiz** [comment] 2020-04-15 18:05
Duplicate of #5705

**Closed by asyncLiz** 2020-04-15 18:05 UTC

**Comment by steven-cole-elliott** [comment] 2020-12-02 18:04
Hi 👋 

I've looked at #5705 , and while that is useful and helpful, is there a supported way to automatically open and then select the matching option in response to keyboard input when the MDCSelect has focus, without having to first manually open the MDCSelect in order to get typeahead support?

It seems that native HTML select elements support this behavior.  I've found myself out of habit tabbing through fields, focusing an MDCSelect, only to start typing and have nothing happen until I deliberately open the MDCSelect with, e.g. hitting down arrow.

If I should submit a separate issue, I'm happy to do that, too.
