### ISSUE TITLE
mdc-button in Edge browser is colorless

### ISSUE THREAD

**Issue by Loggan08** [material-components/material-components-web#1102] opened 2017-08-09 13:04 UTC
Renders properly in Chrome and FF
![untitled](https://user-images.githubusercontent.com/7104301/29122868-0ea0ea8c-7d14-11e7-8a81-22181c55ded7.png)

**Comment by touficbatache** [comment] 2017-08-10 08:07
Hey, thanks for filing an issue. But please consider using the provided template to submit bugs / issues as it makes it more clear what the issue is, which browser is it affecting, which OS you're using, etc... so it can be tested and fixed as soon as possible.

**Comment by acdvorak** [comment] 2017-08-11 05:24
Definitely looks like a bug. I was able to repro it on our [button demo page](https://material-components-web.appspot.com/button.html) in Edge 15.

It's not just dark mode, either: all `--raised` buttons seem to lack any background color at all in Edge.

As @touficbatache suggested, in the future, please try to use the provided issue template and attach a CodePen (or in this case, a link to the public demo page). It will help us get to the bottom of the issue faster.

Thanks!

**Comment by RobJacobs** [comment] 2017-08-14 14:08
@acdvorak I think this has to do with when the global css variables are set/imported.  On the demo page, I used the dev tools to look at the 'Buttons - RAISED WITH PRIMARY' element - the computed tab revealed: 

![image](https://user-images.githubusercontent.com/4559806/29274769-f00c0f2c-80d6-11e7-8f11-76551d4b9df0.png)

For the background-color property, notice the .mdc-button--primary.mdc-button--raised: var(---mdc-theme-primary, #212121) from the assests/demo-styles.css.js is being overruled by the .mdc-button: transparent rule from the assets/material-components-web.css.js.

Odly enough, simply unchecking the top level background-color checkbox will cause the rule to evaluate correctly.  Rechecking will then apply the rules:

![image](https://user-images.githubusercontent.com/4559806/29275196-4bb16a9c-80d8-11e7-8dc1-99366deb1464.png)

Same applies to the button color rule.

**Comment by yeelan0319** [comment] 2017-08-14 20:19
@acdvorak @Loggan08 ,

This seems to be a Edge 15 only bug because its wrong implementation of pseudo element style. I will try to lock down this further.

**Comment by ctafield** [comment] 2017-08-15 08:40
FWIW, you can easily repro these with the demo page... https://material-components-web.appspot.com/button.html - especially with the raised / accent styles.

**Comment by RobJacobs** [comment] 2017-08-15 14:36
@yeelan0319 @acdvorak I was hoping PR #1113 would fix the problem, but no luck.

**Comment by kfranqueiro** [comment] 2017-09-27 17:55
I've done some more investigation on this, and it seems like probably another issue with Edge, CSS variables, and pseudo-elements - but in this case, the CSS variable that trips it is applied to the root element, not the pseudo-elements.

I've been looking at FAB which has a similar issue (it uses secondary for its background), and if I switch its background-color to use a color literal rather than a CSS variable, the color renders correctly. (Alternatively, if I remove the ripple styles that apply background-colors to the pseudo-elements, the issue also goes away; interestingly, those values don't even reference CSS variables in the particular case I'm looking at.)

I suspect this may boil down to us needing to exclude at least some usages of CSS variables from Edge until they sort out their own browser. This unfortunately still happens even on Edge 16 in the modern.ie Win10 preview VM. My biggest concern in working around this is how much CSS I'll end up needing to add, which would affect load times in all browsers.

**Comment by kfranqueiro** [comment] 2017-09-29 20:56
This was fixed via #1364 which was merged manually.

**Closed by kfranqueiro** 2017-09-29 20:56 UTC
Labels: bug, in-tracker
