### ISSUE TITLE
Ripple in demo changed to weird behavior.

### ISSUE THREAD

**Issue by iamdubx** [material-components/material-components-web#1185] opened 2017-08-25 00:27 UTC
I notice that ripple effect is wierd when I am from Android device. Is this is wanted behavior? I don't really like it. Is there an option to use same ripple as on desktop?

**Comment by foreggs** [comment] 2017-08-25 09:08
Same on desktop.
![broken-ripple-mdc](https://user-images.githubusercontent.com/30264244/29707482-514c5720-897d-11e7-857d-bc22fc5d971d.gif)

**Comment by iamdubx** [comment] 2017-08-25 09:44
You are right, it's just me notice this from mobile and thought that it's only related to device, since a day or two ago everything was working fine in demo. This is weird. I hope this is not intended behavior, it's awful.

**Comment by kfranqueiro** [comment] 2017-08-25 13:31
I believe this is a duplicate of #1184, which we've already identified the cause of and reverted in #1183. This was unfortunately present in 0.18.1; we're planning to release another hotfix today to address it. Thanks!

**Closed by kfranqueiro** 2017-08-25 13:31 UTC
