### ISSUE TITLE
[mdc-text-field] input not correctly aligned in Safari 13.1

### ISSUE THREAD

**Issue by strayer** [material-components/material-components-web#5879] opened 2020-05-01 09:17 UTC
## Bug report
After upgrading to textfield 6.0.0 the input in mdc-text-fields isn't aligned correctly anymore. It seems to fix itself after entering text and clicking the input.

### Steps to reproduce
1. Go to https://jsbin.com/sekemoyivi/2/edit?html,output in Safari
2. Click on the input field and enter text
3. See that the input field is centered and intersects with the label text
4. Click on the entered text, the alignment seems to fix itself

### Screenshots
![grafik](https://user-images.githubusercontent.com/310624/80795264-4a8af080-8b9c-11ea-9602-e96cdb3b13be.png)

![grafik](https://i.imgur.com/JAsH9dC.gif)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0
| Browser          | Safari Version 13.1 (15609.1.20.111.8) 
| Operating System | macOS 10.15.4 (19E287)

**Comment by asyncLiz** [comment] 2020-05-01 16:59
Thanks for the issue! It looks like a bug in webkit: https://bugs.webkit.org/show_bug.cgi?id=142968

We'll see if there's anything we can do to help speed along a fix and get a workaround in the meantime.

**Comment by MaximBalaganskiy** [comment] 2020-09-05 02:24
This is a serious regression. Any news?

**Comment by asyncLiz** [comment] 2020-09-08 18:39
We're currently working on an update to text field's layout that addresses this issue.

**Comment by robinsummerhill** [comment] 2020-10-16 19:41
As a workaround for now you can set the placeholder attribute of the input element to a single space. i.e.

`<input type="text" class="mdc-text-field__input" aria-labelledby="my-label" placeholder=" ">`

**Comment by amorey** [comment] 2021-01-15 18:32
@asyncLiz The Safari bug is ~6 years old so it doesn't look like it will be fixed on their end. Any updates on when the new text field layout will be ready?

**Comment by asyncLiz** [comment] 2021-01-15 21:15
My work from last Fall was put on hold due to CDS, but I've started implementing the text field layout update, so soon! :)

**Comment by amorey** [comment] 2021-01-16 11:11
That's great! Let us know if we can help with testing or anything else.

Also - do you happen to know why the "full width" variant was removed between v7.0.0 and v8.0.0?

**Comment by asyncLiz** [comment] 2021-01-19 18:48
"Full width" added styles that were not part of the spec (such as removing horizontal padding). You can achieve full width by adding `width: 100%` to the text field.

**Comment by asyncLiz** [comment] 2022-06-17 18:57
This issue has been fixed in the Material 3 text field.

**Closed by asyncLiz** 2022-06-17 18:57 UTC
Labels: bug
