### ISSUE TITLE
MDCSwitch compilation warnings

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#7386] opened 2021-09-11 10:40 UTC
Hi, using material version 12 with the new switch, I get the following compilation warnings when building a theme:

```
2>> sass --no-color --unicode --style=compressed --load-path=node_modules --no-source-map Styles/material-default-theme.scss wwwroot/css/material-default-theme.min.css
2>
2>EXEC : warning : $level must be between 0 and 24; received ''
2>    @material\elevation\_elevation-theme.scss 225:5         -shadow()
2>    @material\elevation\_elevation-theme.scss 457:20        resolver()
2>    @material\tokens\_resolvers.scss 5:11                   -material-elevation()
2>    @material\elevation\_elevation-theme.scss 417:21        with-resolver()
2>    node_modules\@material\switch\_switch-theme.scss 376:5  -set-handle-elevation()
2>    node_modules\@material\switch\_switch-theme.scss 358:5  @content
2>    @material\theme\_state.scss 231:5                       @content
2>    @material\theme\_state.scss 253:5                       @content
2>    @material\theme\_state.scss 747:7                       -selector()
2>    @material\theme\_state.scss 252:3                       enabled()
2>    @material\theme\_state.scss 230:3                       default()
2>    node_modules\@material\switch\_switch-theme.scss 357:3  -handle-elevation()
2>    node_modules\@material\switch\_switch-theme.scss 191:3  theme-styles()
2>    @material\switch\styles.scss 38:5                       @content
2>    @material\dom\_dom.scss 93:7                            forced-colors-mode()
2>    @material\switch\styles.scss 36:1                       @use
2>    Styles\material-components-web.scss 54:1                @use
2>    Styles\material-default-theme.scss 9:1                  root stylesheet
2>
2>EXEC : warning : $level must be between 0 and 24; received ''
2>    @material\elevation\_elevation-theme.scss 225:5         -shadow()
2>    @material\elevation\_elevation-theme.scss 457:20        resolver()
2>    @material\tokens\_resolvers.scss 5:11                   -material-elevation()
2>    @material\elevation\_elevation-theme.scss 417:21        with-resolver()
2>    node_modules\@material\switch\_switch-theme.scss 376:5  -set-handle-elevation()
2>    node_modules\@material\switch\_switch-theme.scss 366:5  @content
2>    @material\theme\_state.scss 275:5                       @content
2>    @material\theme\_state.scss 747:7                       -selector()
2>    @material\theme\_state.scss 274:3                       disabled()
2>    node_modules\@material\switch\_switch-theme.scss 365:3  -handle-elevation()
2>    node_modules\@material\switch\_switch-theme.scss 191:3  theme-styles()
2>    @material\switch\styles.scss 38:5                       @content
2>    @material\dom\_dom.scss 93:7                            forced-colors-mode()
2>    @material\switch\styles.scss 36:1                       @use
2>    Styles\material-components-web.scss 54:1                @use
2>    Styles\material-default-theme.scss 9:1                  root stylesheet
```

Note that line 54 of my file `Styles\material-components-web.scss` is:

```sass
@use '@material/switch/styles';
```

**Comment by asyncLiz** [comment] 2021-09-13 19:08
Duplicate of #7302 and #7240

**Closed by asyncLiz** 2021-09-13 19:08 UTC
Labels: bug
