### ISSUE TITLE
MDC-select in a dialog renders its menu in the wrong location

### ISSUE THREAD

**Issue by pgbross** [material-components/material-components-web#844] opened 2017-06-21 09:43 UTC
### What MDC-Web Version are you using?

> 0.13.0

### What browser(s) is this bug affecting?

> Version 60.0.3112.32 (Official Build) beta (64-bit)
### What OS are you using?

> Fedora 26 Beta

### What are the steps to reproduce the bug?

> 1. Create a page with an MDC-Dialog that contains an MDC-Select
> 2. Use appropriate javascript to create/attach components to the UI.
> 3. Open() the dialog.
> 4. Pick an item from the select list.
> 5. Observe the list, which is rendered by the select as a simple menu, is incorrectly positioned.
>
See [Codepen dialog select position](https://codepen.io/pgbross/pen/GEmwKr) for an illustration if the fault.

### What is the expected behavior?

> The select list should be rendered where the selected text is placed as when rendered on a normal page.

### What is the actual behavior?

> The select list is rendered out of position, often near the centre at bottom of page.

### Any other information you believe would be useful?
The simple menu underlying the select list is positioned using css `position:  fixed` semantics with the calculations relative to the viewport. However if an ancestor, such as the `.mdc-dialog__surface` has a transform property set to something different from none then this ancestor is used as the container instead of the viewport. [See mdn CSS position](https://developer.mozilla.org/en/docs/Web/CSS/position) docs.

Note this fault is not limited to within a dialog but wherever there is an ancestor with a transform property.

**Comment by bmihelac** [comment] 2017-06-21 10:12
I believe this is duplicate of 

https://github.com/material-components/material-components-web/issues/719

**Comment by pgbross** [comment] 2017-06-21 10:46
Oops sorry, yes this does appear to be a duplicate. 

Maybe the information on `position: fixed` is helpful, and the fact the issue is not limited to dialogs but is just a common place it shows up.

**Comment by bmihelac** [comment] 2017-06-21 10:52
good catch, should I copy this to original issue or you would add it as a comment?

**Comment by pgbross** [comment] 2017-06-21 10:56
Closed as duplicate of #719. Added comment to original issue.

**Closed** 2017-06-21 10:56 UTC

**Comment by bmihelac** [comment] 2017-06-21 10:57
@pgbross thanks!
