### ISSUE TITLE
[MDCDialog] Default button isn't focused correctly

### ISSUE THREAD

**Issue by CiriousJoker** [material-components/material-components-web#4074] opened 2018-11-10 23:21 UTC
### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Chrome 70

### What OS are you using?

> Arch Linux

### What are the steps to reproduce the bug?

See this minimal working example on codepen:
https://codepen.io/ciriousjoker/pen/mQrEmW

### What is the expected behavior?

> The YES button should have the highlighted background since it's set to be the default action.

### What is the actual behavior?

> The NO button is highlighted.

**Comment by kfranqueiro** [comment] 2018-11-12 01:56
This is behaving as intended. The default action is intended to respond to enter keypress, but not receive initial focus. This makes it possible to have e.g. a confirmation dialog with a text input or radio buttons, where you can quickly enter/change the value and press enter to submit the dialog.

I don't think I explained this well enough in the readme though, so we can track this to improve the documentation on this feature.

**Comment by CiriousJoker** [comment] 2018-11-12 09:56
But isn't that really unintuitive?

Imagine you open a dialog with two buttons and you press enter right after it opened:
What does the user expect to happen? Sure, the yes button might be the confirming button, but the no button was highlighted, so what happens?

I get the problem with the other focus-grabbing elements inside the dialog though.

Is is possible that you add some way of setting the initial button to focus by default or focus none at all?

If not, how can I force my way through this problem? Remove the background-focused class on open? Simulate a tab press on the first open?

Giving focus via element.focus() doesn't work, sadly..

**Comment by chacalounet** [comment] 2019-02-10 00:36
how to disable focus trap shit ?

**Comment by chacalounet** [comment] 2019-02-10 01:11
![sans titre](https://user-images.githubusercontent.com/34717743/52528191-6aed3780-2cd8-11e9-985e-4a4b22a9d8d7.png)

since 0.41.2, when i m open a dialog modal, this causing randomly an real infinite loop and crash my browser, i dont  know why when dialog is open the button on the drawer is focused creating this loop.
sorry for my bad english

**Comment by abhiomkar** [comment] 2019-09-13 20:46
Fixed in #4719

**Closed by abhiomkar** 2019-09-13 20:46 UTC
Labels: backlog
