### ISSUE TITLE
Button ripple wash sometimes has 1px gap

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#1753] opened 2017-12-13 10:13 UTC
### What MDC-Web Version are you using?

0.27.0

### What browser(s) is this bug affecting?

Chrome only (tested in v62) - Firefox and Safari seem unaffected

### What OS are you using?

macOS Sierra 10.12.6

### What are the steps to reproduce the bug?

1. View the [Button demo page](https://material-components-web.appspot.com/button.html) in Chrome
2. Mouse down (but not up) on a filled or stroked button ("Compact", "Secondary", and "Icon" seem to trigger the bug most reliably)

### What is the expected behavior?

The ripple wash should cover the entire container.

### What is the actual behavior?

There is a 1px gap on one or both sides of the ripple wash.

### Any other information you believe would be useful?

![Screenshot of ripple gaps](https://user-images.githubusercontent.com/409245/33933366-59306912-dfaa-11e7-9cf1-b8c75aa85f52.png)

**Comment by kfranqueiro** [comment] 2018-01-02 23:25
I've only been able to repro this in Chrome as well. If I remove `overflow: hidden` then the `::after` pseudo-element clearly spans beyond the boundaries of the button's surface, and if I change the text in the button the issue disappears, so I'm inclined to think there's some miscalculation going on internally in Chrome.

**Comment by kfranqueiro** [comment] 2018-01-03 16:10
Finally managed a [reduced test case](https://codepen.io/kfranqueiro/pen/xpLrLL). The second element demonstrates the issue.

If you remove the surface's `border-radius` or the pseudo-element's `will-change: transform`, the issue goes away.

Safari doesn't seem to exhibit the issue, only Chrome.

**Comment by kfranqueiro** [comment] 2018-01-04 22:25
Unfortunately, the performance issue in #1665 will re-emerge if we remove `will-change` outright. #1872 is moving it from the pseudo-elements to the ripple surface itself, but this issue is still present then. Even when removed altogether, the issue is still noticeable specifically while the ripple is transitioning its scale, but then the issue goes away once it's scaled in fully.

I'm thinking of putting a few more examples in my test case, but then I think I need to file a bug with Chrome.

**Comment by kfranqueiro** [comment] 2018-01-05 21:44
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=799591. While testing for filing this bug, I realized this _only_ happens on OS X, not Windows or Linux, which perhaps reduces its effect, but it's still noticeable and awkward on OS X.

**Comment by CyanoFresh** [comment] 2018-01-20 14:41
Almost same (other side) on the Windows 10

![](https://image.prntscr.com/image/6JUobxTVSsWAdLlVrYysLw.jpeg)

**Comment by kfranqueiro** [comment] 2018-04-27 21:37
This has been fixed in Chrome v67, so it will Just Work when that releases to stable in ~6 weeks. 🎉 

Closing this, since there's nothing for MDC Web to do.

**Closed by kfranqueiro** 2018-04-27 21:37 UTC
Labels: bug, in-tracker
