### ISSUE TITLE
Incorrect example on Material Design page

### ISSUE THREAD

**Issue by pwatrous** [material-components/material-components-web#2947] opened 2018-06-18 14:06 UTC
## Bug
![screen shot 2018-06-18 at 10 01 11 am](https://user-images.githubusercontent.com/10429595/41540825-f8edbd66-72de-11e8-9943-2c7f93c81eea.png)

My apologies if this is the wrong place to file this issue. I looked pretty extensively and this repo seemed like my best option. As seen in the screenshot, the example for "Write in the present tense" uses the example for "Use numerals". I'd be able to submit a PR if you could point me in the right direction to do so. Thanks!

**Comment by kfranqueiro** [comment] 2018-06-18 14:50
Which page exactly did you encounter this on?

There should be a Feedback link at the bottom of each page in material.io that you can report issues from. If you have trouble finding that or getting it to work, I should be able to forward this to the site team.

**Comment by pwatrous** [comment] 2018-06-18 15:09
my apologies! I could've sworn I included the link but I must've forgotten. It's located at: https://material.io/design/communication/writing.html#

Just submitted feedback. Thanks for the help :)

**Comment by kfranqueiro** [comment] 2018-06-18 18:35
Thanks. I've confirmed that the site feedback was received, so I'll close this since it's now tracked elsewhere.

**Closed by kfranqueiro** 2018-06-18 18:35 UTC
