### ISSUE TITLE
[Nav] Navigation not opening when button pressed

### ISSUE THREAD

**Issue by MaryWeeb** [material-components/material-components-web#6714] opened 2020-12-24 10:35 UTC
## Bug report
I'm currently migrating from MDL, and while migrating a drawer to navigation and header to top app bar, both taken from the examples, pressing the icon does not open the menu.

### Steps to reproduce
1. Add the HTML for a nav element (modal version) and a top app bar element
2. Click the icon in your browser
3. Nothing happens

### Actual behavior
The navigation modal does not slide in

### Expected behavior
The navigation modal slides in

### Screenshots
The icon, same as the example
![Screenshot_20201224_113326](https://user-images.githubusercontent.com/16361449/103083122-e8c04080-45db-11eb-887c-3cdb63889733.png)
Navigation after removing display:none in inspector
![Screenshot_20201224_113429](https://user-images.githubusercontent.com/16361449/103083164-07263c00-45dc-11eb-8b6a-376558437260.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | latest
| Browser          | chromium latest
| Operating System | arch linux

**Comment by asyncLiz** [comment] 2020-12-28 20:43
Can you please provide a jsbin or glitch showing your code and what is not working?

Have you followed the [drawer's readme for usage with top app bar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#usage-with-top-app-bar), including the JS to toggle the drawer when the navigation button is clicked?

```js
import {MDCTopAppBar} from "@material/top-app-bar";
const topAppBar = MDCTopAppBar.attachTo(document.getElementById('app-bar'));
topAppBar.setScrollTarget(document.getElementById('main-content'));
topAppBar.listen('MDCTopAppBar:nav', () => {
  drawer.open = !drawer.open;
});
```

**Comment by MaryWeeb** [comment] 2020-12-29 08:16
I initially assumed MDC worked just like MDL where it would automatically connect, and the JS was optional for cases like React.

Adding the JS snippets results in some errors:
```
Uncaught SyntaxError: Cannot use import statement outside a module
```

**Comment by asyncLiz** [comment] 2020-12-29 19:37
I'd recommend reading through the [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) to set up your environment for development. JS scripts need to be compiled from bare ES modules into a bundle using a build system such as webpack or rollup.

Alternatively, in the same getting started guide there's a "quick start" at the top with a pre-built bundle containing all of the elements' JS and CSS that you can load from a CDN. The [docs](https://github.com/material-components/material-components-web/blob/master/docs/) folder has many useful guides, such as [how to import JS](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md) for various distributions, including the global CDN.

I'm going to go ahead and close this for now, since it appears that the navigation drawer is working as intended.

**Closed by asyncLiz** 2020-12-29 19:37 UTC
Labels: bug, needs-response
