### ISSUE TITLE
mdc-menu--open out of place on mdc-dialog

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#2369] opened 2018-03-09 03:05 UTC
Hello Team,

Using an mdc-select component on a dialog will render the list out of place. I have created this pen to reproduce the issue:

[https://codepen.io/linear/pen/YazeQx](https://codepen.io/linear/pen/YazeQx)

Thanks,

**Comment by patrickrodee** [comment] 2018-03-12 18:32
Thanks for submitting an issue.

This is a duplicate of #719 so I'm going to close it.

**Closed by patrickrodee** 2018-03-12 18:32 UTC
