### ISSUE TITLE
MDCSlider: layout issues

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#4365] opened 2019-02-07 07:30 UTC
MDCSlider's behavior strongly depends on DOM element dimensions and position. To continue working as expected, the `layout` function of MDCSlider should be called every time when some DOM properties of slider or its parent element(s) changes. As I can see, MDCSlider's foundation relies on `resize` event to handle DOM size changes. But it is not very reliable method as practice shows.
On [MDCSlider demo page](https://material-components.github.io/material-components-web-catalog/#/component/slider) revealing the navigation drawer breaks the behavior of each slider on the page. As I can see, this happens due to sliders parent element size change (additional margin is applied to the left side of container when the drawer appears). Of course, the `resize` event is not fired in this case, and so slider's `layout` method is not called.

Is this a bug or such cases should be handled explicitly by the user (e.g. one should call `layout` function manually when the drawer is opened)?

### What MDC Web Version are you using?
0.44.0

### What browser(s) is this bug affecting?
Firefox 64.0.2, Chromium 71.0.3578.98

> ### What OS are you using?
Fedora 28

**Comment by monstasat** [comment] 2019-02-07 08:12
Another issue of MDCSlider component is that it does not update the `data-step` attribute of the host DOM node when the step is changed via `setStep` method.
I can open a separate issue for this if needed.

**Comment by monstasat** [comment] 2019-02-08 07:42
@kfranqueiro , thank you for the explanation.
There is a [polyfill](https://github.com/que-etc/resize-observer-polyfill) for `ResizeObserver` based on `MutationObserver` API, which is supported by the majority of browsers, so I am tending to use it to capture the cases where `resize` event is not applicable.

Regarding `data-step` attribute, for me this is not a problem. I just though that it will be more consistent to keep slider's JS object and DOM node in sync.

**Comment by kfranqueiro** [comment] 2019-02-13 15:49
I think given the use-case for the `data` attributes on Slider, keeping them in sync isn't necessary. These attributes basically exist as a convenience to initialize these values declaratively rather than JS - the typical case is to configure it one way or the other.

I think we can close this issue now since there's no further action necessary. Thanks for your input!

**Closed by kfranqueiro** 2019-02-13 15:49 UTC

**Comment by MaximBalaganskiy** [comment] 2020-07-15 23:27
A bit late, but for framework wrappers the problem is solved by overriding `rect_` private field with a getter which always gets a fresh bounding rect.
E.g.
```
import { MDCSliderFoundation } from '@material/slider';

export class MdcSliderFoundationAurelia extends MDCSliderFoundation {
  get rect_(): ClientRect {
    return this.adapter.computeBoundingRect();
  }

  set rect_(value: ClientRect) {

  }
}
```
