### ISSUE TITLE
[MDCSelect] wrong behavior when select list element with js and list has empty values 

### ISSUE THREAD

**Issue by DarkSilence** [material-components/material-components-web#5714] opened 2020-03-15 11:18 UTC
## Bug report

After setValue('element') call floating label stays in place and overlaps the selected element.

This only happens if the first element in a list has empty value (data-value="").

### Steps to reproduce

https://codepen.io/RomanPaulov/pen/XWbqbZg

1. Click „Show selected index“.
2. Click „Set vegetables“.
3. Click „Show selected index“ again.

### Actual behavior

1. When clicking „Show selected index“ component says -1.
2. When clicking „Set vegetables“ vegetables item is selected but floating label stays in place and both overlap each other.
3. When clicking „Show selected index“ next time component still says -1.

### Expected behavior

1. I think selected index should be 0.
2. Floating label should be above the selected value.
3. I think selected index should be 2.

### Screenshots

<img width="340" alt="veg" src="https://user-images.githubusercontent.com/1132639/76700338-1a20ed00-66e9-11ea-8f2d-325b1bc8f2db.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.1.0
| Browser          | Chrome Version 80.0.3987.132 (Official Build) (64-bit)
| Operating System | Windows 7 x64

### Possible solution

This behavior caused by this line I think https://github.com/material-components/material-components-web/blob/cd53918f123ff7c2e73f033c4550c7b36c345f91/packages/mdc-select/foundation.ts#L136

When an item with empty value is selected previouslySelectedIndex is equal to -1 and code which clears selected styles won't fire. Which leads to incorrect behavior of getSelectedMenuItem here

https://github.com/material-components/material-components-web/blob/cd53918f123ff7c2e73f033c4550c7b36c345f91/packages/mdc-select/component.ts#L292

which picks first list item with mdc-list-item--selected class is present, which will be the first item.

**Comment by allan-chen** [comment] 2020-03-16 01:39
Hi Roman,

You're right regarding the cause - this also came up in the second issue described in #5646 - marking as duplicate of that issue for now. Please follow that issue for updates. Thanks!

**Closed by allan-chen** 2020-03-16 01:39 UTC
Labels: bug
