### ISSUE TITLE
Allow jquery objects?

### ISSUE THREAD

**Issue by applemonkey496** [material-components/material-components-web#6041] opened 2020-06-08 03:46 UTC
## Feature Request
Would it be possible to allow users to pass jquery elements to MDC components in JS? For example,
```js
const button = $('#button');
const ripple = new MDCRipple(button);
```
As opposed to:
```js
const ripple = new MDCRipple(document.querySelector('#button'));
```

### Proposed solution

When creating a new component, you could implement it using something like the following:
```js
if (element instanceof jQuery) {
  element = element[0];
}

// rest of operations ...
```

### Alternatives considered
You could pass some jquery element `el` but as `el[0]` instead of having Material do it for you, but I would argue it's aesthetically cleaner to have it integrated into the library.

**Comment by patrickrodee** [comment] 2020-06-09 00:02
Hey, thanks for filing this issue. Our components are library and framework agnostic. We provide no custom affordances for any external code such as Angular, React, Vue, or Polymer. Our support for jQuery is no different.

I'd recommend creating your own custom wrappers around the MDC-Web components. You could do something like the following:

```
function $MDCRipple(query) {
  const el = $(query);
  return new MDCRipple(el[0])
}
```

You can then use it easily:

```
const ripple = $MDCRipple('#button');
```

I'll close this as intended behavior.

**Closed** 2020-06-09 00:03 UTC
Labels: wontfix
