### ISSUE TITLE
MDCTextField (Outlined): Spacing between trailing icon and outline is 14px, should be 8.

### ISSUE THREAD

**Issue by aprigogin** [material-components/material-components-web#4148] opened 2018-12-05 21:46 UTC
According to https://material.io/design/components/text-fields.html#spec spacing between trailing icon and outline is 8px.

https://material-components.github.io/material-components-web-catalog/#/component/text-field has 14px.

FWIW: 8px in the spec might be wrong too, as it does not account for case when the trailing icon is actionable and would be producing circular ripple. Spacing in that case would need to be at least 12px.

**Comment by williamernest** [comment] 2018-12-07 18:01
I confirmed with Cortney that our component and spec are wrong. The new value is `12dp`. There are also outstanding questions regarding the right padding of the `input` without an icon being `16dp`. 

I'll update this issue when we get some assets to go off of.

**Comment by bonniezhou** [comment] 2019-01-24 22:33
Closing this issue since it's encompassed by #4294. 
Also confirmed with design that both the left and right padding without an icon is 16dp, which is implemented accurately.

**Closed by bonniezhou** 2019-01-24 22:33 UTC
Labels: icebox, needs-design-guidance
