### ISSUE TITLE
Problem with Material Select Component

### ISSUE THREAD

**Issue by omar2205** [material-components/material-components-web#3750] opened 2018-10-12 18:37 UTC
## Bugs
https://material-components.github.io/material-components-web-catalog/#/component/select

Shaped Outlined Select the Fruit label is off to the left
![](https://i.imgur.com/OrTmQ3T.png)

### What browser(s) is this bug affecting?

Chrome, latest (69.0.3497.100)

### What OS are you using?

Windows 10 - 64bit - 1809

### What are the steps to reproduce the bug?

> Visit https://material-components.github.io/material-components-web-catalog/#/component/select

### What is the expected behavior?

![](https://i.imgur.com/ygwSK6k.png)

### What is the actual behavior?

![](https://i.imgur.com/OrTmQ3T.png)

**Comment by abhiomkar** [comment] 2018-10-12 18:41
Thanks for reporting this issue @omar2205!

This is a duplicate of #3158

**Closed by abhiomkar** 2018-10-12 18:41 UTC
