### ISSUE TITLE
Polish and Ripples

### ISSUE THREAD

**Issue by philmaker1** [material-components/material-components-web#980] opened 2017-07-20 04:19 UTC
Perhaps some of the unpolished nature of MDC is a side effect of its modularity. But every button ought to have ripples by default. Toolbar buttons, dialog buttons, icon buttons, plain buttons, card buttons, FAB buttons. But they do not in MDC. And why not? Is it a modularity issue, a design issue, or a documentation issue?

**Comment by touficbatache** [comment] 2017-07-20 10:20
To add a ripple, add the `data-mdc-auto-init="MDCRipple"` attribute to the element you want to add the ripple to (ex: button) and add this line in the body, after the script importation `<script>mdc.autoInit()</script>`. Take a look at the documentation: https://material.io/components/web/catalog/buttons/#adding-ripples-to-buttons

**Comment by Garbee** [comment] 2017-07-20 13:09
> But every button ought to have ripples by default.

It is the encourage method. It shouldn't be auto-handled unless you're using the auto init system as @touficbatache pointed out. The reason MCW shifted from MDL on this front, is because with MDL everyone was hitting major pain-points due to it not being modular. The same auto-init system is provided, just in a different manner.

If you use the CSS-only buttons, there are no ripples. Because it is engineered to work without JS to keep things usable and accessible if needed. That's just a necessary thing to make applications as robust as possible.

**Comment by lynnjepsen** [comment] 2017-07-20 20:11
Thank you @touficbatache and @Garbee for those replies! I think that answers the original question, so I will close this issue. @philmaker1 if there is a specific component you're having trouble applying a ripple to, feel free to open a new issue with steps to reproduce.

**Closed by lynnjepsen** 2017-07-20 20:11 UTC
