### ISSUE TITLE
MDCTextField: Label doesn't overlay full width

### ISSUE THREAD

**Issue by mathiasschopmans** [material-components/material-components-web#3607] opened 2018-09-21 14:19 UTC
### What MDC Web Version are you using?

> latest / 0.39.3

### What browser(s) is this bug affecting?

> Chrome 69

### What OS are you using?

> OS X 10.13.6

### What are the steps to reproduce the bug?

- Goto https://material-components.github.io/material-components-web-catalog/#/component/text-field
- Fill "Full Width Textarea" with a long text
- Scroll the textarea slowly

**Screenshot:**
![bildschirmfoto 2018-09-21 um 16 11 27](https://user-images.githubusercontent.com/193253/45886706-16453080-bdba-11e8-842e-463b94865db4.png)

### What is the expected behavior?

- Shouldn't look awkward
- Should overlay full width

### What is the actual behavior?

- Doesn't look intended in the right corner
- In "dense-mode" there's even a transparen pixel at top

![issue-textfield-label](https://user-images.githubusercontent.com/193253/45886505-9919bb80-bdb9-11e8-8d6b-d60ae0775117.gif)

**Comment by williamernest** [comment] 2018-09-21 15:58
This looks like a duplicate of #3472 . Please post any additional information on that issue.

**Closed by williamernest** 2018-09-21 15:58 UTC
