### ISSUE TITLE
[mdc-tooltip] identical controls can't use the same tooltip

### ISSUE THREAD

**Issue by johncronan** [material-components/material-components-web#7513] opened 2022-01-17 16:52 UTC
I have removed the issue template, because this is very straightforward. Sorry.

Identical controls are not able to use the same tooltip.

Suppose there is a table and we wish to add a tooltip to the action button at the end of each row. The current design requires *both* that we keep track of how many rows there are, assigning a unique ID for each, *and* that we put the tooltips directly under the body element. It's overly complicated.

I don't care that tooltips aren't aware of each other. I simply don't want to have to assign unique IDs, when it's the same tooltip. There are an arbitrary number of these tables on the page, and each one has several different components responsible for removing and/or rendering new rows.

**Comment by sayris** [comment] 2022-01-26 21:55
This is actually WAI given tooltip element is only associated with a single anchor element. We definitely understand the desire to reduce the amount of HTML one has to write if the same tooltip label is going to be displayed across different anchor elements, we'll definitely consider this when implementing the MWC version of tooltips.

Duplicate of https://github.com/material-components/material-components-web/issues/6906

**Closed by sayris** 2022-01-26 21:55 UTC
Labels: feature-request
