### ISSUE TITLE
mdc-textfield bottom border stays light gray after focus + external animation

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#666] opened 2017-05-18 08:42 UTC
### What MDC-Web Version are you using?

Current; 0.10.0

### What browser(s) is this bug affecting?

Chrome 58.

### What OS are you using?

Windows 10.

### What are the steps to reproduce the bug?

See codepen: https://codepen.io/deap82/pen/QvVJrN

### What is the expected behavior?

Whenever the text-field is blurred, the bottom border is restored to its initial gray color.

### What is the actual behavior?

Sometimes, when focused and then moved around in the dom, for example due to some other element being expanded, it gets blurred, but bottom border color stops at a lighter gray than the initial gray.

More in codepen: https://codepen.io/deap82/pen/QvVJrN

**Comment by traviskaufman** [comment] 2017-05-18 15:28
Hey @deap82,

We're unable to reproduce this issue. Is there any _concrete_ steps you _know_ will cause this to happen?

**Comment by deap82** [comment] 2017-05-18 19:25
Other than what I'm describing in the codepen I have no other way to reproduce. Also in the application we're building it happens randomly, but mostly related to other element animations causing the text field to move in the page.

To me, using Chrome, it happens in the codepen consistently at least by the 4th-5th time I'm repeating the steps of focusing the text box and clicking the button. I noticed now that when it happens the border color is flickering between fully white and light gray during the animation, when animation stops it stays in this light gray.

My buest guess, unfortunately, is that this is some bug in Chrome related to the css transition of the border... As I was able to reproduce it in codepen I still thought it was worth reporting.

**Comment by anton-kachurin** [comment] 2017-05-22 22:11
@deap82 Are you using a high DPI display? I was able to reproduce it with the trick described in #399.
This time, I used `--force-device-scale-factor=3.1415`.

The bottom border appears to be in a lighter gray color because its width changes after the animation ran a few times.

**Comment by yeelan0319** [comment] 2017-05-24 21:41
I also cannot repro this on my end, but I think @anton-kachurin is on the right track. I tried the suggested tricks for setting `--force-device-scale-factor=3.1415` and zoom to 67%. I am able to see the flicker under second situation but still getting the normal grey afterward.

@deap82 can you repro this on other browsers as well or this is a chrome specific problem?

**Comment by deap82** [comment] 2017-06-16 08:14
@yeelan0319 Apologies for the delay; yes I have only reproduced the issue in Chrome.

FYI For our design, we've decided to add top, left, and right borders when the element is a textarea, this causes the bottom border to be not displayed at all on load - also only in Chrome.

My custom css for reference, if it could give some clue to the issue:
textarea.mdc-textfield__input {
		border-width: 1px;
		border-style: solid;
		border-color: rgba(0, 0, 0, 0.12);
	}

**Comment by abhiomkar** [comment] 2019-09-17 17:24
Marking this as obsolete, assuming this is fixed in latest text field.

**Closed by abhiomkar** 2019-09-17 17:24 UTC
