### ISSUE TITLE
Grid span 0 have no effect

### ISSUE THREAD

**Issue by andriytyurnikov** [material-components/material-components-web#2293] opened 2018-02-22 19:03 UTC
### What MDC Web Version are you using?
0.30.0

### What browser(s) is this bug affecting?
Chrome 64

### What OS are you using?
OS X High Sierra 10.13.3

### What are the steps to reproduce the bug?
https://codepen.io/andriytyurnikov/pen/aqKrYK

### What is the expected behavior?
Invisible cell
Cell with size 0 should not be visible

### What is the actual behavior?
Visible cell

### Any other information you believe would be useful?
Yeah, developing real apps based on tools - seriously helps developing tools.

**Comment by moog16** [comment] 2018-03-01 19:22
@andriytyurnikov  thanks for opening this issue, but this is a duplicate of #2293. Going to close and track in that issue.

**Closed by moog16** 2018-03-01 19:22 UTC

**Comment by kfranqueiro** [comment] 2018-04-02 20:45
I think there was a typo in our previous comment when we closed this... the original issue, which is being tracked, is #2270.
