### ISSUE TITLE
mdc-textfield--multiline shows validation error before initial interaction

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#841] opened 2017-06-20 01:41 UTC
### What MDC-Web Version are you using?

v0.13.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

https://codepen.io/Shyam-Chen/pen/vZLowj

### What is the expected behavior?

In the field with validation, `textarea` default should not have a red border.

### What is the actual behavior?

When the user first into the page, `textarea` default with a red border.

### Any other information you believe would be useful?

:x:

**Comment by traviskaufman** [comment] 2017-06-22 15:14
👍 Thanks for reporting!

**Comment by lynnjepsen** [comment] 2017-10-18 16:29
Confirmed this is still a bug even after our recent large batch of text field changes.

One proposed solution: Add private methods to check for input values on required textareas when MDCTextfield is initialized. If the input value is falsey, then add a modifier CSS class to style MDCTextfield a way that maintains the border color.

**Comment by Garbee** [comment] 2017-10-18 19:23
This is technically a correct thing, even though it looks weird.

On the web, native validation happens immediately. As the JS hasn't initialized yet, the red border is the CSS-only invalid rendering state. Then the JS kicks in to handle state and the red border is removed on upgrade.

This is an inherit problem with having a CSS-only base being upgraded into a JS world. It would be difficult to reconcile without offering a separate thing to turn off the CSS only display before JS initializes.

**Comment by lynnjepsen** [comment] 2017-10-30 20:00
@Garbee is correct, this is native validation, and we don't have a way of overriding that until the JS loads. I'm going to close this bug, because we can't offer a better solution.

**Closed by lynnjepsen** 2017-10-30 20:00 UTC
Labels: bug, in-tracker
