### ISSUE TITLE
Add new `mdc-circular-progress` component

### ISSUE THREAD

**Issue by lucasecdb** [material-components/material-components-web#4502] opened 2019-03-13 02:44 UTC
https://material.io/design/components/progress-indicators.html#circular-progress-indicators

**Comment by kfranqueiro** [comment] 2019-03-13 17:01
Thanks. This is a duplicate of #30.

**Closed by kfranqueiro** 2019-03-13 17:01 UTC

**Comment by lucasecdb** [comment] 2019-03-13 17:02
Oh, okay, sorry!
