### ISSUE TITLE
Icon toggle does not support SVG

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#3155] opened 2018-07-20 16:48 UTC
The way the icon toggle is built, it looks like it only support the font-family version of icons. 

The icon toggle is also doing some mildly concerning DOM manipulation. It changes the text content to toggle the icon. In order to support SVGs, the foundation can no longer just update text content.

**Comment by kfranqueiro** [comment] 2018-07-20 16:58
Duplicate of #3107

**Closed by kfranqueiro** 2018-07-20 16:58 UTC
