### ISSUE TITLE
Bug - @material/textfield - Error colors not working correctly on the dark theme

### ISSUE THREAD

**Issue by tyronedougherty** [material-components/material-components-web#1699] opened 2017-12-06 02:22 UTC
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

> `@material/textfield` `0.26.0`

### What browser(s) is this bug affecting?

> Google Chrome `62.0.3202.94` (latest stable as of time of post)

### What OS are you using?

> Mac OS High Sierra `10.13.1`

### What are the steps to reproduce the bug?

> Go to the demo page - https://material-components-web.appspot.com/text-field.html
> Tick the `Required` checkbox on the first text field (Email Address)
> Click on the text field and then click off of it (making it an invalid input)
> Inspect the element and observe that the `mdc-text-field__label` and other red colors on the text field component are `#d50000` (expected)
> Click the checkbox that turns it into the `Dark Theme`
> Again inspect the `mdc-text-field__label` element (and others) still has a `color` property of `#d50000` (unexpected)

### What is the expected behavior?

> The red colors on an invalid text field component using the dark theme should use `$mdc-text-field-error-on-dark` (`#ff6e6e`), instead of continuing to use `$mdc-text-field-error-on-light` (`#d50000`).

### What is the actual behavior?

> The red colors on an invalid text field component using the dark theme continues to use `$mdc-text-field-error-on-light` (`#d50000`).

### Any other information you believe would be useful?

As a side note, I've discovered that the `$mdc-text-field-error-on-dark` color (`#ff6e6e`) is actually incorrect. According to [the material design guidelines on text field errors](https://material.io/guidelines/components/text-fields.html#text-fields-states), the color should actually be `100% red (A400)`, which maps to `#FF1744` according to [the color guide](https://material.io/guidelines/style/color.html#color-color-palette).

**Comment by lynnjepsen** [comment] 2018-03-28 21:21
Closing this as cannot reproduce now that we dont have a "dark theme" checkbox on the text field demo page

**Closed by lynnjepsen** 2018-03-28 21:21 UTC
Labels: in-tracker
