### ISSUE TITLE
[Checkbox] error when compiling with sass 1.42.1

### ISSUE THREAD

**Issue by jkevingutierrez** [material-components/material-components-web#7410] opened 2021-09-24 02:22 UTC
### Steps to reproduce
1. Create a project like https://replit.com/@jkevingutierrez/mdc-checkbox-test it has:
  - @material/checkbox 12.0.0
  - sass 1.42.1
  - Webpack and necessary loaders (css-loader, sass-loader, etc)
2. Run `npx webpack`

### Actual behavior

Trying to compile a project with a checkbox, using latest sass 1.42.1 is throwing an error

```
SassError: Expected "(" or ".".
    ╷
329 │   $checkbox-padding: calc((_ripple-size - _icon-size) / 2);
    │                                        ^
    ╵
  node_modules/@material/checkbox/_checkbox-theme.scss 329:40  @use
  node_modules/@material/checkbox/_checkbox.scss 42:1          @forward
  node_modules/@material/checkbox/_variables.scss 24:1         @forward
  node_modules/@material/checkbox/_index.scss 1:1              @use
  index.scss 1:1                                               root stylesheet
```

### Expected behavior

It should compile well

### Screenshots

![image](https://user-images.githubusercontent.com/6220055/134608621-198a449f-16cb-42e7-898e-fb9cfa9798fe.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          | N/A
| Operating System | macOS Big Sur 11.6

### Additional context

Same thing happen if we don't use webpack, but sass directly

1. Create an npm project: `npm init`
2. Install sass: `npm install --save-dev sass`
3. Install checkbox: `npm install @material/checkbox @material/radio`
4. Create an index.scss file:
```
@use '@material/checkbox';
@use '@material/radio';
```
4. Run sass: `npx sass index.scss --load-path=node_modules/`
5. See error

![image](https://user-images.githubusercontent.com/6220055/134609118-37cb2087-9944-486c-af62-6c9d3c9e7864.png)

Same thing happen with the radio component

![image](https://user-images.githubusercontent.com/6220055/134611963-57a5882b-bc8a-42b1-8b19-086937be706f.png)

**Comment by stof** [comment] 2021-09-24 08:14
Duplicate of https://github.com/material-components/material-components-web/issues/7391 (which is fixed in the dev version but not released yet)

**Closed** 2021-09-24 09:21 UTC
Labels: bug
