### ISSUE TITLE
MDCMenu: Link is not working

### ISSUE THREAD

**Issue by 2003kaito** [material-components/material-components-web#3926] opened 2018-10-16 23:34 UTC
### What MDC Web Version are you using?

> 0.40.1

### What browser(s) is this bug affecting?

> Chrome 69.0.3497.100

### What OS are you using?

> Android 8.0.0, Windows 10

### What is the expected behavior?

> Links in MDCMenu should be working as links in MDCList.

### What is the actual behavior?

> If we click the link in MDCMenu, the menu closes but we can't go to the link destination.

### Any other information you believe would be useful?
> [Codepen](https://codepen.io/2003kaito/pen/bmaXeR)

**Comment by acdvorak** [comment] 2018-10-18 21:28
Thanks for filing this issue!

This is actually a duplicate of #3486, which is being fixed in #3680 😀

**Closed by acdvorak** 2018-10-18 21:28 UTC
