### ISSUE TITLE
MDC- Drawer Style

### ISSUE THREAD

**Issue by jimyhdolores** [material-components/material-components-web#6433] opened 2020-08-25 17:41 UTC
According to the documentation, for the Drawer to work, the following must be imported
![image](https://user-images.githubusercontent.com/10909792/91207897-1dc09300-e6cf-11ea-91a3-1692d0acec0a.png)

But it doesn't seem to work resulting in the following
![image](https://user-images.githubusercontent.com/10909792/91208364-bb1bc700-e6cf-11ea-934f-d5bd0d3c01a4.png)

![image](https://user-images.githubusercontent.com/10909792/91208257-8c055580-e6cf-11ea-9095-329b3849d582.png)

But if I import the styles in the following way, the Drawer becomes functional.
![image](https://user-images.githubusercontent.com/10909792/91208601-0a61f780-e6d0-11ea-84f5-f972dc21168d.png)
![image](https://user-images.githubusercontent.com/10909792/91208658-21084e80-e6d0-11ea-8092-00feccca8daa.png)

The question is why does this happen?

**Version**
"material-components-web": "^7.0.0"

**Comment by asyncLiz** [comment] 2020-08-25 18:17
Thanks for the bug! This is a duplicate of https://github.com/material-components/material-components-web/issues/6137.

The [drawer style documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#styles) has been updated. The variant styles that are used need to be included:

```scss
@use "@material/drawer";
@use "@material/list";

@include drawer.core-styles;
@include drawer.dismissible-core-styles;
@include drawer.modal-core-styles;
@include list.core-styles;
```

Keep in mind that you only need to include one of dismissible or modal core styles if you only use one of them. Include both if you use both within your app.

**Closed by asyncLiz** 2020-08-25 18:17 UTC
Labels: feature-request
