### ISSUE TITLE
Module build failed material/animation/functions

### ISSUE THREAD

**Issue by claretyoung20** [material-components/material-components-web#4508] opened 2019-03-15 15:24 UTC
I got this problem 

here is my ripple dep

```
| +-- @material/ripple@0.39.3
| | +-- @material/animation@0.39.0 deduped
| | +-- @material/base@0.39.0 deduped
| | `-- @material/theme@0.39.1 deduped
```
but I still get this error

```
ERROR in ./src/app/partials/sidemenu/sidemenu.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
^
      File to import not found or unreadable: @material/animation/functions.
      in filepath\node_modules\@material\ripple\mdc-ripple.scss (line 23, column 1)
```

On Angular project.

**Comment by kfranqueiro** [comment] 2019-03-18 18:46
I'm unable to reproduce this error if I `npm install @material/ripple@0.39.3` and then compile with `dart-sass -I node_modules`. Are you sure you're configuring your import paths correctly to point to your `node_modules` directory?

It also looks like what you pasted above is only part of your entire MDC Web dependencies. If you happen to depend on a mixture of MDC Web versions, you may need to configure a custom importer in order to resolve dependencies from nested `node_modules` directories correctly. We document how to do this in an [appendix](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#appendix-configuring-a-sass-importer-for-nested-node_modules) in our getting started guide.

If you still encounter trouble after trying a custom importer, can you provide more information (e.g. a package.json) for us to reproduce your setup?

**Comment by claretyoung20** [comment] 2019-03-19 08:25
I fix this problem by using npm i @angular-mdc/web instead of  "material-components-web".

**Comment by moog16** [comment] 2019-03-21 16:53
@claretyoung20 were you using a combination of @angular-mdc/web and material-components-web (MDC)? Is this why you were having issues? Or did you completely switch from MDC --> @angular-mdc/web? I want to make sure what you're experiencing isn't an actual issue.

**Comment by claretyoung20** [comment] 2019-03-21 16:58
Yeah, after I switch from MDC to @angular-mdc/web the error disappear.

**Comment by moog16** [comment] 2019-03-21 17:29
Do you have a codepen/codesandbox for us to replicate the error you had with material-components-web?

**Comment by moog16** [comment] 2019-03-25 19:25
Closing as no Sample code has been provided.

**Closed by moog16** 2019-03-25 19:25 UTC
