### ISSUE TITLE
missing js sourcemap files in version 0.35.0

### ISSUE THREAD

**Issue by lj1000** [material-components/material-components-web#3129] opened 2018-07-18 10:38 UTC
using version 0.35.0

within component @material/animation/dist/mdc.animation.js the last line is
//# sourceMappingURL=mdc.animation.js.map
 i.e. it references a sourcemap file that doesn't exist

**Comment by kfranqueiro** [comment] 2018-07-18 14:07
Thanks for reporting. This is a duplicate of #2942.

**Closed by kfranqueiro** 2018-07-18 14:07 UTC
