### ISSUE TITLE
Unpkg material components map files 404 on Safari

### ISSUE THREAD

**Issue by david-j-davis** [material-components/material-components-web#4077] opened 2018-11-12 18:47 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What browser(s) is this bug affecting? Safari
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15"

### What are the steps to reproduce the bug?

https://codepen.io/david-j-davis/pen/gQLzWe

I'm working with the cdn Unpkg files for my project. Open up this codepen in Safari and open up the developer console and observe that there are 404's for both the material-components-web.min.js.map and min.css.map. These two missing packages are causing my js to stop working. 
![screen shot 2018-11-12 at 10 44 22 am](https://user-images.githubusercontent.com/3498223/48368187-edc60e00-e667-11e8-9810-c91f912ff9c7.png)

### What is the expected behavior?

These files should not 404 or there should be map files for the cdn.

**Comment by abhiomkar** [comment] 2018-11-12 22:11
Thanks for reporting this issue @david-j-davis 

We're generating source maps for each package in build steps, but we don't seem to deploying it to npm repository.

I [quickly tested](https://codepen.io/abhiomkar/pen/mQOQeJ) hosting this bundle with source maps properly deployed it seems to work.

I'm adding this to our tracker to include source maps when deploying.

**Comment by abhiomkar** [comment] 2018-11-12 22:55
Also this seems to be duplicate of #4077

I'm closing this one.

**Closed by abhiomkar** 2018-11-12 22:55 UTC
Labels: icebox
