### ISSUE TITLE
[Getting Started Guide] Using MDC with Sass and ES2015 needs TLC

### ISSUE THREAD

**Issue by Thell** [material-components/material-components-web#5297] opened 2019-12-03 05:15 UTC
This isn't as much a _bug_ as it is a question/suggestion.
Button material setup and ripple code needs updating.

Should the [Getting Started Guide][1] linked as the first link of the README **Important Links** be a part of automated testing and quality control to ensure that this 'seemingly simple' first introduction to material-components-web will yield the results that are intended?

I ask because I went through it and everything 'looked' like it should work, but the button didn't match the button image, and the ripple didn't display a ripple (though the code was reactive while I watched in chrome dev-tools); so I cloned the Getting Started Guide's example [Glitch Repo][2], did the install and it works just fine.
After perusing documentation and tweaking things the button and ripple effect work; which makes me wonder when the last time was that it 'successfully' produced the desired output. I am guessing somewhere along the line of the packages updating something changed and now, to get the guide's stated results, different steps/code are needed.

It seems to me, that the Getting Started Guide should always produce the results it states and should follow along with master, even if some troubleshooting is needed for environment and build package updates and that making the output a part of testing would be AGoodThing:tm:.

This was asked about in discord and Liz (@asyncliz) asked me to open a ticket.

[1]: https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md
[2]: https://github.com/bonniezhou/material-starter-kit

**Comment by asyncLiz** [comment] 2019-12-03 17:21
Thanks for the issue! We'll need to update the docs and Glitch demo to be accurate with the latest version of MDC.

**Comment by abhiomkar** [comment] 2020-01-02 18:45
Docs have been updated:
https://github.com/material-components/material-components-web/commit/5b98de6a76998fcd8c71d6fabfe7dd17c16e653f

Can we close this?

**Comment by asyncLiz** [comment] 2020-01-03 16:46
Docs are good, though we should either update [material-starter-kit](https://github.com/bonniezhou/material-starter-kit) to v4 or remove the glitch link to it from [the getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#using-mdc-web-with-sass-and-es2015).

@abhiomkar @bonniezhou any preferences? I can make a quick PR to the starter kit or remove the link from our docs.

**Comment by abhiomkar** [comment] 2020-01-03 18:20
Yes, we would need to update the starter kit and many other places (Including code labs). We can start with updating starter kit.

Thanks Liz!

**Comment by asyncLiz** [comment] 2020-01-15 00:35
Waiting to publish the codelabs since I'll need to update them for host label textfield changes.

There's also one codelab owned by Martin Splitt that I have suggestion edits for, but they won't be back until Jan 24.

**Comment by asyncLiz** [comment] 2020-01-22 20:11
Looks like https://material.io/develop/web/docs/getting-started/ needs to be updated as well

**Comment by abhiomkar** [comment] 2020-01-22 20:51
material.io site can only be updated after MDC Web release which is due. We can also cut a minor release based off of `v4` just to update markdown files.

**Closed** 2020-01-27 17:38 UTC
Labels: docs

**Comment by asyncLiz** [comment] 2020-01-27 17:49
Closing since things have been updating or are being updated!

**Comment by nscozzaro** [comment] 2020-02-27 04:51
@asyncLiz Is there an example Glitch/CodeSandbox that you can point me to that is like "material starter kit" but uses pure typescript and no scss file? I just need a very very basic example. 
I can't get it to work -- I tried replicating all the HTML from the radio button component in pure Typescript (using a bunch of createElement()'s), but in the end the radio button shows up without any styling, including no ripple effect, and I can't figure out what the issue is. It would be great to have an example to look at.

**Comment by abhiomkar** [comment] 2020-02-27 04:54
@nscozzaro Here are some [examples](https://github.com/abhiomkar/mdc-web-getting-started) with bare minimum setup using different bundler options. Hope this helps.

**Comment by nscozzaro** [comment] 2020-02-27 05:02
Thanks. Maybe I'm confused about the SCSS file, which I'm trying to not use. In the "Installing Locally" section of this page https://material.io/develop/web/docs/getting-started/ it says 

> Each package provides precompiled CSS and JS under its dist folder. The precompiled JS is converted to UMD format and is consumable directly by browsers or within any workflow that expects to consume ES5. Referencing @material/foo within a Node.js context will automatically reference the precompiled JS under dist.

>However, for optimal results, we recommend consuming MDC Web’s ES2015 modules and Sass directly. This is outlined in the steps below.

All of the examples I see in your repo use SCSS files, but I'm trying to figure out how to use the material design web components without the SCSS files. Any pointers?

**Comment by asyncLiz** [comment] 2020-02-27 17:40
The precompiled CSS is in the `dist/` folder of the package. For example: https://unpkg.com/@material/button@5.1.0/dist/mdc.button.css.

For button you would need to include `node_modules/@material/button/dist/mdc.button.css` in your build.

It is more optimal to use Sass since you can exclude the CSS you are not using and take advantage of all of the theming capabilities that MDC offers.
