### ISSUE TITLE
[MDCSnackbar] Snackbar stays open if another tab is focused

### ISSUE THREAD

**Issue by CiriousJoker** [material-components/material-components-web#3710] opened 2018-10-06 16:44 UTC
### What MDC Web Version are you using?

> 0.40.0

### What browser(s) is this bug affecting?

> Chrome 71 Dev

### What OS are you using?

> Arch 4.18.10

### What are the steps to reproduce the bug?

> 1. Open [the demo page of the snackbar component](https://material-components.github.io/material-components-web-catalog/#/component/snackbar)
> 2. Click one of the buttons to open a snackbar
> 3. Open a new tab
> 4. Return to the old tab after 5 secs or so

### What is the expected behavior?
Snackbar should be closed OR stay open for the remaining duration.

### What is the actual behavior?
Snackbar stays open and doesn't close. Like, ever.

**Comment by kfranqueiro** [comment] 2018-10-08 14:16
This looks like a duplicate of #1398.

**Closed by kfranqueiro** 2018-10-08 14:16 UTC
