### ISSUE TITLE
MDC-Web: Dialog "You can't have a focus-trap without at least one focusable element"

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#762] opened 2017-05-31 18:48 UTC
I'm using `<script src="//unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>` w foundation and today am getting an error that I was not getting last week.

```
material-components-web.min.js:6 Uncaught Error: You can't have a focus-trap without at least one focusable element
    at p (material-components-web.min.js:6)
    at l (material-components-web.min.js:6)
    at Object.n [as activate] (material-components-web.min.js:6)
    at Object.trapFocusOnSurface (material-components-web.min.js:6)
    at e.value (material-components-web.min.js:6)
    at HTMLDivElement.n.transitionEndHandler_ (material-components-web.min.js:6)
```

Any ideas?  I have a `<button id="account-cancel" type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Cancel</button>` in the dialog?...

**Comment by rhroyston** [comment] 2017-05-31 20:29
Thinking more about it: why is MDC-Web force feeding this .mdc-dialog__footer__button--accept element and custom MDCDialog:accept/cencel events on us?  All we need is dialog.open() and dialog.close() methods...?

**Comment by rhroyston** [comment] 2017-05-31 21:52
fixed my issue. for some reason, i had CSS `visibility:hidden` inline on the `dialog` element.  Removed that and all works fine...

**Comment by robzenn92** [comment] 2017-06-01 08:02
@rhroyston Not sure if you are using the latest version (0.12.0), but in the positive case it has a [BREAKING CHANGE](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0120-2017-05-30) that states "Dialogs do not require a style="visibility:hidden" attribute in html".

If you still face the problem please be more precise as possible so we can help you. Otherwise just close the issue! 🙂 

We also have a [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) which we encourage you to use to create a reproduction of the issue.

**Closed** 2017-06-01 15:16 UTC

**Comment by grafa** [comment] 2017-06-03 10:33
Big thank you @robzenn92 !

**Comment by Download** [comment] 2018-11-11 05:54
Getting this same issue:

```
index.js?79b7:169 Uncaught Error: You can't have a focus-trap without at least one focusable element
    at getInitialFocusNode (index.js?79b7:169)
    at updateTabbableNodes (index.js?79b7:239)
    at Object.activate (index.js?79b7:40)
    at Object.trapFocus (index.js?254f:167)
    at MDCModalDrawerFoundation.opened (foundation.js?f521:36)
    at MDCModalDrawerFoundation.handleTransitionEnd (foundation.js?cb41:155)
    at HTMLElement.handleTransitionEnd_ (index.js?254f:120)
```

**Comment by zaguiini** [comment] 2018-11-17 02:46
+1 for @Download issue. Me is when I click to open it. Code:

```js
import React, {Component} from 'react';
import Drawer from '@material/react-drawer';
import Button from '@material/react-button';

import './App.scss'

export default class App extends Component {
  state = {open:false}
  mainContentEl = React.createRef();

  onDrawerClose = () => {
    this.setState({open: false});
    this.mainContentEl.current.querySelector('input, button').focus();
  }

  onListItemClick = () => this.onDrawerClose();

  render() {
    return (
      <div>
        <Drawer
          modal
          open={this.state.open}
          onClose={this.drawerOnClose}
        >
          Teste
        </Drawer>
        <div ref={this.mainContentEl} onClick={() => this.setState({ open: true })}>
          <Button raised>Click me!</Button>
        </div>
      </div>
    );
  }
}
```

**Comment by abhiomkar** [comment] 2018-11-19 18:04
@Download @zaguiini The error that you see expected behaviour when drawer is missing list component (which is a focusable element).

**Comment by Download** [comment] 2018-11-21 10:08
The error also happens when during development my Preact component gets re-rendered due to code changes and the component gets replaced with a new one.

**Comment by abhiomkar** [comment] 2018-11-21 19:48
@Download Can you please share an example code that I can run on sandbox?

Thanks!

**Comment by zaguiini** [comment] 2018-11-22 09:54
> @Download @zaguiini The error that you see expected behaviour when drawer is missing list component (which is a focusable element).

So how to do it? I just copied the example...

**Comment by raphaelrpais** [comment] 2018-11-22 16:53
> > @Download @zaguiini The error that you see expected behaviour when drawer is missing list component (which is a focusable element).
> 
> So how to do it? I just copied the example...

The same here!

**Comment by johnhaitas** [comment] 2018-11-27 18:11
> Getting this same issue:
> 
> ```
> index.js?79b7:169 Uncaught Error: You can't have a focus-trap without at least one focusable element
>     at getInitialFocusNode (index.js?79b7:169)
>     at updateTabbableNodes (index.js?79b7:239)
>     at Object.activate (index.js?79b7:40)
>     at Object.trapFocus (index.js?254f:167)
>     at MDCModalDrawerFoundation.opened (foundation.js?f521:36)
>     at MDCModalDrawerFoundation.handleTransitionEnd (foundation.js?cb41:155)
>     at HTMLElement.handleTransitionEnd_ (index.js?254f:120)
> ```
> I get this when I try to close the drawer (from preact-material-components).

@download I can verify that I see the same "_You can't have a focus-trap without at least one focusable element_" error with `MDCDrawer` on `preact-material-components`

**Comment by johnhaitas** [comment] 2018-11-27 18:31
@Download I found a solution to the problem - you must have at least one `DrawerItem` with the `selected` attribute

**Comment by Download** [comment] 2018-12-15 12:57
I can confirm that @johnhaitas great solution!

@ material components team
It really is a very confusing message and I think the requirement to have a selected item + the way it is handled when no item is selected is not very nice. Can't it just either pick the first element and select it, or insert a dummy element and select that if there are no elements? Why does this requirement exist in the first place? Is it to prevent scrolling or something?

The drawer is one of the first components people use and it gives a bumpy ride at the moment.

**Comment by abhiomkar** [comment] 2018-12-20 08:45
For future reference I'm linking a complete example of dismissible drawer on [stackblitz](https://stackblitz.com/edit/mdc-drawer-demo?file=index.js).

The reason we made it to have at least one focusable element inside drawer because of accessibility reasons.

- At least one focusable element is required to close the drawer using <kbd>ESC</kbd> key when it is opened and focus is inside drawer.
- Focus is trapped inside drawer when modal drawer is opened. This requires at least one focusable element to be present.

As suggested above, it is recommended to have at least one drawer item (i.e., `mdc-list-item`).

@Download Please see [this example](https://stackblitz.com/edit/mdc-drawer-demo-ytwosc?file=index.js) for use case when none of the drawer items are selected initially. Drawer component itself is not aware which navigation item is currently active, it is also not safe assumption to activate or select first item.

**Comment by guptamahcl** [comment] 2019-10-17 08:08
I guess actually adding a focusable element like button to the drawer would make the error go away.
