### ISSUE TITLE
`mdc-text-field` (3 in a row), flows out of surrounding `mdc-drawer-app-content` when setting custom width.

### ISSUE THREAD

**Issue by vedtam** [material-components/material-components-web#4110] opened 2018-11-26 06:35 UTC
Hi,

I'm trying to set 3 `mdc-text-field` (that are placed inside `mdc-drawer-app-content`) to fill the screen horizontally by adding a width of ~33.33% to each. But as I do that, the text-fields starts to flow out on the x axis and if scrolling to the right go beneath the drawer.

From what I have observed the text-fields have this:

```
.mdc-text-field::before {
...
width: 200%;
}
```

Which I assume is part of a ripple effect, and cause the overflow.

![issue](https://user-images.githubusercontent.com/4981592/48996870-6348d880-f156-11e8-9db4-481557fbb14a.gif)

### What MDC Web Version are you using?

> ^0.41.0

### What browser(s) is this bug affecting?

> Chrome 70

### What OS are you using?

> OSX

### What are the steps to reproduce the bug?
> 1.  Add a dismissible drawer by copying the code from docs
> 2. Add 3 `mdc-text-fields` to the `mdc-drawer-app-content` div
> 3. Set the `mdc-text-fields` width to 33.3% to fill the entire row
> 4. Scroll to right (along x)
> 4. Observe the component's behaviour as it goes behind the drawer on the left while scrolling

> I also have a [template on CodePen](https://codepen.io/vedtam/pen/bQKvZw?editors=1000) which demonstrates the issue.

### What is the expected behavior?

> The 3  textfield when having equal (33.33%) width, fill the width of the parent div without flowing out on the x axes.

### What is the actual behavior?

> The 3  textfield when having equal (33.33%) width, flow out of the parent div on the x axes.

**Comment by williamernest** [comment] 2018-11-26 18:12
@vedtam Thanks for filing this issue. This occurs because we use the before/after elements for the states ripple which is much larger than the element. To temporarily fix this issue you can put the text field in a container element with `overflow: hidden`.

https://codepen.io/williamernest/pen/wQxzRr?editors=1100

**Comment by kfranqueiro** [comment] 2018-11-26 20:04
This is a duplicate of #4057, and is also reproducible in the [text field catalog page](https://material-components.github.io/material-components-web-catalog/#/component/text-field). I'm testing a fix right now.

**Closed by kfranqueiro** 2018-11-26 20:04 UTC
