### ISSUE TITLE
[mdc-auto-init] npm index.d.ts has multiple default exports

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-components-web#5158] opened 2019-10-05 01:56 UTC
### Bug report
npm @material/auto-init/index.d.ts has multiple default exports

### Steps to reproduce
https://repl.it/repls/ElasticKnowledgeableLocations

### Actual behavior
> node_modules/@material/auto-init/index.d.ts:38:16 - error TS2528: A module cannot have multiple default exports.

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |3.2.0
| Browser          |Chrome 77.0.3865.90
| Operating System |Windows 10 (1903)

### Possible solution
Remove duplicate default export from index.d.ts

**Comment by abhiomkar** [comment] 2019-10-18 15:43
I'm not able to reproduce this issue.

Demo https://glitch.com/edit/#!/noisy-muscle?path=index.js:2:24

**Comment by austinw-fineart** [comment] 2019-10-21 02:08
This is a TypeScript compiler error; I'm not sure how your demo is supposed to demonstrate that.
Anyway, here's my own demo: https://repl.it/repls/ElasticKnowledgeableLocations

**Comment by devrikx** [comment] 2019-11-20 23:26
Same issue here as of the last couple of days.  I had many more after digging into an outdated project and updating material design - though upgrading the `typescript` version to >3.0, and the *jquery* `types` package to the current latest resolved all but:

```bash
  [Build]: Compiling Typescript sources into JavaScript...  
node_modules/@material/auto-init/dist/mdc.autoInit.d.ts(44,20): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/dist/mdc.autoInit.d.ts(45,20): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/index.d.ts(38,16): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/index.d.ts(39,16): error TS2528: A module cannot have multiple default exports.
```

and

```bash
  [Build]: Generating Typescript declarations...  
node_modules/@material/auto-init/dist/mdc.autoInit.d.ts(44,20): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/dist/mdc.autoInit.d.ts(45,20): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/index.d.ts(38,16): error TS2528: A module cannot have multiple default exports.
node_modules/@material/auto-init/index.d.ts(39,16): error TS2528: A module cannot have multiple default exports.
```

I upgraded material-components-web to `"material-components-web": "^4.0.0",`

and `"@types/material__auto-init": "^0.35.1",` seems to be the latest version (my other `@types/material...` packages are at their latest as well.

The issue is not stopping the build from happening, but to add to the reported issue...

**Comment by emilgpa** [comment] 2020-01-14 15:52
same error here

**Comment by asyncLiz** [comment] 2020-01-14 17:27
@abhiomkar this can be fixed by removing the export keyword in the function declaration and exporting it manually.

```diff
- export function mdcAutoInit(root = document) {
+ function mdcAutoInit(root = document) {
  ...
  // tslint:disable-next-line:no-default-export Needed for backward compatibility with MDC Web 
  v0.44.0 and earlier.
  export default mdcAutoInit;
+ export { mdcAutoInit };
```

**Comment by abhiomkar** [comment] 2020-01-14 17:51
Missed to reply on this thread. Yes, I noticed multiple default exports in [auto-init/index.d.ts](https://unpkg.com/browse/@material/auto-init@4.0.0/index.d.ts) which is not intended.

Removing export keyword from declaration and manually exporting it fixed the issue. Will send out a PR. Thanks @asyncLiz !

**Closed** 2020-01-15 01:36 UTC
Labels: bug
