### ISSUE TITLE
Wrong position of opened Select inside Dialog component

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web#719] opened 2017-05-25 10:40 UTC
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

Chrome, Firefox, probably all others as well

### What are the steps to reproduce the bug?

Add select component to Dialog and open it.

> We also have a [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to repro the issue, the less time it takes to verify and
> fix it!

http://codepen.io/bmihelac/pen/qmvxjJ

### What is the expected behavior?

Open choices in proper position.

### What is the actual behavior?

Wrong position, shifted options as on picture below:

![mdc-select-dialog](https://cloud.githubusercontent.com/assets/13813/26447106/4b9f1d7c-4147-11e7-8fbc-120556316849.png)

**Comment by yeelan0319** [comment] 2017-05-26 23:05
Definitely not look right, thanks for filing.

**Comment by pgbross** [comment] 2017-06-21 10:55
From duplicate issue #844 

The simple menu underlying the select list is positioned using css `position: fixed` semantics with the calculations relative to the viewport. However if an ancestor, such as the `.mdc-dialog__surface` has a transform property set to something different from none then this ancestor is used as the container instead of the viewport.

Note this fault is not limited to within a dialog but wherever there is an ancestor with a transform property.

**Comment by pvamshi** [comment] 2017-07-26 06:27
Is there a workaround or temporary fix for this. Thankyou.

**Comment by DBartsch** [comment] 2017-07-26 14:08
Yeah .. I'd also be interested.

Possibly best would be to just move the menu to the body, give it an id and aria-controls on the parent

**Comment by abyr** [comment] 2017-08-02 11:06
As a temporary fix it's possible to overwrite "top" and "left" with "inherit !important" on ".mdc-select__menu".

**Comment by j-o-d-o** [comment] 2017-08-09 09:49
I also seems like setting overflow: hidden to mdc-dialog__body changes the position. The offset is smaller but it still has the wrong position. 
If overflow: hidden is not set for mdc-dialog__body, the workaround from @abyr works.

**Comment by thosakwe** [comment] 2017-08-30 21:33
Still getting this bug. If I could help patch it up, that would be awesome. Just can't figure out what the cause is.

**Comment by j-o-d-o** [comment] 2017-09-01 13:58
Is there actually a reason that the select menu is position: fixed? When scrolling this is really really bad. position absolute with mdc-select being position: relative seems much butter.


@thosakwe I think the problem is, that getBoundingClientRect() is not returning the correct value when some parent is scrolled. Or at least not the correct value with the current CSS styles. 

My workaround for scrollable parents is this:

```
    .mdc-select{
        position: relative;
    }
    .mdc-select__menu{
        left: 0px !important;  
        top: 0px !important;
        position: absolute !important;
    }
```
Note: this always opens the menu from the first index. It's just a hack and might actually defet some behaviours that are explained in the offical documentation.

**Comment by jordyboytjuh** [comment] 2017-09-05 08:02
Same issue over here, and also the scrolling with an selectbox open is an issue.

**Comment by SVyatoslavG** [comment] 2017-11-24 21:52
Same issue, please fix it.

**Comment by izakfilmalter** [comment] 2017-12-12 18:22
I've done the following to get a fairly good ux:

```css
.mdc-dialog .mdc-select {
  position: relative !important;
}

.mdc-dialog .mdc-select__menu {
  top: inherit !important;
  left: inherit !important;

  max-height: calc(100vh - 64px)!important;

  margin-top: 44px;
}
```

**Comment by mellogarrett** [comment] 2017-12-18 17:20
Is there an actual fix coming for this? The work arounds are not ideal. This issue has been open for quite some time now.

**Comment by mellogarrett** [comment] 2017-12-18 19:44
Actually, the positioning is correct in IE 11, but wrong in Chrome, Safari, & Firefox 🤔

**Comment by izakfilmalter** [comment] 2017-12-18 19:48
Probably an IE bug, `position: fixed` is relative to any parent that has a
transform on it.

**Comment by mellogarrett** [comment] 2017-12-18 20:31
`transform: translate(0,0);` screws up the positioning of the opened menu.

**Comment by devgianlu** [comment] 2018-01-10 14:13
Setting `transform: none` on the `.mdc-dialog__surface` element fixed the issue for me.

**Comment by piotr-cz** [comment] 2018-02-06 10:38
Still a problem in v0.29

**Comment by kmmbvnr** [comment] 2018-02-07 05:20
I agree with @j-o-d-o The only correct div based select implementation should be based on position:relative/absolute styles. That's how select is implemented in the MaterializeCSS library.

**Comment by izakfilmalter** [comment] 2018-02-07 19:51
I think `mdc` needs to have a special `div` inside of `body` where it places all elements that need to overlap. You get into issues with `overflow: hidden` and with any `transform` with both `select`, and `dialog`. This would resolve that, can still use the regular position techniec, but you lose so many bugs like this. 

For instance, if we want to do any panel based ui, we are gonna use a transform for mobile performance. Which in turn screws up any selects inside of that panel. I used to work around this with the css only select, but now that's gone as well which is a big pain in the but because the native ui for select on mobile is not bad, and in the old docs it was pointed out as being a better experience.

**Comment by piotr-cz** [comment] 2018-02-08 08:43
I'd love to see the css-only Select component back that uses native `<select>` element.

There are too many things that are hard to work around when implementing similar functionality in javascript, this issue is just one of them.

I've been trough it before with _Select2_, now it's exactly the same with _MDCSelect_

**Comment by PeteCrighton** [comment] 2018-02-28 14:31
@izakfilmalter Thanks for your workaround! I used a margin-top of 7.5px, but that works quite well for me. Still an annoying bug …

**Comment by ixtli** [comment] 2018-03-02 19:33
I don't know if this will help anyone, but I am including `@material/select`, `@material/menu`, and `@material/list` in my React 16 project. I'm getting a behavior where I was `@include`ing all the MDC styles I am using in another SCSS file and the menu was showing up in the center of the window.

After a bit of puzzling and comparing the styles on the demo page ( https://material-components-web.appspot.com/select.html ) with my own, I found that `.mdc-menu--open` style was being applied on top of `.mdc-select__menu` on my `mdc-menu` component. This was resulting in `postition: absolute` instead of `fixed`. I ended up re-arranging my imports in my scss file from this:

```sass
@import "../node_modules/@material/select/mdc-select";
@import "../node_modules/@material/menu/mdc-menu";
@import "../node_modules/@material/list/mdc-list";
```
to
```sass
@import "../node_modules/@material/menu/mdc-menu";
@import "../node_modules/@material/select/mdc-select";
@import "../node_modules/@material/list/mdc-list";
```
and now it works.

**Comment by kmmbvnr** [comment] 2018-03-12 08:20
I've got same inside drawer, even with `transform: none` style from `.mdc-drawer--open`

Fixed by

```css
 .mdc-drawer__drawer {
      will-change: unset;
}
```

**Comment by r1cs1** [comment] 2018-03-12 11:11
I've found two important notes in the w3 specs.

[Will-change](https://www.w3.org/TR/css-will-change-1/)
> If any non-initial value of a property would cause the element to generate a containing block for fixed-position elements, specifying that property in will-change must cause the element to generate a containing block for fixed-position elements.

[Transform](https://www.w3.org/TR/css-transforms-1/)
> For elements whose layout is governed by the CSS box model, any value other than none for the transform also causes the element to become a containing block, and the object acts as a containing block for fixed positioned descendants.

Thus it means the mdc-menu for the select component is going to be relative to the parent element that is alike mentioned above instead of the viewport, while the top; left; properties are calculated relative to the viewport instead of the transformed container. Same issue applies to a right side aligned mdc-drawer.

**Comment by rubenmendoza** [comment] 2018-03-12 23:50
I have created a pen to reproduce this issue [https://codepen.io/linear/pen/YazeQx](https://codepen.io/linear/pen/YazeQx)

**Comment by abhiomkar** [comment] 2019-10-18 16:13
This issue seems to be fixed in new version.

Closing this.

**Closed by abhiomkar** 2019-10-18 16:13 UTC
Labels: backlog, bug
