### ISSUE TITLE
Select menu does not close when clicking

### ISSUE THREAD

**Issue by YuoMamoru** [material-components/material-components-web#1747] opened 2017-12-12 07:01 UTC
### What MDC-Web Version are you using?

0.27.0

### What browser(s) is this bug affecting?

Crome 62.0.3202.94 and any browser

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Go to https://codepen.io/YuoMamoru/full/rpNxMB
2. Click a "mdc-select" in the page
3. Click the list under "Steps to Reproduce the Bug"

### What is the expected behavior?

If you click the point on "li" tag with class="mdc-list-item", the menu should close.

### What is the actual behavior?

If you click the point on "li" tag with class="mdc-list-item", the menu does not close.

### Any other information you believe would be useful?

I think that it is an issue not to check whether the element clicked is part of its own menu in handleDocumentClick_(evt) on mdc-menu/simple/foundation.js.

**Comment by simono** [comment] 2017-12-12 22:09
I'm working on a fix for this. I'll send a PR soon.

**Comment by KayvandenHeuvel** [comment] 2017-12-18 10:50
I have also noticed that the mdc-simple-menu won't close if you click on a mdc-list-item element somewhere else on the page, even if it isn't part of the simple-menu.

**Comment by simono** [comment] 2017-12-18 10:56
I've fixed this in #1756.
@KayvandenHeuvel @YuoMamoru Maybe you could try my patch?

**Comment by YuoMamoru** [comment] 2017-12-19 00:39
The patch looks good to me.

**Comment by jordyboytjuh** [comment] 2018-01-25 14:22
Same issue over here in 0.29.0. Can't click on the titles in the mdc-simple-menu. If I click at the side it works. Looks like I'm using the same HTML as in the demo (there it works).

**Comment by aaronhudon** [comment] 2018-01-31 20:40
@jordyboytjuh I believe the issue is that menu item elements cannot be anything but text, no sub-elements.  A fix is required

**Comment by simono** [comment] 2018-02-02 14:22
@jordyboytjuh @aaronhudon I think this should be fixed in #1756.

**Closed** 2018-02-02 18:08 UTC
Labels: help wanted
