### ISSUE TITLE
MDCSelect mdc-select__menu mdc-menu mdc-menu-surface HTML nodes extracted from original node locations.

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#4450] opened 2019-02-26 12:40 UTC
## Bugs

The Demo MDCSelect seems to have the issue also. The contents of the SELECT (the options) are extracted from original position in the DOM and appended to the end of BODY. Hence the items HTML becomes unlinked to the original DOM parent node.

### What MDC Web Version are you using?

> 0.44.1

### What browser(s) is this bug affecting?

> Chrome (probably others)

### What OS are you using?

> Both Win10Pro and MacOS

### What are the steps to reproduce the bug?

In the Demo for MDCSelect

https://material-components.github.io/material-components-web-catalog/#/component/select

### What is the expected behavior?

> the mdc-select__menu element should stay in its original inserted DOM position - eventually within the parent mdc-select element - but it shouldn't be relocated in whatever case.

<img width="1466" alt="screenshot 2019-02-26 at 13 33 41" src="https://user-images.githubusercontent.com/4300051/53413397-2944d800-39cc-11e9-957a-0bf158d73ec6.png">

### What is the actual behavior?

MDC list items are extracted to the bottom of the document and loose the parent Node etc.
In some cases I see it produce multiple listbox nodes - that are unlinked to the original HTML.

**Comment by cintaccs** [comment] 2019-02-28 19:45
that the MDC list of the select node is extracted and repositioned in the DOM - is that intended behaviour? does anyone know? Seems to happen during initialization in e.g.

**Comment by acdvorak** [comment] 2019-02-28 20:12
Thanks for filing this issue!

This is actually intentional behavior (sort of—see below).

To avoid the dropdown menu getting clipped when the Enhanced Select is inside an element with CSS `overflow` set to `hidden`, `scroll`, or `auto` (e.g., [`mdc-dialog`](https://github.com/material-components/material-components-web/tree/83d468b/packages/mdc-dialog)), we call [`MDCMenu.hoistMenuToBody()`](https://github.com/material-components/material-components-web/tree/83d468b/packages/mdc-menu#mdcmenu-properties-and-methods):

https://github.com/material-components/material-components-web/blob/2025c8b5eb9891ec3f159e2fde03f45d23f6bbed/packages/mdc-select/component.ts#L355-L361

However, this "solution" has an unfortunate side effect, which is that the menu becomes disconnected from the anchor element when the user scrolls:

![screen video capture](https://user-images.githubusercontent.com/409245/53594740-5d490600-3b50-11e9-8a21-87c3a7623849.gif)

The detached scrolling behavior is obviously bad, so I'm going to reopen #879 to investigate a better solution.

Closing this issue since it's technically working as intended. See #879 for further updates.

Thanks again! 😀

**Closed by acdvorak** 2019-02-28 20:12 UTC

**Comment by cintaccs** [comment] 2019-03-15 23:59
@acdvorak I have implemented pages with multiple enhanced select controls on the same page. It is part of a SPA where e.g. the MDC Tab control will change the visible part the UI. The enhanced select control is moving (undocumented to my knowledge) the select "mdc-select__menu mdc-menu mdc-menu-surface" element to end of the body content. However it is not removed again without additional actions. Therefore switching tabs back and forward to the content that creates the select controls will keep adding (moving) the same content to the end of the body. In my case it might be my design causing this - but it is something that is bound to happen in a lot of other cases.

**Comment by cintaccs** [comment] 2019-03-16 00:00
<img width="827" alt="Screenshot 2019-03-16 at 01 00 05" src="https://user-images.githubusercontent.com/4300051/54467655-dbc7b980-4786-11e9-8be6-81dec3147824.png">

@acdvorak I end up with something like this.

**Comment by cintaccs** [comment] 2019-03-16 00:05
@acdvorak It might be an option to feed the select with an "external" list. I.e. if the "mdc-select__menu mdc-menu mdc-menu-surface" is defined outside the "mdc-select mdc-select--outlined" element - then the MDC functionality could reference it instead of moving anything. The potential benefit of that would be that multiple select controls might re-use the same list content (like e.g. when you have to assign a "fruit" to various controls from a list of "fruits" which is the same for each of those).

**Comment by cintaccs** [comment] 2019-03-16 00:48
@acdvorak sorry for the "spam" ... if I am not mistaken - I think this issue is also causing the select menu to periodically NOT open on "click". I.e. if you click to open a select - then select or close the select menu - then click and open again - the content is now sitting in the body already - the select functionality have to remove and insert the new content (not sure what it is doing in the background). The repeated open and close of select will not always do the same thing (menu might open above at first - then below on next click e.g.). I also see the menu NOT opening - but it is difficult to reproduce - because on next click it will open.
