### ISSUE TITLE
Cannot use various material-components-web component mixins without control over html

### ISSUE THREAD

**Issue by dantman** [material-components/material-components-web#6361] opened 2020-08-12 02:06 UTC
## Feature Request

I've been trying to use material-components-web inside of an environment where I cannot control most of the HTML structure to add mdc css classes. My use case is for Azure AAD B2C sign in pages, but this issue probably applies to others as well.

MDC's SASS actually works fairly well for this. Most of the modules export modules like `typography.base` and `typography.typography(subheading1)` that can be used to apply MD behaviours to css rules that target the pre-existing HTML structure.

However there are a few exceptions to this. For some of the more complex components like `@material/button` and `@material/card` the public mixins export css classes instead of styles you can apply to any css rule.

For example `@material/button`'s main export is a `core-styles` mixin that exports a `.mdc-button { ... }` with the styles.

### Proposed solution

Modules like these should export additional mixins that can be used to apply component styles directly to css rules. If a component is complex and needs to export other rules for child elements and conditions then it should export extra mixins for those cases.

e.g. `@material/button` should probably export the following mixins:

- `button`
- `button-icon`
- `button-touch`
- `button-raised`
- etc

### Alternatives considered

I considered doing these manually. But components like button are pretty complex and require duplicating half a dozen lines of implementation-specific code to recreate button outside.

**Comment by joyzhong** [comment] 2020-08-12 21:00
MDC Web component Sass mixins are intended to be used with HTML that is marked up with the corresponding component classes. The Sass would be difficult to maintain otherwise, especially for more complex components.

Closing as intended.

**Closed by joyzhong** 2020-08-12 21:00 UTC
Labels: feature-request
