### ISSUE TITLE
Highlight/Ripple remains after touch interactions

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#1553] opened 2017-11-06 18:42 UTC
### What MDC-Web Version are you using?

Latest: tried here: https://material-components-web.appspot.com

### What browser(s) is this bug affecting?

Tested on Chrome for android

### What OS are you using?

Android 7

### What are the steps to reproduce the bug?

Tap on the button and see that a whiter background remains

### What is the expected behavior?

The ripple disappears completely

**Comment by anton-kachurin** [comment] 2017-11-07 04:48
Extra data points:
1) Same happens on desktop Chrome switched to "device" mode with enabled touch events.
2) On the first touch, the background of the button is slightly "highlighted" (similarly to how it looks when focused through pressing the tab key) but the subsequent touches on the same button remove this.

**Comment by kfranqueiro** [comment] 2017-11-07 15:17
I think this sounds like #809?

**Comment by lynnjepsen** [comment] 2017-11-08 18:11
Looks like a duplicate of #809

**Closed by lynnjepsen** 2017-11-08 18:11 UTC
