### ISSUE TITLE
(BUG?) Hovering list-item with Checkbox (svg) in the DEMO show black box.

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#4690] opened 2019-05-07 13:29 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

<img width="1244" alt="Screenshot 2019-05-07 at 15 24 17" src="https://user-images.githubusercontent.com/4300051/57303038-bdbe6b80-70dc-11e9-86a1-6b9ceb2fd308.png">

### What MDC Web Version are you using?

2.1.0

### What browser(s) is this bug affecting?

Chrome Version 74.0.3729.131 (Official Build) (64-bit)

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

https://material-components.github.io/material-components-web-catalog/#/component/list

hover over list with SVG checkboxes.

### What is the expected behavior?

hover should not be a black box.

### What is the actual behavior?

hover is covering the list-item with a solid black box.

### Any other information you believe would be useful?

I am running my W10 Chrome in a VMWare instance.

**Comment by Darhakexge** [comment] 2019-05-07 14:34
Duplicate of #4629

**Closed** 2019-05-09 15:51 UTC
