### ISSUE TITLE
Automated tests no longer pressing button when mobileEmulation is specified

### ISSUE THREAD

**Issue by berenddeboer** [material-components/material-components-web#2937] opened 2018-06-14 22:38 UTC
I noticed that my mobile automated tests stopped working. I'm using Behat + mink driver and if I specify mobileEmulation for Chrome, buttons are no longer being pressed. Works fine when not specifying mobileEmulation.

Is anyone seeing this too? Is this just an issue with latest chrome/chromedriver/selenium?

My Chrome is v67. Web components v0.35.2.

**Comment by kfranqueiro** [comment] 2018-06-18 19:56
I'm not sure this is something we'd be able to easily reproduce, but if something used to work and no longer does while your version of MDC Web remained constant, I have to think the problem isn't with MDC Web.

I'm going to close this, but here's a couple of things I'd suggest trying for troubleshooting, assuming you're referring to MDC Buttons:

* Try removing `MDCRipple` JS instantiation (or adding it, if you aren't currently using it)
* Try with a vanilla button with some basic `button:active` styles

**Closed by kfranqueiro** 2018-06-18 19:56 UTC
