### ISSUE TITLE
Menus open from edge not working

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web#686] opened 2017-05-19 13:21 UTC
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

v0.11.1

### What browser(s) is this bug affecting?

N/A

### What OS are you using?

N/A

### What are the steps to reproduce the bug?

[Documentation](https://material.io/components/web/catalog/menus/) states that there are convenience classes to use for changing opening point of menus:

> The menu will open from the top left by default (top right in RTL). Depending on how you’ve positioned your button, you may want to change the point it opens from. To override the opening point, you can style transform-origin directly, or use one of the following convenience classes:

Adding any of this classes to menu component does not change anything, ie:

```
<div class="mdc-simple-menu mdc-simple-menu--open-from-top-right">
```

Searching source code shows this classes are not used anywhere.

### What is the expected behavior?

Opening menu from edge specified with class.

### What is the actual behavior?

Always opening menu from top-left (or different edge when there is no space)

> Please describe what the component/code is actually doing that's different from what it should be
doing.

**Comment by yeelan0319** [comment] 2017-05-22 16:10
Hi @bmihelac ,

This sounds like a interesting problem. We checked the code and the logic is there, could you provide a pen to reproduce for the bug so we can nail down what is exactly happening?

**Comment by bmihelac** [comment] 2017-05-22 16:23
Hi @yeelan0319 and thanks for quick answer.
Sure, I can make a pen to provide example.

Just for info, searching in this repository for [mdc-simple-menu--open-from-top-right](https://github.com/material-components/material-components-web/search?l=JavaScript&q=mdc-simple-menu--open-from-top-right&type=&utf8=%E2%9C%93) or [TOP_RIGHT](https://github.com/material-components/material-components-web/search?l=JavaScript&q=TOP_RIGHT=&utf8=%E2%9C%93) constant will demonstrate that this strings are not actually used in code :)

**Comment by bmihelac** [comment] 2017-05-22 17:12
Here is codepen that reproduces behavior:

http://codepen.io/bmihelac/pen/zwyNpq

I expected result to be like this:

![686](https://cloud.githubusercontent.com/assets/13813/26320272/8b5defa0-3f22-11e7-9a4b-9914f93c2185.png)

It is possible that I just misunderstood documentation.

**Comment by yeelan0319** [comment] 2017-05-25 17:01
@bmihelac We think what you ask for it total valid, but once again, we would like to confirm with designer that's their suggestion. Hold on tight and we will get back to you asap.

**Comment by robzenn92** [comment] 2017-05-25 23:30
I think that the problem is due to the fact that in the `autoPosition_()` function (defined in [line 318](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L318)) the default values for vertical and horizontal are top and left respectively. Those values are changed **only once** if `isRtl()` and then are passed to the `setTransformOrigin()`.

Hence, there is no checks to understand if the root element has one of the *convenience classes* (e.g. `mdc-simple-menu--open-from-top-right `) defined in the [README.md](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu#manual-positioning). To the best of my knowledge there is the need to check if the root element has one of those classes before invoking `setTransformOrigin()`.

Let me know, I might be wrong.

**Comment by aecz** [comment] 2017-09-21 00:56
I have this issue too.
I forked the codepen above and added this workaround:
```
.mdc-simple-menu--open-from-top-right {
  left: auto !important;
  right: 0;
  transform-origin: right !important;
}
```
https://codepen.io/aecz/pen/MEejQV

Demo below is working but only because the anchor is close to the right border.
https://material-components-web.appspot.com/simple-menu.html
Also, the demo does not seem to use the convenient classes.

**Comment by Garbee** [comment] 2017-09-21 01:19
The design is right. It *covers* the triggering node as the MD spec says. The "open from" is where the animation to open the menu occurs from. It does not change the physical position of the menu list node.

**Comment by aecz** [comment] 2017-09-21 09:39
I updated the codepen to show my use case. The menu covers the anchor (red) but also the adjacent node (blue). If it is by design then what are the convenient classes used for ?
https://codepen.io/aecz/pen/MEejQV

Without the workaround:
![image](https://user-images.githubusercontent.com/7781120/30689237-a85ae7ae-9ec0-11e7-9cb0-0d431dadc7ee.png)
With the workaround:
![image](https://user-images.githubusercontent.com/7781120/30689452-488ba7ea-9ec1-11e7-90b4-a7c0613a3d8e.png)

**Comment by Garbee** [comment] 2017-09-21 09:48
The classes, as stated, are for the opening animation only. Not the physical menu positioning.

**Comment by aecz** [comment] 2017-09-21 11:51
@Garbee Thanks for explaining. Convenient classes are indeed for animations only. (Maybe we could rename them mdc-simple-menu--**animate**-from-top-right).

My question is then, how do we position the menu to top right ?

I have made another [codepen](https://codepen.io/aecz/pen/oGLEmZ) copying the [official demo](https://material-components-web.appspot.com/simple-menu.html).
It adds the convenient classes depending on the button position AND fix the menu position.

Without position workaround:
![image](https://user-images.githubusercontent.com/7781120/30694302-af1f3956-9ed3-11e7-9f5c-6f84fb9f9ab4.png)

With position workaround:
![image](https://user-images.githubusercontent.com/7781120/30694278-99b04c68-9ed3-11e7-91d0-4c1315645c45.png)

Any chance that this could be the default behavior or make it easier to postition the menu correctly?

**Comment by Garbee** [comment] 2017-09-21 22:57
As far as I understand it, the current behavior is correct by the spec. The design team should let us know if your alternate positioning is allowed. If they say no, then it's on developers to implement this if they want it.

**Comment by abhiomkar** [comment] 2019-11-13 16:37
Closing this as obsolete. Please feel free to re-open if you're still able to repro this with newer version of MDC Web.

**Closed by abhiomkar** 2019-11-13 16:37 UTC
Labels: needs-design-guidance
