### ISSUE TITLE
Web - MDCDrawer keep opening states !

### ISSUE THREAD

**Issue by updatepixels** [material-components/material-components-web#4346] opened 2019-02-04 15:10 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs
Can't close the Drawer because it's keeping states isOpening with css class : mdc-drawer--animate & mdc-drawer--opening 

### What MDC Web Version are you using?
<script type="text/javascript" src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet" />

### What browser(s) is this bug affecting?
Cordova WebApp

### Any other information you believe would be useful?
I avoid this issues like that : 

            drawer.open = !drawer.open;
            if (drawer.open) setTimeout(function () {
                var drawerDom = document.querySelector('.mdc-drawer');
                drawerDom.classList.remove("mdc-drawer--animate");
                drawerDom.classList.remove("mdc-drawer--opening");
            }, 300)

**Comment by abhiomkar** [comment] 2019-02-04 16:38
Thanks for reporting this issue!

Can you please provide clear reproducible steps? Please see this example of drawer on [stackblitz](https://stackblitz.com/edit/mdc-drawer-demo) for your reference.

**Comment by kfranqueiro** [comment] 2019-02-13 15:44
Given no further response, we're closing this issue since we're unable to reproduce it.

**Closed by kfranqueiro** 2019-02-13 15:44 UTC
