### ISSUE TITLE
[MDCSlider] Discrete Slider styles problem, wenn Value > 1000

### ISSUE THREAD

**Issue by damian-mariachi-team** [material-components/material-components-web#5469] opened 2020-01-15 14:22 UTC
## Bug report
1. By discrete slider with custom range for example max-value more then 1000, value doesn't fit in bubble-thumb with it width
2. Value for example 1100 is displayed as a 1.100 with a dot.
That is not right. It should be 1100

### Steps to reproduce

1. Go to 'https://codepen.io/damian-mariachi-team/pen/xxbJmxd'
2. Click on 'thumb'
3. See value in 'bubble'

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | @4.0.0
| Browser          | Chrome
| Operating System | Windows 10

**Comment by asyncLiz** [comment] 2020-01-15 17:05
Duplicate of #4134. This will be fixed when slider is updated to the [current spec](https://material.io/components/sliders), which uses a tooltip instead of the bubble.

**Closed by asyncLiz** 2020-01-15 17:05 UTC
Labels: bug

**Comment by jimyhdolores** [comment] 2020-08-16 23:48
Hello @asyncLiz   any news about this? I have the same problem

**Comment by asyncLiz** [comment] 2020-08-17 19:28
@jimyhdolores please see my comment above, which mentions this issue is a duplicate of #4134. You can subscribe to that issue for updates.
