### ISSUE TITLE
npm install --save material-components-web  do not contain `@material`

### ISSUE THREAD

**Issue by eromoe** [material-components/material-components-web#1107] opened 2017-08-10 08:14 UTC
Hi, 

Due to error of `@import "material-components-web/material-components-web";`
(https://github.com/material-components/material-components-web/issues/1106)

I tried to use below code:
```
@import "~material-components-web/material-components-web.scss";
```
This does work, but got another error:

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./no
de_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap
!./app/styles/main.scss
Module build failed:
undefined
^
      File to import not found or unreadable: @material/animation/mdc-animation.

Parent style sheet: E:/Project/allproject_git/annotator/node_modules/material-co
mponents-web/material-components-web.scss
      in E:\Project\allproject_git\annotator\node_modules\material-components-we
b\material-components-web.scss (line 17, column 1)
 @ ./app/styles/main.scss 4:14-224 13:2-17:4 14:20-230
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/ap
p.js
```

Then I look into the folder , there is no `@material` :

![image](https://user-images.githubusercontent.com/3938751/29160926-c306d310-7de6-11e7-9840-940270ebd4ab.png)

I installed this lib by `npm install --save material-components-web`.  How can I install `material-components-web` with `@material` ?

**Comment by eromoe** [comment] 2017-08-10 08:25
Ok, I found `@material` is under `node_modules` . So it is by import problem too...

**Comment by acdvorak** [comment] 2017-08-11 04:34
This issue appears to be a duplicate of #1106

**Closed by acdvorak** 2017-08-11 04:34 UTC
