### ISSUE TITLE
[MDCDataTable] Row Border Overlap When Using Colspan

### ISSUE THREAD

**Issue by RacerDelux** [material-components/material-components-web#6890] opened 2021-02-26 15:47 UTC
## Bug report
Setting colspan on a `<td>` causes overlapping table borders

### Code Example
https://codepen.io/racerdelux/pen/qBqxpwQ

### Actual behavior
When you set a colspan, you can visually see the borders on the table rows overlap and darken

### Expected behavior
For colspan to not cause style issues with table borders

### Screenshots
![image](https://user-images.githubusercontent.com/2667344/109321591-f467f780-7816-11eb-99d0-eeff33bb8376.png)
(Look at the borders on the top and bottom of the "Extra Info Here" rows)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Google Chrome          | 88.0.4324.190
| Windows 10 | Version	10.0.18363 Build 18363

**Comment by asyncLiz** [comment] 2021-02-26 20:08
Related: b/179268158

**Comment by abhiomkar** [comment] 2021-02-26 22:28
This seems to be a browser specific bug. I'm able to reproduce this only in Chrome browser. (Tested on Safari & FF it looks fine).

@RacerDelux Can you try overriding row's border color to use hex value instead of rgba()?

```css
.mdc-data-table__row {
  border-top-color: #e0e0e0;
}
```

Example: https://codepen.io/abhiomkar/pen/bGBLmzY?editors=1100

**Comment by RacerDelux** [comment] 2021-03-01 17:34
> This seems to be a browser specific bug. I'm able to reproduce this only in Chrome browser. (Tested on Safari & FF it looks fine).
> 
> @RacerDelux Can you try overriding row's border color to use hex value instead of rgba()?
> 

This indeed worked like a charm. Looks like chrome has a bug using rgba().

Updated Pen with fix (tested to work in chrome).


![image](https://user-images.githubusercontent.com/2667344/109534973-95f28180-7a81-11eb-924e-53f67b533250.png)

**Comment by abhiomkar** [comment] 2021-03-02 20:14
Thanks for verifying!

I'm going to close this issue for now since this is a browser specific bug. There seems to be [bug already filed](https://bugs.chromium.org/p/chromium/issues/detail?id=769730&q=colspan%20border%20rgba&can=2) on Chrome browser to fix this issue.

**Closed by abhiomkar** 2021-03-02 20:14 UTC
Labels: backlog, bug
