### ISSUE TITLE
Select-Menus don't display links

### ISSUE THREAD

**Issue by Loggan08** [material-components/material-components-web#1338] opened 2017-09-21 18:22 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Feature Requests

> If you're interested in requesting a new component or proposing UX changes to an existing
> component, please read our [Component Request Policy](https://github.com/material-components/material-components/blob/develop/COMPONENTS_REQUEST_POLICY.md) before opening an issue.

If you have an idea for a new feature, we'd love to hear about it! Please provide enough
information regarding the feature such that we'll be able to evaluate the appropriateness and
feasibility of your request. Try to be as specific as possible regarding your motivation, use-case,
and potential API or affects on other APIs (where applicable). The more detailed your proposal is,
the easier it will be for us to understand and evaluate it. [This Meta.SE answer](http://meta.stackexchange.com/a/259196) also contains great general guidelines for writing
feature requests.

If you'd like to work on a component, please ensure that you *submit an Engineering Outline before
submitting a pull request*. You can read more about this in our [contributing docs](https://github.com/material-components/material-components-web/blob/master/CONTRIBUTING.md#building-components).

MDC-Web is still under active development. You can see our current progress on [master](https://github.com/material-components/material-components-web/tree/master) as well as an overview of the direction we're headed in our [developer guide](https://github.com/material-components/material-components-web/blob/master/docs/DEVELOPER.md).

If you're interested in information for a specific component, check out our [component issues](https://github.com/material-components/material-components-web/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Av2-component) to see which milestone it's associated with and subscribe to updates to it. If an issue has the `in-tracker` label, you can also take a look at our [public Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011) for a rough estimate of when we'll get to it.

Our team prioritizes responding to as many engineering and user experience questions as possible. We do not support responses to questions outside of these areas at this time.

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

0.21.1

### What browser(s) is this bug affecting?

Chrome 61

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

put a link inside  li class="mdc-list-item" role="option" tabindex="0"

### What is the expected behavior?

Select-Menus display links

### What is the actual behavior?

Select'menus do not display links.

**Comment by amsheehan** [comment] 2017-09-25 18:16
We could not reproduce this. Could you send over a codepen or js fiddle?

**Comment by Loggan08** [comment] 2017-09-25 18:58
https://lolupdater.com/?p=test

Let me know when you are finished looking so I can remove the test-page.

> 
> <h2>LINKS</h2>
> <div id="js-select" class="mdc-select" role="listbox" tabindex="0">
>   <span class="mdc-select__selected-text"><font color=white>TEST</font></span>
>   <div class="mdc-simple-menu mdc-select__menu">
>     <ul class="mdc-list mdc-simple-menu__items">
>       <li class="mdc-list-item" role="option" tabindex="0">
>         <a href="/">Home</a>
>       </li>
>     <li class="mdc-list-item" role="option" tabindex="0">
>         <a href="/shop/index.php">Shop</a>
>       </li>
>     </ul>
>   </div>
> </div>
> <br>
> <br>
> <br>
> <br>
> <h2>NO LINKS</h2>
> <div id="js-select2" class="mdc-select" role="listbox" tabindex="0">
>   <span class="mdc-select__selected-text"><font color=white>TEST</font></span>
>   <div class="mdc-simple-menu mdc-select__menu">
>     <ul class="mdc-list mdc-simple-menu__items">
>       <li class="mdc-list-item" role="option" tabindex="0">
>         HOME
>       </li>
>     <li class="mdc-list-item" role="option" tabindex="0">
>         SHOP
>       </li>
>     </ul>
>   </div>
> </div>
> <br>
> <br>
>     <script>
>       (function() {
>         var MDCSelect = mdc.select.MDCSelect;
>         var root = document.getElementById('js-select');
>         var currentlySelected = document.getElementById('currently-selected');
>         var select = MDCSelect.attachTo(root);
>         root.addEventListener('MDCSelect:change', function() {
>           var item = select.selectedOptions[0];
>           var index = select.selectedIndex;
>           currentlySelected.textContent = '"' + item.textContent + '" at index ' + index +
>            ' with value "' + select.value + '"';
>         });
> 
>       })();
> 
> 
>      (function() {
>         var MDCSelect = mdc.select.MDCSelect;
>         var root = document.getElementById('js-select2');
>         var currentlySelected = document.getElementById('currently-selected');
>         var select = MDCSelect.attachTo(root);
>         root.addEventListener('MDCSelect:change', function() {
>           var item = select.selectedOptions[0];
>           var index = select.selectedIndex;
>           currentlySelected.textContent = '"' + item.textContent + '" at index ' + index +
>            ' with value "' + select.value + '"';
>         });
> 
>       })();
>     </script>

**Comment by amsheehan** [comment] 2017-09-25 19:08
Your example is styling links such that they end up having the same `color` as the background of the list element. This is not a bug in MDC Web. Closing.

![screen shot 2017-09-25 at 3 07 37 pm](https://user-images.githubusercontent.com/1578263/30826139-664b6f28-a203-11e7-8bf7-d7c3aa5d1ba8.png)

**Closed by amsheehan** 2017-09-25 19:08 UTC
