### ISSUE TITLE
mdc text field textarea text is hidden behind label whitespace

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#3032] opened 2018-07-05 10:50 UTC
### What MDC Web Version are you using?

> 0.37.0

### What browser(s) is this bug affecting?

> Chome Browser

> Type the long text on textarea.
> Textarea padding will not take and overlap with the label.

### What is the expected behavior?

> Textarea text should not overlap with the label.

### What is the actual behavior?

> Textarea text is overlapping with the label.

![image](https://user-images.githubusercontent.com/12517126/42319284-191c5cf8-806f-11e8-8fde-4af3f045239d.png)

**Comment by williamernest** [comment] 2018-07-06 21:01
@ruwaroshan Thanks for filing this issue. This issue is being tracked in #2278.

**Comment by williamernest** [comment] 2018-07-09 21:35
@ruwaroshan I was mistaken, this issue was resolved with #2392 . Can you verify your version and provide a codepen ? This issue should have been resolved in `0.36.0`.

**Comment by kfranqueiro** [comment] 2018-07-09 21:38
Here's a [codepen](https://codepen.io/kfranqueiro/pen/GBKeOJ) running against the latest release - I can't reproduce it here, but if you can, or if you can fork the codepen to make the issue reproducible, then we can look into this. Thanks!

**Comment by zikhan** [comment] 2018-07-16 15:37
Using MS Edge, I noticed this oddity with the textarea. You can edit text hidden behind the label whitespace. It also happens in @kfranqueiro's codepen. In the picture, taken from the demo site, you can see the cursor on the same line as the label, but editing the contents of the textarea.
![image](https://user-images.githubusercontent.com/8488326/42767965-e7b29646-88e3-11e8-9222-f3a93cafd20a.png)

**Comment by abhiomkar** [comment] 2018-07-17 14:32
Thanks @zikhan for reporting the issue.

The original issue filed by @ruwaroshan seems like a different issue where text is being overlapped with label which is not reproducible.

Adding this to tracker to fix text being hidden behind label issue. Also renaming this issue to match.

**Closed** 2018-12-04 22:38 UTC
Labels: icebox
