### ISSUE TITLE
[MDC-List] Non interactive list still grabs focus

### ISSUE THREAD

**Issue by CiriousJoker** [material-components/material-components-web#4438] opened 2019-02-20 15:37 UTC
### What MDC Web Version are you using?

> 0.44.1

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

If I open an mdc-menu with an mdc-list inside, the first list item is selected. However, when I change the list to be non-interactive, it still steals focus from the currently focused element.

### What is the expected behavior?

> Non-interactive lists should not grab focus in any way

### What is the actual behavior?

> The first list item still gets focused, even if it's invisible

[Here's the Codepen](https://codepen.io/ciriousjoker/pen/JxVEga)

**Comment by acdvorak** [comment] 2019-02-21 20:25
Thanks for filing this issue! 😀 

Would it solve your problem if we fixed #3922?

I'm curious why you need a non-interactive list inside of a menu. The `--non-interactive` class disables keyboard functionality, which is generally inadvisable from an accessibility perspective.

Can you tell us a little bit more about your use case? Are you trying to implement search suggestions, typeahead, or something like that?

**Comment by CiriousJoker** [comment] 2019-02-22 00:23
Yes, I created a Textfeld that opens a menu when you click on it. Then, the user can filter the list inside the menu. When the user clicks on the item, it's text is copied to the textfield.

I don't technically need a non-interactive list as I know it's bad, but I absolutely need a way to disable focus grabbing on the list, otherwise the user opens the menu just to close it by accident while trying to focus the textfield again.

**Comment by acdvorak** [comment] 2019-02-25 19:42
Cool, I'll close this as a duplicate of #3922 then. Thanks! 😀

**Closed by acdvorak** 2019-02-25 19:42 UTC

**Comment by CiriousJoker** [comment] 2019-02-26 11:44
But it isn't a duplicate, both just happen to solve my underlying problem
