### ISSUE TITLE
CSS Custom Properties not fully supported

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-components-web#5242] opened 2019-11-07 23:08 UTC
This is a tracking issue for CSS Custom Property theming fixes.

**Comment by azakus** [comment] 2019-11-08 00:22
Also related to #3685

**Comment by jamesmfriedman** [comment] 2019-11-13 16:55
Adding a var for border-radius globally that elements inherited would be a good one :). 

Vars for transition speeds

I’ve also put forth several proposals for how to handle runtime color alpha, basically you can store a var as a comma separated value

`—color: 255, 255, 255`

And then use it like this. 

`color: rgba(var(—color), 0.8)`

That would allow the same functionality that sass Mixins provide.

**Comment by zbot473** [comment] 2019-11-24 15:49
Is there a workaround for styling input labels?

**Comment by jamesmfriedman** [comment] 2019-11-24 17:04
Yes, for now you can target the label directly with a css rule and fix the color, or if you’re using SASS you can override the color variables and it will build the appropriate CSS

**Comment by zbot473** [comment] 2019-11-26 02:50
I did end up using that method, but unfortunately, I cannot use sass.
If only the RasPi supported node-sass...

**Comment by una** [comment] 2019-12-17 21:17
A few items listed out with potential resolutions: #5349

**Comment by drzony** [comment] 2020-04-15 02:37
In mwc-textfield the following properties do not work:
--mdc-text-field-idle-line-color
--mdc-text-field-hover-line-color
--mdc-text-field-disabled-line-color
The line is covered by mdc-line-ripple which is styled without custom properties

**Comment by asyncLiz** [comment] 2020-04-15 16:48
@drzony the textfield custom properties were fixed in #1044, but haven't been released yet. You can install the `canary` version from npm to test them out.

**Comment by drzony** [comment] 2020-04-15 20:01
@asyncLiz Thanks, canary seems to be working

**Comment by asyncLiz** [comment] 2020-05-01 17:15
From https://github.com/material-components/material-components-web/issues/5878:

The text field's floating label is always purple, even when `--mdc-theme-secondary` or `--mdc-theme-primary` is set to custom colors.

https://material-components.github.io/material-components-web-catalog/#/component/text-field

https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

Note that this problem of "hard-coded" colors exists also for:

* `mdc-select` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/select )
* `mdc-snackbar` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/snackbar )
* `mdc-drawer` / `.mdc-list-item--activated` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/drawer )

### Steps to reproduce

1. Go to https://material-components.github.io/material-components-web-catalog/#/component/text-field
2. Open the web inspector, and add a `style` attribute to the `body` or `html` element, in order to change the theme's primary and secondary color CSS properties, for example: `style="--mdc-theme-primary: magenta; --mdc-theme-secondary: orange;"`

### Actual behavior

The floating label is always purple

### Expected behavior

The floating label should have the color of either primary or secondary

### Screenshots

![MDC_floatingLabel](https://user-images.githubusercontent.com/625201/80789469-f83dd580-8b83-11ea-92c2-0ff85aa5478b.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0
| Browser          | Firefox (latest)
| Operating System | MacOS 10.15.4

### Possible solution

My current workaround is to override the following selectors:

```
/* MDC select floating label */
.mdc-select:not(.mdc-select--disabled).mdc-select--focused .mdc-floating-label,

/* MDC drawer list item text */
.mdc-drawer .mdc-list-item--activated .mdc-list-item__graphic,

/* MDC drawer list item leading icon */
.mdc-drawer .mdc-list-item--activated,

/* MDC snackbar */
.mdc-snackbar__action:not(:disabled),

/* MDC textfield floating label */
.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label
{
    color: var(--mdc-theme-secondary); /* or primary */
}
```

**Comment by danielweck** [comment] 2020-06-28 11:32
Heads-up: bug tested and reproduced (as per the above comment) with the latest version deployed at https://material-components.github.io

**Comment by asyncLiz** [comment] 2020-06-28 19:30
@danielweck keep in mind that the catalog is still on v4 and is not updated to the latest version, nor has this issue been fixed in the latest version.

**Comment by asyncLiz** [comment] 2022-06-17 18:59
Closing this as obsolete with Material 3 and token support

**Closed by asyncLiz** 2022-06-17 18:59 UTC
Labels: bug, Epic
