### ISSUE TITLE
Broken textfield autocomplete, making the complete library unusable.

### ISSUE THREAD

**Issue by ranjeet-choudhary** [material-components/material-components-web#3174] opened 2018-07-23 14:28 UTC
After autosuggest, Sometimes clicking on input to enter data stops working.
![image](https://user-images.githubusercontent.com/13473684/43081195-1c25b22a-8eaf-11e8-9167-b3b4268a1290.png)
After hovering on textfield autocomplete, the suggested data in yellow is not removed. Even if i have not selected the data, just by hovering its getting stuck and stops any further input.
![image](https://user-images.githubusercontent.com/13473684/43082556-f5e247e2-8eb1-11e8-9e56-ecdd1c88cf0a.png)
Chrome 67
"@material/textfield": "^0.37.1",

**Comment by ranjeet-choudhary** [comment] 2018-07-24 08:14
Looks like, this is due to web component, wrapping input inside component is creating this problem.
even for plain input tag wrapped inside component, the autosuggest fails until its inside form tag.

`
<form >
 <input name$="${name}" type$="${type}" placeholder$="${placeholder}" autocomplete$="${autocomplete}" disabled?="${disabled}"
			value="${value}" pattern="${pattern}" required?="${required}" type="text" id="text-field" aria-labelledby="text-label"
			on-change="${(e) => this._forwardEvent(e)}" on-input="${(e) => this._forwardEvent(e)}">
</form>
`

**Comment by abhiomkar** [comment] 2018-07-24 16:15
I'm not able to reproduce this issue on text field with native autocomplete. I'm able to change the input on hover and also on select of suggestions dropdown as expected.

Can you try removing on-change and on-input callbacks from your example and see if the issue still persists?

**Comment by ranjeet-choudhary** [comment] 2018-07-24 18:23
@abhiomkar try inside web component

**Comment by abhiomkar** [comment] 2018-07-24 20:06
Thanks for pointing this issue.

I'm able to repro this in material web components catalog. I would track this in material-components-web-components/issues. Since you've already filed an issue there, I'm closing this one to avoid duplicates.

**Closed by abhiomkar** 2018-07-24 20:06 UTC
