### ISSUE TITLE
Console error when installed @material/dialog

### ISSUE THREAD

**Issue by jperera84** [material-components/material-components-web#2901] opened 2018-06-07 20:58 UTC
### What MDC Web Version are you using?
Material Dialog
"@material/dialog": "^0.36.0"

### What browser(s) is this bug affecting?

Chrome Canary. Version 69.0.3450.0 (Official Build) canary (64-bit)

### What OS are you using?

MAC OS, Sierra

### What are the steps to reproduce the bug?

1. Install the npm install @material/dialog.
     1.1. Getting the following warnings:
            npm WARN @babel/plugin-transform-classes@7.0.0-beta.35 requires a peer of 
            @babel/core@7.0.0-beta.35 but none is installed. You must install peer dependencies yourself.
              npm WARN @babel/plugin-transform-classes@7.0.0-beta.35 requires a peer of 
             @babel/core@7.0.0-beta.35 but none is installed. You must install peer dependencies yourself.
2. In a LitElement webcomponent I added the following reference:
            ` import { MDCDialog } from "@material/dialog";`
3. Added the html:
```
<aside id="my-mdc-dialog" class="mdc-dialog" role="alertdialog" aria-labelledby="my-mdc-dialog-label" aria-describedby="my-mdc-dialog-description">
                <div class="mdc-dialog__surface">
                    <header class="mdc-dialog__header">
                        <h2 id="my-mdc-dialog-label" class="mdc-dialog__header__title">
                            Use Google's location service?
                        </h2>
                    </header>
                    <section id="my-mdc-dialog-description" class="mdc-dialog__body">
                        Let Google help apps determine location. This means sending anonymous location data to Google, even when no apps are running.
                    </section>
                    <footer class="mdc-dialog__footer">
                        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Decline</button>
                        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept">Accept</button>
                    </footer>
                </div>
                <div class="mdc-dialog__backdrop"></div>
            </aside>
```
4. Added the instantiation of the dialog:
```
async _firstRendered() {
        await this.renderComplete;
        this.dialog = new MDCDialog(this.shadowRoot.querySelector('#my-mdc-dialog'));
    }
```
5. Refresh the page.

### What is the expected behavior?

When I refresh the page it doesn't show any console error.

### What is the actual behavior?

I'm getting the following error in the browser console:

> Uncaught (in promise) SyntaxError: The requested module '../../focus-trap/index.js' does not provide an export named 'default'

### Any other information you believe would be useful?

I have been used other components like TextField, Radiobutton, and Button and everything works fine.
When I deleted the dialog reference everything works fine.

Also I'm getting the following warning from Visual Studio Code when I over the @material/dialog import statement:

```
[ts]
Could not find a declaration file for module '@material/dialog'. '/Users/joser.pereramorales/Documents/Projects/web/miTienda/miTienda-app/node_modules/@material/dialog/index.js' implicitly has an 'any' type.
  Try `npm install @types/material__dialog` if it exists or add a new declaration (.d.ts) file containing `declare module 'material__dialog';`
```
I notice in the folder tree in node_modules this is what is happening when you install the dialog component:
![img](https://user-images.githubusercontent.com/13193138/41184525-d17f8f08-6b4e-11e8-8030-ca0d0029034a.png)

**Comment by kfranqueiro** [comment] 2018-06-11 21:25
One thing I find odd about your folder tree is it looks like it's completely missing `focus-trap` and `tabbable`?

Here's what the installed dependencies look like simply from installing `@material/dialog`:

```
└─┬ @material/dialog@0.36.0
  ├── @material/animation@0.34.0
  ├── @material/base@0.35.0
  ├─┬ @material/elevation@0.35.0
  │ ├── @material/animation@0.34.0 deduped
  │ └── @material/theme@0.4.0 extraneous
  ├─┬ @material/ripple@0.36.0
  │ ├── @material/animation@0.34.0 deduped
  │ ├── @material/base@0.35.0 deduped
  │ └── @material/theme@0.35.0 deduped
  ├── @material/rtl@0.36.0
  ├── @material/theme@0.35.0
  ├── @material/typography@0.35.0
  └─┬ focus-trap@2.4.6
    └── tabbable@1.1.3
```

Is it possible you have a different version of focus-trap somewhere else that doesn't have the expected exports?

Meanwhile, the warnings you encountered while installing seem unrelated to MDC Web, or at least we don't have anything versioned 7.0.0-beta.35. That sounds like it might be babel-related?

We also don't have typescript declarations (I believe someone contributed some to DefinitelyTyped but I'm not sure how up-to-date they are), which would explain the VS Code warning.

**Comment by kfranqueiro** [comment] 2018-06-11 21:25
I should probably also point out that there is a logged issue which someone encountered when attempting to use MDC Dialog within a web component, FYI: https://github.com/material-components/material-components-web/issues/2212

**Comment by jperera84** [comment] 2018-06-11 21:56
Hello,
This is my package.json file with the dependencies:
  "dependencies": {
    "@material/button": "^0.35.0",
    "@material/dialog": "^0.36.0",
    "@material/form-field": "^0.35.0",
    "@material/linear-progress": "^0.35.0",
    "@material/radio": "^0.35.0",
    "@material/tabs": "^0.35.0",
    "@material/textfield": "^0.35.2",
    "@polymer/app-layout": "^3.0.0-pre.19",
    "@polymer/lit-element": "^0.5.0",
    "@webcomponents/webcomponentsjs": "^2.0.0",
    "pwa-helpers": "^0.8.2",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1"
  },
  "devDependencies": {
    "axe-core": "^3.0.0",
    "chai": "^4.1.2",
    "mocha": "^5.1.0",
    "pixelmatch": "^4.0.2",
    "polymer-cli": "^1.7.1",
    "polyserve": "^0.27.0",
    "prpl-server": "^1.1.0",
    "puppeteer": "^1.4.0",
    "renamer": "^0.6.1",
    "replace": "^1.0.0",
    "wct-browser-legacy": "^1.0.0"
  }

I deleted the node_modules folder and reinstall everything (npm install) again. but it keeps installing in the same way I showed in the picture in my first post, it doesn't seems to be correct the installation, I've never seen before that a module creates a new mode_module folder inside it...

**Comment by jperera84** [comment] 2018-06-11 22:14
Also this is the package-lock.json:
```
"@material/dialog": {
      "version": "0.35.2",
      "resolved": "https://registry.npmjs.org/@material/dialog/-/dialog-0.35.2.tgz",
      "integrity": "sha512-mUZqqI8b4sIT44gEu6ItLVbxX3d2K13GxBk1yMqLELh48G73k/AZdXHYm2lY/LPB+wRraKg/JG6Av1Jg2hMSlw==",
      "requires": {
        "@material/animation": "^0.34.0",
        "@material/base": "^0.35.0",
        "@material/elevation": "^0.35.0",
        "@material/ripple": "^0.35.0",
        "@material/rtl": "^0.35.0",
        "@material/theme": "^0.35.0",
        "@material/typography": "^0.1.1",
        "focus-trap": "^2.3.0"
      },
```

The focus-trap version is not the same that you have installed right?

**Comment by jperera84** [comment] 2018-06-11 22:32
I fixed: `"focus-trap": "^2.3.0" ` to `focus-trap@2.4.6` in my package-lock.json then delete the node_modules folder and reinstall everything again... Still no working

**Comment by kfranqueiro** [comment] 2018-06-18 22:11
When I install using your list of dependencies, I also get focus-trap@2.4.6 under top-level node_modules.

I'm wondering if this is not so much a npm issue as a toolchain issue... how are you transpiling/serving your JS? The fact that you're getting this error in the _browser_ console in particular has me wondering, unless that's being forwarded from a dev server.

We're using MDC Dialog in our MDC Web Catalog repository, currently locked to focus-trap@2.4.5, with no issues. AFAICT the index.js in focus-trap hasn't changed in 2.4.6. One thing worth noting is that we specifically configure `babel-loader` to `include` both the app source path and `node_modules/@material`.

**Comment by kfranqueiro** [comment] 2018-07-02 20:23
Given no further response, I'm going to close this issue. This issue should be resolved as long as you ensure your toolchain is configured to build the ES2015 sources of the MDC modules you're depending on.

**Closed by kfranqueiro** 2018-07-02 20:23 UTC

**Comment by mkay581** [comment] 2018-08-25 20:32
@kfranqueiro unfortunately I am having this same issue. The problem is that the `@material/dialog` component [uses `focus-trap` package](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/util.js#L24) which is [not compatible with browser es6 import/exports](https://github.com/davidtheclark/focus-trap/issues/30).  I am not using babel, rollup, or otherwise any build process via Polymer/Lit and because this package uses `focus-trap`, it makes `@material/dialog` unusable unfortunately.

**Comment by kfranqueiro** [comment] 2018-08-27 16:15
@mkay581 if you're not using a build process, then you'd be consuming `dist/mdc.dialog.js` which should have everything bundled, right? Could you file a new issue with more details?

**Comment by mkay581** [comment] 2018-08-28 15:17
@kfranqueiro no problem, I will do that. I was actually trying to reproduce using stackblitz but I'm unable to point to the `dist/mdc.dialog.js` file since it doesn't look like it's checked in. Where would I be able to reference that file? Once I do that and I can reproduce, I will open a new issue.

**Comment by kfranqueiro** [comment] 2018-08-28 15:26
If you've installed the package from npm, then `dist/mdc.dialog.js` should exist within the `mdc-dialog` folder under `node_modules`. It doesn't exist within the source repository without running `npm run dist` and `node scripts/cp-pkgs`.

**Comment by mkay581** [comment] 2018-08-28 16:18
@kfranqueiro opened #3444
