### ISSUE TITLE
Slider on Safari ios 13 does not drag

### ISSUE THREAD

**Issue by berenddeboer** [material-components/material-components-web#5161] opened 2019-10-07 20:46 UTC
## Bug report
On iPhone, when trying to drag the blue dot, it always jumps back to a lower number. I can tap to each number, but it won't let me drag. 

This seems to be new behaviour. Can reproduce this behaviour on BrowserStack with the ios13 beta they have, but not with earlier versions or different iphone models.

Chrome on the same phone/ios is fine.

### Steps to reproduce
1. Go here: https://material-components.github.io/material-components-web-catalog/#/component/slider
2. Attempt to drag slider.

### Actual behavior
Dot jumps back to starting number.

### Expected behavior
Dot stays on portion of slider where you stopped dragging.

### Your Environment:
iphone 6, version 11.4.1, iOS 13.1.2, browser Safari.

**Comment by stephanemagnenat** [comment] 2020-08-13 05:36
I also experience this bug on Safari on iOS 13.6 on iPad 7th generation.

The bug happens not always, but sometimes when I drag the slider and release it, it goes back approximately to the previous position, producing two change events: one with the new position and one with the old one. Obviously, this makes the slider close to unusable.

**Comment by asyncLiz** [comment] 2020-08-24 18:39
@stephanemagnenat our slider has been updated, and the catalog version you are referencing in the video is out of date. Can you try the following demo and see if you have any issues?

https://jsbin.com/qikudukiha/edit?html,output

**Comment by stephanemagnenat** [comment] 2020-08-25 07:10
Thank you for your answer! I could not reproduce the issue in the linked jsbin. Was that fixed in e844443878b9711a306e72b951c7ea931b17d837?

**Comment by asyncLiz** [comment] 2020-08-25 18:23
It is more likely that the slider was fixed in our rewrite of the M2 slider in https://github.com/material-components/material-components-web/pull/6231. We have quite a few old slider issues that need to be closed since the rewrite. I'll go ahead and mark this one as closed since it's working on the new version.

**Closed by asyncLiz** 2020-08-25 18:23 UTC
Labels: bug, needs-response
