### ISSUE TITLE
Snackbar will not be hidden when the visibilitychange is fired after call snackbar.show()

### ISSUE THREAD

**Issue by yuheiy** [material-components/material-components-web#1947] opened 2018-01-12 01:58 UTC
### What MDC-Web Version are you using?

0.28.0

### What browser(s) is this bug affecting?

Safari 11.0.2 (also iOS Safari)

### What OS are you using?

Mac OS X 10_13_2

### What are the steps to reproduce the bug?

If I switch the browser tab after call `snackbar.show()`, Snackbar will not be hidden.

1. Go to https://material-components-web.appspot.com/snackbar.html
1. Click Show button (`#show-snackbar`)
1. Make current the tab background
1. Make the tab foreground

**Comment by acdvorak** [comment] 2018-01-18 22:06
Duplicate of #1398

**Comment by acdvorak** [comment] 2018-01-18 22:06
Thanks for filing this issue! 😀

**Closed by acdvorak** 2018-01-18 22:06 UTC
