### ISSUE TITLE
[suggestion / possible bug?] mdc-layout-grid--span-0-phone shouldn't have extra margin

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4118] opened 2018-11-28 07:23 UTC
## Bugs

Having `<div class="mdc-layout-grid--span-1-desktop mdc-layout-grid--span-0-phone"></div>` currently adds extra margin to areas where it should just display nothing.

### What MDC Web Version are you using?

> 0.41.1

### What browser(s) is this bug affecting?

> Chrome version 70.0.3538.110 (Official Build) (64-bit)

### What OS are you using?

> MacOS 10.14.1

### What are the steps to reproduce the bug?

> Have a standard mdc-layout-grid that has custom values for desktop, tablet and mobile
> Make sure that the tablet and mobile divs have them set to 0
> Have some text in the main area that is gridded
> Shrink down the window to tablet or mobile size
> observe the text get moves down from the extra margin that the span-0 makes
>
> CodePen example [here](https://codepen.io/anon/pen/bQxPZX?editors=1000)

### What is the expected behavior?

> If the span is set to 0 for tablet or mobile, then no styles should be added

### What is the actual behavior?

> Extra margin is added pushing everything under it down.

### Any other information you believe would be useful?

Here are some pictures of the example (from the code pen exmaple)

Desktop view
<img width="1014" alt="screen shot 2018-11-28 at 8 13 11 pm" src="https://user-images.githubusercontent.com/26075792/49135282-23971200-f34b-11e8-90ed-4a7cf021e370.png">

Mobile view
<img width="594" alt="screen shot 2018-11-28 at 8 13 24 pm" src="https://user-images.githubusercontent.com/26075792/49135317-37427880-f34b-11e8-842f-667e178b89b2.png">
See the extra gird lines above and below the test card. those are the things that add the extra margin.

This could be how you intended it to work, and I could just be using the layout grid very wrong, but I thought I would just say something anyway just in case it is not intended.

**Comment by kfranqueiro** [comment] 2018-11-28 14:42
Thanks for the report. I suspect this is a duplicate of #2270, and what you're experiencing is that span-0 isn't being recognized.

**Comment by CyborgSemon** [comment] 2018-11-29 09:47
The solution that i just made for it was just to have a `@media` query in the css and make `mdc-layout-grid__cell--span-0-phone` have `display: none;` when it jumps into "phone mode"
That seemed to get the job done

**Comment by williamernest** [comment] 2018-12-04 19:09
Closed as duplicate. Tracking in #2270

**Closed by williamernest** 2018-12-04 19:09 UTC
