### ISSUE TITLE
mdc-button__ripple {z-index} should be -1

### ISSUE THREAD

**Issue by leecjson** [material-components/material-components-web#6515] opened 2020-10-05 21:42 UTC
The issue which ripple layer could cover the text. It is not right.
```css
.mdc-button__ripple {
  z-index: -1;
}
```

**Comment by patrickrodee** [comment] 2020-10-09 18:31
Hey Li, thanks for filing this bug. Do you have a link to the section in the Material.io spec that lead to you file this bug?

**Comment by leecjson** [comment] 2020-10-14 10:23
@patrickrodee HI.  I'm not familiar with it.

I think it is a visual error, i find it when i try to change the ripple color in devtools. My final solution is set global css to override it.

```scss
// bugfix
.mdc-button {
  & > :not(.mdc-button__ripple) {
    z-index: 1;
  }
}
```

**Comment by joyzhong** [comment] 2020-10-16 13:46
Closing, I believe this is working as intended. Please reopen with a reference to the material.io spec if this is not the case.

**Closed by joyzhong** 2020-10-16 13:46 UTC
Labels: bug, needs-response
