### ISSUE TITLE
Material Components tabs

### ISSUE THREAD

**Issue by sylvaincordiere** [material-components/material-components-web#2861] opened 2018-06-02 00:57 UTC
Hi I try to make a tab with material Component but the problem is that the content of the tabs appears even when the corresponding tabs aren't clicked. Item One should appears only when the item one is click but here the three item are show everytime. I follow there Markup for Dynamic view switching so I don't know what's going wrong

[codepen](https://codepen.io/anon/pen/aKvyeV)

**Comment by patrickrodee** [comment] 2018-06-04 20:06
Hey there! Thanks for submitting an issue.

It looks like you copied this from the deprecated demos on https://material-components-web.appspot.com/tabs.html. In that case, all you're missing is the following CSS:

```
.panel {
  display: none;
}

.panel.active {
  display: block;
}
```

I [updated your demo](https://codepen.io/patty/pen/zaqvBa) with the missing CSS. I'm going to close this since it's not a bug with MDC Web functionality.

Thanks!

**Closed by patrickrodee** 2018-06-04 20:06 UTC
