### ISSUE TITLE
[mdc-select/mdc-list] Broken SASS compilation after V5

### ISSUE THREAD

**Issue by raphaelsantos** [material-components/material-components-web#5631] opened 2020-02-19 21:48 UTC
In my components SASS file I import these:
```
@import '@material/list/mdc-list';
@import '@material/menu-surface/mdc-menu-surface';
@import '@material/menu/mdc-menu';
@import '@material/select/mdc-select';
```

it used to work, but now with v5 I'm getting this error:

```
{
  "status": 1,
  "file": "../../node_modules/@material/list/mdc-list.scss",
  "line": 22,
  "column": 10,
  "message": "Invalid CSS after \"@include mixins\": expected 1 selector or at-rule, was \".core-styles;\"",
  "formatted": "Error: Invalid CSS after \"@include mixins\": expected 1 selector or at-rule, was \".core-styles;\"\n        on line 22 of ../../node_modules/@material/list/mdc-list.scss\n        from line 1 of src/sass/drop-down.scss\n>> @include mixins.core-styles;\n\n   ---------^\n"
}

```

I'm using the latest version of `node-sass`.

**Comment by DRiFTy17** [comment] 2020-02-20 14:11
@raphaelsantos `node-sass` doesn't support `@use` sass modules yet... If you switch to the dart implementation by installing the `sass` package (should be interchangeable API-wise) then it will work. The only issue with this is that the compilation is a lot slower on large libraries, and it forces consuming applications of our own sass libraries (that take a dependency on MDC) to also use dart sass.

**Comment by asyncLiz** [comment] 2020-02-28 19:39
Closing since MDC switched to Sass modules in v5, so this is working as intended. The recommendation for client libraries that consume MDC is to use Dart `sass` for compilation.

**Closed by asyncLiz** 2020-02-28 19:39 UTC
Labels: bug

**Comment by robbertvancaem** [comment] 2021-03-19 15:10
For anyone ending up here through Google, I had `node-sass` installed it and removed it by running `yarn remove node-sass`. Then, I had to install `sass` to make it work again. I did this by running `yarn add -D sass`
