### ISSUE TITLE
Patching native getters and setters for Checkbox causes React to misfire events.

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#4018] opened 2018-10-30 17:21 UTC
I'll try to keep my bedside manner, but this just killed half my day.

https://github.com/material-components/material-components-web/blob/2645aa4f43ae2ac10fa2acb904bfa1362657f378/packages/mdc-checkbox/foundation.js#L143

I'll do my best to explain the issue as it relates to React and RMWC. https://github.com/jamesmfriedman/rmwc/issues/312

- Somewhere deep in React's synthetic event system, it binds to onChange handlers. Don't ask me where it is, but it exists. I've seen the code. It pools them all at the document body (soon to be the React root)
- In what appears to be an attempt to fire the event animations deterministically, MDC has hijacked the setter and getter for the checkbox properties. I'm sure this has worked fine for Vanilla Web
- In React, after a programmatic update, React loses the ability to fire an onChange event on said checkbox.
- I used to wrap the vanilla js component in React. This issue came up, but it was resolved by fudging the event cycle with a RAF.
- Since 3.0, I've moved to doing the foundation integration the "right" way which is where this issue has come back to rear its ugly head and has not been fixable by any sort of scotch tape.
- As a last ditch effort, I've monkey patched MDCFoundation prototype and made `installPropertyChangeHooks_` and empty function which is the source of the evil. https://github.com/jamesmfriedman/rmwc/commit/3ffef39d527ce153821ee6595299e0a24650ab9c
- I still have animations on both controlled and uncontrolled checkboxes because I'm forcing my own internal `sync` method to be called on the native `change` event which in turn calls foundation.handleChange_() which calls transitionCheckState anyways which is what it looks like you were trying to do.
- Ahhhhh!

So why the heck not just listen to the change event?

**Comment by williamernest** [comment] 2018-10-30 17:42
This was added as a way of triggering the animations without having to use the component to change the checked value (where we would apply animation classes). Since the user could simply toggle the element by using a DOM (`document.querySelector('input[type="checkbox"]').checked = true;`) query, the implementation chose to insert itself into the `ProperyDescriptor` hooks for `set` so that any way the user changed the checked state of the checkbox the foundation methods (and animation classes) would be applied correctly.

**Comment by jamesmfriedman** [comment] 2018-10-30 17:58
I understand why they're there, it just causes a very real bug in React land.

**Comment by jamesmfriedman** [comment] 2018-10-30 17:58
Updated the title to reflect how I feel after a quick break ;).

**Comment by kfranqueiro** [comment] 2018-10-30 18:30
It's also worth noting that patching the events was likely to come in handy for #2949, so if we were to remove this we'd have to see if there's any other alternative way to fix that as well.

I was trying to remember if we had any other reasons for patching native properties other than supporting direct programmatic writes to those properties on the elements. I could fathom de-supporting that given that users should be encouraged to use our component APIs... Is this also helping to support e.g. browsers restoring checkbox state on refresh/back? (Could we get away with doing that during initialSyncWithDOM?)

**Comment by jamesmfriedman** [comment] 2018-10-30 19:03
Also, I know this error sounds really cryptic. I'd be happy to put a repro together to prove it, but It's hard to separate React from my implementation of Checkbox, from MDC. I'd hate for this to be a problem with how I have it implemented, but I just don't see how it's anything else.

**Comment by jamesmfriedman** [comment] 2018-10-31 14:47
Took a little bit of time to explore the differences in my implementation vs mat-react. Definitely two completely different approaches. A few things I found.

- Good news for the mat-react team, this bug is not present
- Bad news, I think the bug isn't present because the mat-react checkbox re-renders itself constantly which is going to objectively lead to performance issues in real world use.
- Checkbox Component mount
   - mat-react: 8 render cycles
   - rmwc: 2 render cycles
- Checkbox Change
  - mat-react: 17 render cycles
  - rmwc: 2 render cycles
- I bring this up because I believe the issue I filed is real, but react-mat isn't seeing it because the component is refreshing itself frequently.
- Since mat-react does not have this issue, you can feel free to close it and blame my implementation, but considering the fix is simply commenting out the getter / setter override I would say it is indeed a real issue, just one that might not be worth fixing if I'm the only one experiencing it. I can keep my prototype patch in my codebase as a permanent fix.

**Comment by kfranqueiro** [comment] 2018-10-31 14:56
Is there something even more specific within the getter/setter that are causing it, or is commenting the entire getter/setter the minimum required to resolve it for your case?

I'm a little concerned that we may end up needing the getter/setter in checkbox and also radio to resolve a state system issue, but I also respect that your implementation is actually doing things more efficiently (and possibly correctly).

**Comment by moog16** [comment] 2018-10-31 16:41
I remember that we talked about removing the getter/setter from the foundation and into the component. I partially did the easy ones in https://github.com/material-components/material-components-web/issues/3396. The issue is still open because of the native getter/setter. I'll work on this finishing it, which I don't think will result in a breaking change.

**Comment by jamesmfriedman** [comment] 2018-10-31 16:50
FYI, I just did some testing in other browsers. In  Chrome it broke on the 3rd try, in Safari it was outright broken and the checkbox couldn't change state at all.

I did find one more bug in my logic that fixed the safari issue, but the root issue remains. The issue occurs anytime you override the propertyDescriptor. It doesn't matter what you set the setter or getter to, just the simple fact of overriding it breaks. Without getting deep into React's code I can only venture guesses as to why. For testing, I stripped away as many abstractions as I could from RMWC and the issue remains.

Feel free to check out my code and tell me I'm crazy :)

**Comment by williamernest** [comment] 2018-10-31 16:51
Duplicate of #3666.

**Comment by kfranqueiro** [comment] 2018-10-31 17:07
I forgot we had that other task open. I suppose that task should resolve this from the perspective of libraries wrapping the foundation directly. I do wonder whether we even need the property change hooks at all though, if the _only_ thing they exist to support is directly changing checked state on the input element programmatically - we have a component API for doing that; shouldn't people use that?

Whatever we do, we just need to make sure that user interaction, programmatic component updates, and state restored by back/forward/refresh (where applicable, e.g. Chrome doesn't restore on refresh) still work.

**Comment by williamernest** [comment] 2018-10-31 17:20
The other task is to just move it to the component since we probably shouldn't be manipulating native DOM elements in the foundation anyways. This should alleviate the issue for framework wrappers, while still allowing our component to be continue working the way it has.

**Comment by kfranqueiro** [comment] 2018-11-01 19:32
I'm going to close this since it's tracked in #3666, and we're aiming to resolve it this month. Thanks for all the info, both here and on MDC React.

**Closed by kfranqueiro** 2018-11-01 19:32 UTC

**Comment by jamesmfriedman** [comment] 2018-11-01 21:18
Thanks Ken, much appreciated.
