### ISSUE TITLE
MDCDrawer dynamic list items

### ISSUE THREAD

**Issue by tanner0101** [material-components/material-components-web#3471] opened 2018-08-29 18:44 UTC
When changing the list elements in an MDCDrawer _after_ initialization, the focus behavior no longer works correctly. It is also seemingly impossible to destroy the drawer and re-initialize it succesfully (or any "relayout" function).

### What MDC Web Version are you using?

"@material/drawer": "^0.39.0",

### What browser(s) is this bug affecting?

Safari

### What OS are you using?

High Sierra

### What are the steps to reproduce the bug?

* Initialize an MDCDrawer with list items.
* Change the list items.
* Observe the clicking on list items on longer correctly focuses active item.
* Attempt to destroy / reinit the drawer.
* Observe that the list items still no longer correctly focus active item.

### What is the expected behavior?

Either MDCDrawer automatically detects re-layout, or there is a method for telling MDCDrawer that the list items have changed and it should re-initialize any necessary state.

### What is the actual behavior?

MDCDrawer has no apparent way of dealing with dynamically changing list items.

### Any other information you believe would be useful?

Discussed this with @moog16 in Discord. Thanks!

**Comment by williamernest** [comment] 2018-08-31 22:43
@tanner0101 Thanks for filing this issue. I think we resolved the list not destroying itself in v0.39.1. Can you provide a codepen reproducing your case? We're having trouble diagnosing a specific issue without a reproducible example. 

Thanks!

**Comment by kfranqueiro** [comment] 2018-09-06 16:56
Given no further details, I'm closing this issue since we resolved the one issue we were able to identify in v0.39.1. Let us know if you still encounter problems.

**Closed by kfranqueiro** 2018-09-06 16:56 UTC
