### ISSUE TITLE
An optional disabling "restoreFocus" feature when menu closes

### ISSUE THREAD

**Issue by apoterenko** [material-components/material-components-web#1977] opened 2018-01-17 14:17 UTC
## Feature Requests

Could you pls add the additional behaviour. I have an issue when using the SimpleMenu

### What MDC-Web Version are you using?

Latest version

### What browser(s) is this bug affecting?

All

### What is the expected behavior?

For example (or something like that):

```
menuAdapter.preventRestoreFocus() {
   thsi._preventRestoreFocus = true;
}
```

```
      restoreFocus: () => {
        if (this.previousFocus_ && !thsi._preventRestoreFocus) {
          this.previousFocus_.focus();
        }
      },
```

https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/index.js#L133

https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L560

### What is the actual behavior?

The UI works incorrectly in my specific case

### Additional Info

My current workaround is

```
this.input.blur(); // TODO
this.menu.show();
```

**Comment by acdvorak** [comment] 2018-01-18 19:51
Thanks for reporting this!

Seems like a bug to me.

When the menu closes, we should check if there's a newly focused element (e.g., because the user clicked on a different focusable element outside the menu). If so, we shouldn't steal focus.

**Comment by bonniezhou** [comment] 2018-02-01 19:33
Marking this as a duplicate of #2159

**Closed by bonniezhou** 2018-02-01 19:33 UTC
Labels: bug, in-tracker
