### ISSUE TITLE
MDC-Textfield required highlighting on init

### ISSUE THREAD

**Issue by jvalst** [material-components/material-components-web#2280] opened 2018-02-21 10:27 UTC
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> 0.31.0

### What browser(s) is this bug affecting?

Think every browser, I'm testing in Chrome

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

See https://codepen.io/anon/pen/LQmLZG

If I set the required in the Javascript on init, the field is highlighted red. 

### What is the expected behavior?

The highlighting should be set after the textfield has lost focus.

### What is the actual behavior?

The textfield has the red highlighting after init.

**Comment by kvdheuvel** [comment] 2018-02-21 12:25
This bug also appears on mdc-text-field--textarea.

**Comment by moog16** [comment] 2018-02-21 17:56
@jvalst this is a duplicate of https://github.com/material-components/material-components-web/issues/2029 and is currently being worked on in this PR https://github.com/material-components/material-components-web/pull/2201

**Closed** 2018-02-21 17:56 UTC
