### ISSUE TITLE
[MDCTextField] creates double events + helper text never appears

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#5600] opened 2020-02-12 11:00 UTC
## Bug report

When instantiating MDCTextField - events are registered double.
Also the helper text never appears.

### Steps to reproduce
see below

### Actual behavior

with this:
<img width="720" alt="Screenshot 2020-02-12 at 11 44 03" src="https://user-images.githubusercontent.com/4300051/74328672-9fce1780-4d8e-11ea-9d03-2e8560c151cc.png">

I get:
<img width="544" alt="Screenshot 2020-02-12 at 11 44 20" src="https://user-images.githubusercontent.com/4300051/74328636-92189200-4d8e-11ea-8f36-e94bc12c3ccf.png">

### Expected behavior

Only 1 focus event , 1 blur event, 1 mousedown, 1 touchstart ...

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.0.0-canary.8c11ea2a3.0
| Browser          | Chrome latest
| Operating System | Win 10

**Comment by cintaccs** [comment] 2020-02-12 11:05
Regarding the helper text - I have already tried instantiating the js component next to the MDCTextField - it makes no difference in behaviour - the helper text stays with opacity hidden state.
Btw - using sibling :focus css it should be possible to make the helper text appear and disappear without having to do any js instantiation or js events for the helper text show / hide.

**Comment by asyncLiz** [comment] 2020-02-12 19:04
Thanks for the issue! Can you add a codepen reproduction that shows the problem?

**Comment by cintaccs** [comment] 2020-02-12 19:19
If you don't see the same issue when looking at a standard outline MDCTextField and looking at the event in Chrome - you are welcome to close the issue - then it might be a canary issue or maybe my setup.  I have shown the HTML above - and it should be a copy of the documented examples. I currently can't find any with helper text in the demo's and docs to re-check.

Below is  the 2 events - in the canary latest - it is however 2 events close to each other in foundation - I am not sure I know how to set this up in codepen with canary version.


<img width="544" alt="Screenshot 2020-02-12 at 20 17 04" src="https://user-images.githubusercontent.com/4300051/74368928-cb73f080-4dd4-11ea-925a-4eb653d178e6.png">

**Comment by asyncLiz** [comment] 2020-02-14 17:30
I did a little more digging, and this is working as intended. One event listener is for [the textfield](https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/foundation.ts#L127) and the other is for [the ripple](https://github.com/material-components/material-components-web/blob/master/packages/mdc-ripple/foundation.ts#L131).

However, this is only present if the input is filled. It looks like in your code it's an outlined variant. I would double check to make sure you're not calling `MDCRipple.attachTo(outlinedInput)`.

Closing for now. Please re-open if you're still seeing the duplicate events for outlined variants!

**Closed by asyncLiz** 2020-02-14 17:30 UTC
Labels: bug
