### ISSUE TITLE
REACT with CRA incorrect webpack config for SCSS - loaders not working

### ISSUE THREAD

**Issue by CasperGrey** [material-components/material-components-web#3985] opened 2018-10-23 23:59 UTC
Hi,

I am currently using a CRA based app that im trying to use Material components web with. I have edited my dev config to include the suggested changes to the scss loaders but still i am getting the following compile error suggesting webpack is not able to find the correct modules..

> 
> ./node_modules/@material/button/mdc-button.scss)
> Module build failed:
> undefined
> ^
>       File to import not found or unreadable: @material/ripple/common.
>       in C:\Users\johnstonb\Documents\Project\cloudify\node_modules\@material\button\mdc-button.scss (line 23, column 1)

My webpack.config.dev.js and package.json

https://codepen.io/ben-johnston/pen/dggJPp

Can anyone assist in the correct config to make this work?

**Comment by jantimon** [comment] 2018-10-24 07:13
material-components does not follow the webpack standard so it is not compatible with webpack unless you have access to the webpack config which might be difficult for large angular or react projects.

Without the loader option you would still be able to resolve packages from the node_modules folders using a `~`.

```
@import "~@material/textfield/mdc-text-field";
```

However material-components is also using the `node_modules` alias internally so it will show error messages like:

```
@import "@material/animation/variables";
^
      File to import not found or unreadable: @material/animation/variables.
      in materialio-test/node_modules/@material/textfield/mdc-text-field.scss (line 23, column 1)
```

**Comment by williamernest** [comment] 2018-10-24 20:19
You might be able to get everything working with CRA and MDC Web by following the getting started guide from the Material Components for React [repo](https://github.com/material-components/material-components-web-react). I believe there's currently a way to do without ejecting. 

Using our components with Angular is also pretty straightforward but does require you to manually edit the `angular.json` file to add the `scss` includePaths.

**Comment by williamernest** [comment] 2018-10-24 20:31
We explored that option at one point but discovered the tilde (`~`) is a node specific. It isn't recognized/supported everywhere (for example, ruby sass doesn't support the tilde since they also have to import from gems).

**Comment by CasperGrey** [comment] 2018-10-24 22:30
> You might be able to get everything working with CRA and MDC Web by following the getting started guide from the Material Components for React [repo](https://github.com/material-components/material-components-web-react). I believe there's currently a way to do without ejecting.
> 
> Using our components with Angular is also pretty straightforward but does require you to manually edit the `angular.json` file to add the `scss` includePaths.

Already did that in the code and still didnt work

**Comment by jantimon** [comment] 2018-10-25 08:11
@williamernest that's true but is ruby still used?  
would it be possible to do a "search an replace" before you publish the code to npm (which is node specific)?

**Comment by williamernest** [comment] 2018-10-25 11:37
Rails users still use nom to install their node dependencies and then use rubysass to compile their sass files. Rubysass doesn't support the tilde. We do have users that are using rails and our components. 

@CasperGrey Can you tell me what you've tried or reproduce it in a separate repo? I'd like to get you working but it's sometimes easier to just look at the code.

**Comment by jantimon** [comment] 2018-10-25 12:02
Here is the create-react-app webpack.config.js (which can't be changed unless you eject):

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js

**Comment by williamernest** [comment] 2018-10-25 12:06
Here's the MDC React workaround for compiling sass without ejecting.

https://github.com/material-components/material-components-web-react/blob/master/README.md#step-3-using-sass

**Comment by robcaldecott** [comment] 2018-10-27 11:34
@CasperGrey Here is a sample ejected CRA2 project that uses MDC SASS/RMWC.

https://github.com/robcaldecott/rmwc-cra2-example

The trick is the following change to the webpack config to include `appNodeModules`

**webpack.config.dev.js, line 62**

```js
if (preProcessor) {
    loaders.push({
      loader: require.resolve(preProcessor),
      options: { includePaths: [paths.appNodeModules] }
    });
  }
```

**webpack.config.prod.js, line 87**

```js
if (preProcessor) {
    loaders.push({
      loader: require.resolve(preProcessor),
      options: {
        sourceMap: shouldUseSourceMap,
        includePaths: [paths.appNodeModules]
      }
    });
  }
```

**Comment by robcaldecott** [comment] 2018-10-27 11:38
FWIW I might publish a CRA2 `react-scripts` fork with this change so anyone can use it without ejecting.

**Comment by robcaldecott** [comment] 2018-10-27 12:54
@CasperGrey here you go (forked CRA2):

```bash
yarn create react-app my-app --scripts-version mdc-react-scripts
```

You can import the Material SASS without it throwing errors. HTH.

**Comment by jantimon** [comment] 2018-10-30 06:13
How will this work with mono repo approaches like lerna?
There you would have multiple node_modules directories.

**Comment by robcaldecott** [comment] 2018-10-30 15:42
@moog16 Someone tried a similar PR for CRA2 but it was rejected and they cited the `~` syntax that people can use (which does not work with MDC, see above.)

@jantimon I've just pushed 2.1.0 of `mdc-react-scripts` that includes the latest `create-react-app` 2.1.0 features (TypeScript!) and adds support for yarn workspaces (where `mdc-react-scripts` ends up hoisted.) I have not tried lerna but it might work.

**Comment by robcaldecott** [comment] 2018-10-30 15:56
@jantimon I just tried lerna (with and without `--hoist`) and it works.

**Comment by moog16** [comment] 2018-10-30 16:31
@robcaldecott can you share the PR you're talking about?

**Comment by robcaldecott** [comment] 2018-10-30 17:21
@moog16 This one: https://github.com/facebook/create-react-app/pull/5011

However, there is a new PR in flight which prompted a discussion about supporting `SASS_PATH` (which I didn't know about until today!)

https://github.com/facebook/create-react-app/pull/5599

It would be good to not have to eject or fork. Another option is `react-app-rewired` I guess.

**Comment by kfranqueiro** [comment] 2018-10-30 17:31
There's also https://github.com/facebook/create-react-app/issues/4494 which looks relevant.

On a quick glance it looks like node-sass does support SASS_PATH... interestingly, it looks like dart-sass might not currently?

I'm a tiny bit concerned of the usability of SASS_PATH if it needs to be absolute paths, when `node_modules` are installed locally to a given project, but it might be a start...

**Comment by robcaldecott** [comment] 2018-10-30 17:56
@kfranqueiro I just tried the `SASS_PATH` trick in a vanilla CRA2 install (by modifying `node_modules/react-scripts/config/env.js` directly as mentioned in that PR) and it works. I set `SASS_PATH` to `./node_modules`, so relative paths look OK.

It will be interesting to see what happens to that PR.

**Closed** 2018-11-05 22:39 UTC

**Comment by moog16** [comment] 2018-11-05 22:46
Closed this issue since we updated our guidelines in https://github.com/material-components/material-components-web-react/pull/393. This is a step-by-step guide on how to setup CRA-2 on Linux, MacOSX, and Windows. 

Please find new steps in the React Repo's [README](https://github.com/material-components/material-components-web-react/blob/master/README.md).

Also Thanks @robcaldecott for figuring out the `SASS_PATH`! All the credit goes to you.
