### ISSUE TITLE
MDC menu link inside mdc-list-item

### ISSUE THREAD

**Issue by torstahl** [material-components/material-components-web#1354] opened 2017-09-25 21:23 UTC
I want to click on a link inside an MDC Menu list item.
Clicking on the list item stops all propagation.
I'd like to use the MDC menu for a socialshare Menu and therefore it is necessary to click on the links to open it in a popup window.

**Comment by amsheehan** [comment] 2017-09-28 18:10
I believe we removed `Event.stopPropagation()`from most of our components. I'm wondering if you update to the latest version of MDC Menu if this problem will go away. If that does not fix it, please provide a Codepen so we can help investigate.

Further, in future issues, please follow the template provided.

**Comment by acdvorak** [comment] 2017-10-05 18:32
Closing this issue - feel free to reopen if you're still seeing the problem 🙂

**Comment by oleastre** [comment] 2017-10-12 15:48
I just stumbled on the same problem: cannot follow links in a menu.
After some search, the problem is not javascript related but comes from the CSS code.
There is a ::before pseudo-element on the mdc-list-item that is absolute and comes above the actual link. And that element prevents the event propagation => css problem.

**Comment by kfranqueiro** [comment] 2017-10-13 15:47
You're right, there are `::before` styles set up to shade the element when it is interacted with. It looks like we're missing `pointer-events: none` in those styles, whereas we have this for ripple already which prevents this issue from happening for ripples.

**Comment by oleastre** [comment] 2017-10-13 21:51
This will work but in a limited way: the link will be contained in a "LI" element and both have different sizes (see screen shots).  
![capture](https://user-images.githubusercontent.com/838332/31567653-da16f0fa-b070-11e7-96b3-b1cc54377783.png)

I suppose the user expects the whole li surface to be clickable and not only the link; 
But this is maybe another problem not related to this one.

**Closed** 2017-10-13 23:27 UTC

**Comment by acdvorak** [comment] 2017-10-17 22:41
@oleastre: The `::before` pseudo-element has `pointer-events: none`, so clicking on it will fall through to the `mdc-list-item` element.

Also, as @amsheehan mentioned, we removed `Event.stopPropagation()` from all but one of our components, so as long as you're on the latest version of MDC-Web, you shouldn't have a problem.

**Comment by ahlechandre** [comment] 2018-08-11 14:14
Workaround:

```css
.mdc-menu .mdc-list-item a {
  width: 100%
}

```
